### ISSUE TITLE
How to write a multimatch query with individual field boosting using NEST & LINQ?

### ISSUE THREAD

**Issue by martinwidmer** [elastic/elasticsearch-net#1139]
How to write a multimatch query with individual field boosting using NEST & LINQ?

**Comment by bgiulianetti** [comment]
I know this issue is closed, but maybe this helps someone, since i have not found an example of a multimatch query search without defining a given type. I spent a few days trying to work it out and i came up with the solution

Here i leave the same method as above but using Generics, and passing a dictionary with the fields and boosts, since you will not have the intellisence writing with the fluent expression. I also added the skip and take (or from and size) methods, the Type of Search and an array of the indexes you want to perform the search.

           var dic = new FluentDictionary<string, double?>();
            dic.Add("Field1", 1.0);
            dic.Add("Field2", 1.0);

           var response = Client.Search<T>(s => s
                                            .Skip(0)
                                            .Take(5)
                                            .Indices(indexes)
                                            .Query(q => q
                                                .MultiMatch(m => m
                                                    .OnFieldsWithBoost(b => 
                                                    {
                                                        foreach (var entry in dic)
                                                            b.Add(entry.Key, entry.Value);     
                                                    })
                                                    .Type(TextQueryType.Phrase)
                                                    .Query("your query text")
                                                    )
                                                 )
                                            );
