### ISSUE TITLE
Support for Named Queries missing in NEST Query DSL?

### ISSUE THREAD

**Issue by daflookie** [elastic/elasticsearch-net#1186]
Per [ES docs](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-named-queries-and-filters.html), since 0.90.4 each query can support a Name via the "_name" property, however, this looks to be missing in NEST.  The resultant "matched_queries" string array on each hit in the response would also need to be added.

I am looking to leverage this feature in an existing project.  If it indeed is not present would you be interested in a PR that adds it?  The documentation states all queries support this, and for starters I'm not sure if that literally means 100% of all possible query types or not (MLT, geo related, fuzzy, etc).  If you know that answer off hand great, if not I could dig around in the ES source itself to try and figure that out so we have complete coverage.

**Comment by gmarz** [comment]
Nice catch @daflookie.

It looks like this is implemented on the request side for filters:

https://github.com/elasticsearch/elasticsearch-net/blob/develop/src/Nest/DSL/Filter/FilterDescriptor.cs#L15

https://github.com/elasticsearch/elasticsearch-net/blob/develop/src/Nest/DSL/Filter/FilterDescriptor.cs#L940

but missing entirely for queries, and on the response for both.

We should do something along the same lines as this for `QueryDescriptor<T>`, and also add `matched_queries` to `ISearchResponse`.

A PR for this would be awesome if you're up for it :+1:.  Let us know if you need any help getting started or get stuck anywhere..  No need to dig through the ES source code to find all the queries that support `_name`...the majority of them do, if not all- at least enough to justify doing this at a base level like we're already doing for filters.

**Comment by gmarz** [comment]
Hey @daflookie 

Just want to touch base with you and see if you've taken a crack at this yet?  We'd really like to have this for our upcoming 1.4 release and are contemplating just implementing ourselves- but don't want to crush any progress you've made if you're on the brink of opening a PR.

**Comment by daflookie** [comment]
Sorry @gmarz - I had a couple setbacks outside of getting this done, and didn't devote the kind of time I was expecting those first few days.

I haven't pushed changes to my fork, but in a nutshell the response side of things and updating the NamedFilter's integration test is totally straightforward and completed.  The response side was just a couple of changes so there really is no lost work/effort IMO. 

I was aiming to implement query names at a base level like you recommended, but it seems to me there is much more judicious use of base and abstract classes for Nest's filters compared to queries.  Almost all the filter and filter descriptors inherit from PlainFilter and FilterBase respectively (and more importantly both of those implement IFilter).  On the query side however there looks to be more touch points than I was anticipating when giving IQuery a QueryName property.  So much so that I just now took a step back to contemplate the optimal approach.

If you guys want to implement yourself no prob.  I'm not too close to this lib, but if it were me I'd consider refactoring it to have both PlainQuery and QueryBase implement IQuery (like filters).  Eventually other query-wide properties like Boost could also find there way.

Thoughts from here?

**Comment by gmarz** [comment]
No need for an apology @daflookie :).  We appreciate you opening an issue and bringing this to our attention, let alone attempting to implement it yourself :+1:.

I definitely agree that our query objects could benefit from some further/better abstraction, but it's probably more of a 2.0 thing as we have a pretty strict backwards compatibility policy that we need to oblige to.  In the mean time, we're better off fitting this into what we currently have in place as best as we can.

We'll go ahead and implement this - thanks again for your efforts and for opening this issue!

**Comment by daflookie** [comment]
Sounds good looking forward to seeing this released.  Am I right that when this issue is closed I could leverage it with the bleeding edge packages you all publish?

**Comment by gmarz** [comment]
That is correct.

**Comment by gmarz** [comment]
Breaking this issue into two issues:

#1217 - for adding `matched_queries` to `ISearchResponse` so at least named filters will be fully implemented.

Leaving this issue open for adding support for named queries, but this will most likely be a 2.0 change since it requires heavy refactoring of the current query objects.

**Comment by gmarz** [comment]
@daflookie FYI ^^

**Comment by daflookie** [comment]
Thanks for the heads up

**Comment by bytenik** [comment]
This feature is really important for us at FunnelFire too.

**Comment by bytenik** [comment]
Has there been any progress on this? If not I will take a crack at it.

**Comment by gmarz** [comment]
@bytenik as mentioned earlier we decided not to attempt this until 2.0 since it will likely require a decent amount of refactoring, which we would want to be able to do freely without worrying about backwards compatibility.

Filters are able to pull it off because the current implementation is to write all the meta data fields like `_name` using custom converters: https://github.com/elasticsearch/elasticsearch-net/blob/develop/src/Nest/Resolvers/Converters/Filters/TermsFilterConverter.cs#L62

Not an ideal approach, and would be a ton of work to do the same for all query types.  That said, I've only attempted this once and gave up pretty quickly :).  If you can come up with a bwc solution for 1.x that would be awesome and really appreciated.

**Comment by Mpdreamz** [comment]
@daflookie @bytenik 

Its pretty certain queries and filters are gonna be merged into a single construct in elasticsearch 2.0 (see also: https://issues.apache.org/jira/browse/LUCENE-1518) 

With that in mind it might make sense not to implement it, since we can't in our `1.x` release cycle without breaking and our `2.0` release will have feature parity with elasticsearch `2.0`

Just throwing this out there, I'm still going to investigate a way we might be able to do this in a `1.x` without introducing breaking changes.

**Comment by bytenik** [comment]
Actually the latest two comments on that Lucene ticket seem to indicate they're considering reverting that.

**Comment by bytenik** [comment]
If I can do this using an "elegant hack," are you interested? Its not code I would want to keep around forever, but I think I can do this relatively easily with a bit of clever coding with a single converter. It would work as a stopgap until all of the refactoring occurs.

**Comment by bytenik** [comment]
Maybe I don't understand the issue because I haven't dug in enough. `IQuery` seems to be the base of every query. Was that not the case in Jan when @daflookie looked at this? Otherwise, why can't this be done with a property on `IQuery`, the same as its done with a property on `IFilter`?

Is it just the lack of a base class on which to put the fluent method to set the property?

**Comment by Mpdreamz** [comment]
@bytenik sorry for not updating my progress, I've been spiking support for this during elasticon and so far its looking good. 

It's a heavy refactor since we need to write tests for named queries on each of the individual queries to make sure all the custom serializers behave well with regards to `_name`. 

From the point where I'm at right now it does look like we can do this without introducing breaking changes.

**Comment by Mpdreamz** [comment]
And your bang on re: `IQuery` by the way :+1:

**Comment by bytenik** [comment]
If you want to branch and push I would be happy to help.

**Comment by Mpdreamz** [comment]
Hi @bytenik @daflookie 

I just pushed https://github.com/elastic/elasticsearch-net/pull/1274 which adds support for named queries. 

Thanks for the offer the help @bytenik, writing code wise it was not difficult but simply just a lot of touched files that needed updating hence hard to update. 

If you are able to give the PR a quick review that'd be much appreciated!

**Comment by bytenik** [comment]
Looks great to me.
