### ISSUE TITLE
ElasticClient timeout semantic changed

### ISSUE THREAD

**Issue by UdiBen** [elastic/elasticsearch-net#1262]
Hi,
In the past, the semantic of timeout for elasticclient was an invalid response.
In the current version, the client throws WebException.
Is there an easy way to restore the semantic of timeout (in the client level) that does not throw? Or at least an easy way to return an invalid ISearchResponse?
Does it make sense to add such behavior?

Thanks,
Udi

**Comment by Mpdreamz** [comment]
Hi @UdiBen 

As far as I can remember we never had any special routine to handle WebException/SocketException and inspect whether it was a timeout related exception. Right elasticsearch does not fully obey timeouts as can be clearly seen in this issue I opened sometime ago:

https://github.com/elasticsearch/elasticsearch/issues/6918

Once elasticsearch implements: https://github.com/elasticsearch/elasticsearch/pull/4586 we can introduce the option of timeouts to be actual soft responses because we can rely on getting actual responses back before WebRequest kills the socket and starts throwing hard exceptions.
