### ISSUE TITLE
Update that returns fields from document

### ISSUE THREAD

**Issue by jcachat** [elastic/elasticsearch-net#1296]
I am trying to execute an Update that returns fields from the source document.  It works fine when I do it manually (curl, etc) but when using the .Net client, I am able to specify the fields but Nest.IUpdateResponse doesn't seem to provide any way to get them.  In fact, response.ConnectionStatus.ResponseRaw is just null.  The RequestUri does contain the "&fields=_source" parameter so it seems like it's executing correctly.

Is this something that is just not supported or is there something else I need to do to get these fields from the response?

**Comment by Mpdreamz** [comment]
This should be working, will investigate before next release. 

`response.ConnectionStatus.ResponseRaw` will only be set if you specify `ExposeRawResponse()` on `ConnectionSettings`

**Comment by Mpdreamz** [comment]
This was indeed blatantly missing! added a PR. 

Please note that due to backwards compat reasons the syntax is a bit verbose:

``csharp
update.Get.Found;
//get loc property from _source
update.Source<ElasticsearchProject>().LOC; 
//get loc field
var fieldLoc = update.Fields<ElasticsearchProject>().FieldValues(p => p.LOC);
```
