### ISSUE TITLE
SniffingConnectionPool handling of node types

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-net#1322]
From discussion with @gmarz, the current implementation of SniffingConnectionPool does not take into account the ES node type.  In general, we do not recommend sending search and indexing requests to dedicated master nodes.  It will be nice for the sniffing functionality to identify nodes but filter out the master only nodes to prevent requests from being sent to the master only nodes.

**Comment by Mpdreamz** [comment]
++

Grave omission from the current implementation thats been on the backlog for too long.

We should skip data nodes, in addition to this in 2.0 the sniffing part will be injectable and responsibility of `IConnectionPool` itself so its easier to override default behavior here.

**Comment by Mpdreamz** [comment]
bumping this because we need a discussion with the other clients to come up with general rules here

**Comment by Mpdreamz** [comment]
Closing this because we recommended using dedicated clients for different subset of calls if needed. E.g a ConnectionPool that only accepts nodes with the ingest role for ingest bulk indexes. 

Subclassing SniffingConnectionPool and overriding Reseed is already supported to bake in custom filter rules.

**Comment by Mpdreamz** [comment]
@elastic/microsoft closed this but if you feel otherwise lets reopen to discuss
