### ISSUE TITLE
How to retrieve search request URL even when Search throws an exception

### ISSUE THREAD

**Issue by bittusarkar** [elastic/elasticsearch-net#1332]
Normally I can get the request URL from search response as under.
```
var response = client.Search<T>(s => s.Query(...));
var requestUrl = response.ConnectionStatus.RequestUrl;
```
If `Search()` throws an exception then `response` is `null` and I can no longer retrieve the value of search request URL. Is there another way of doing it?

**Comment by Mpdreamz** [comment]
Yeah we do not actually wrap exceptions (unless a maxretry is set) so if WebRequest throws an exception that exception bubbles out of the client. 

We are looking into a more unified exception design for `2.0` this could be a good reason to wrap all exceptions. 

closing this for now because its the status quo but will open a new exception design for 2.0 ticket in the coming weeks

ping @gmarz  :)
