### ISSUE TITLE
Terms Aggregation: Support for sorting on multiple criteria

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch-net#1348]
https://github.com/elastic/elasticsearch/pull/7662

**Comment by Mpdreamz** [comment]
Started on this here: https://github.com/elastic/elasticsearch-net/commit/9e4551de121b085e69fad0acb0fea11b20be40c3 but as it stands now we need to write our own serializer for the terms aggregation in order to choose either the old or new ordering property.. 

letting this bake in the hopes we can come up with something cleverer during as the day progresses :)

**Comment by gmarz** [comment]
This is fixed in [2.0](https://github.com/elastic/elasticsearch-net/blob/2.0/src/Nest/Aggregations/Bucket/Terms/TermsAggregation.cs#L58).  Don't think we should do anything for the 1.x branch.
