### ISSUE TITLE
Serialization of long datatype in range query

### ISSUE THREAD

**Issue by judewood** [elastic/elasticsearch-net#1375]
Hi

When I serialize C# long datatype values in a range query then the NEST serialiser converts the values to scientific notation causing the search  to return no results.
As an example this SearchDescriptor:

var sd = new SearchDescriptor<MyEntity>().Query(q => (q.Range(r => r.OnField(p => p.Id).Greater(913684354165972099)) && q.Range(r => r.OnField(p => p.Id).Lower(913684354165972104))));

serializes to:

{ "query": { "bool": { "must": [ { "range": { "id": { "gt": "9.13684354165972E+17" } } }, { "range": { "id": { "lt": "9.13684354165972E+17" } } } ] } }}

but it should serialize to:

{ "query": { "bool": { "must": [ { "range": { "id": { "gt": "913684354165972099" } } }, { "range": { "id": { "lt": "913684354165972104" } } } ] } }}

Thanks

Regards

Jude Wood

**Comment by Mpdreamz** [comment]
Hey @judewood thanks for reporting this, sadly this ties into a bigger issue that we can't change without introducing breaking changes in our `1.x` releases. We need to stay binary compatible at an assembly level due to our strong naming policy which allows a complex project graph with different NEST `1.x` references to work fine even if a higher version then referenced at compile time ends up in bin without needing assembly redirects. 

This is great but introduces very very stringent backwards compatibility demands that cause us to not be able to really properly address this issue until `2.0` which will be the next release after `1.5`

We currently track this issue here https://github.com/elastic/elasticsearch-net/issues/1215

The workaround for now is to manually do the tostring before passing it to the Range query.
