### ISSUE TITLE
Question: Handling timeouts / ping exceptions

### ISSUE THREAD

**Issue by jeroenslor** [elastic/elasticsearch-net#1439]
Hi,

Our test server is currently using a free hosted elasticsearch solution. Since its free its not that fast / stable. Now and then im getting the error messages below. What is the best way to handle / avoid this? Set a maxretry, increase ping timeout, increase normal timeout, disable ping? For the context, im just doing a relative simple search.

Exception 1
[WebException: The operation has timed out]
   System.Net.HttpWebRequest.GetResponse() +6542104
   Elasticsearch.Net.Connection.HttpConnection.DoSynchronousRequest(HttpWebRequest request, Byte[] data, IRequestConfiguration requestSpecificConfig) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:266
 
[Exception: ping returned no status code]
   Elasticsearch.Net.Connection.Transport.Elasticsearch.Net.Connection.ITransportDelegator.Ping(ITransportRequestState requestState) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\Transport.cs:98

Exception 2 :
PingException: Pinging xxx caused an exception]
   Elasticsearch.Net.Connection.<>c__DisplayClass0.<Elasticsearch.Net.Connection.ITransportDelegator.PingAsync>b__1(Task`1 t) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\Transport.cs:143
   System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke() +81
   System.Threading.Tasks.Task.Execute() +45
 
[MaxRetryException: Failed after retrying 0 times: 'POST xxx/_search'. 
InnerException: PingException, InnerMessage:  Pinging xxx caused an exception, InnerStackTrace:    at Elasticsearch.Net.Connection.Transport.<>c__DisplayClass0.<Elasticsearch.Net.Connection.ITransportDelegator.PingAsync>b__1(Task`1 t) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\Transport.cs:line 143

**Comment by gmarz** [comment]
Hey @jeroenslor 

Judging by those exceptions, it's obvious the ping requests are the problem, which are supposed to be quick, lightweight calls- and so have a very small default timeout.

What version of NEST are you on?  The default ping timeout use to be very aggressive...50ms prior to 1.3, which we increased to 200ms, and now the default is 1s since version 1.4 (2s if using SSL).

If 1 second is still too stringent, then I would first try increasing the ping timeout to maybe 5 seconds, and decrease from there until you find the lowest acceptable threshold.

**Comment by gmarz** [comment]
Closing this for now.  Feel free to reopen if this is still an issue @jeroenslor.

**Comment by sundertinwar** [comment]
I was running into same problem and via updated my nugget package I got rid of this problem. I used version 1.7
