### ISSUE TITLE
[Nest] Sort by script using ISearchRequest

### ISSUE THREAD

**Issue by prychel** [elastic/elasticsearch-net#1443]
Hi,

Is it possible to sort by script using ISearchRequest from Nest namespace? 
I want to achive following request but I cannot see such option in Sort property:
"sort": [
    {
        "_script" : {
            "script" : "doc['priceMatrix.prices.X'].value > 0 ? doc['priceMatrix.prices.X'].value : doc['priceAmount'].value",
            "type" : "number",
            "params" : {
                "factor" : 1.1
            },
            "order" : "asc"
        }
    }
  ],

I've noticed that in DSL query there is SortScript descriptor but I cannot use DSL due to restrictions for aggregations (I cannot create a list of aggregations and pass it to AggregationDescriptor).

I would be very greatfull for an answer.
Paweł

**Comment by gmarz** [comment]
Hey @prychel

Here's how this can be achieved using the object initializer syntax:

```csharp
var request = new SearchRequest
{
	Sort = new List<KeyValuePair<PropertyPathMarker, ISort>>
	{
		new KeyValuePair<PropertyPathMarker, ISort>("_script", new ScriptSort
			{
				Script = "doc['priceMatrix.prices.X'].value > 0 ? doc['priceMatrix.prices.X'].value : doc['priceAmount'].value",
				Type = "number",
				Params = new Dictionary<string, object> 
				{ 
					{ "factor", 1.1 } 
				},
				Order = SortOrder.Ascending
			})
	}
};
```

Note, we're aware of how verbose this syntax is and it has already been improved in the 2.0:  [`Sort` is just a `List<ISort>` rather than `List<KeyValuePair<PropertyPathMarker, ISort>>`](https://github.com/elastic/elasticsearch-net/blob/2.0/src/Nest/DSL/SearchDescriptor.cs#L49).

Also, to access `ScriptSort` you need to include the `Nest.DSL.Descriptors` namespace.  This is a bug, but unfortunately can only be fixed in the 2.0 branch since it would introduce a breaking change.
