### ISSUE TITLE
Aggregations are not scoped to search results

### ISSUE THREAD

**Issue by YatishGupta** [elastic/elasticsearch-net#1460]
Hi,

I am new to Nest and I am facing problem with Aggregations.
Basically, I am firing something like following:

                results = _client.Search<Item>(new SearchRequest
                {
                    From = 0,
                    Size = 50,
                    Query = BuildQuery(),
                    Filter = BuildFilter(),
                    Sort = BuildSort(),
                    Aggregations = BuildAggregations()
                });

Where Query has some term for _all.
Filter is a bool filter having some must conditions (combination of exists and range).
Sort is having one descending field.
Aggregation is a term aggregation based on a field not contained in query or term.

I am getting hits and aggs in the results, however, aggs are not scoped to the query search and filter output. Instead, I am getting aggs as per global scope. 
If I put filter aggregation before my term aggregation, I am getting correct results. However, that does not solve my problem generically in the scope of the project (also, how will it solve problem along with _all term Query).

I went through the documentations and found that there is a Global aggregation which makes the aggregations global and by default it should have been in search result scope itself.

What am I missing here? Please help.

Thanks and regards,
 Yatish

**Comment by gmarz** [comment]
Hey Yatish

This is a common pitfall when first learning Elasticsearch.  The problem here is that you're executing a query and a filter separately, and the filter is acting as a [post filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-post-filter.html).  Meaning it's applied after everything else, including your aggregations.

Instead, you want to use a [filtered query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-filtered-query.html), which has both a query and a filter portion:

```csharp
results = _client.Search<Item>(new SearchRequest
{
    From = 0,
    Size = 50,
    Query = new QueryContainer(new FilteredQuery
            {
                Query = BuildQuery(),
                Filter = BuildFilter()
            },
    Sort = BuildSort(),
    Aggregations = BuildAggregations()
});
```

This will reduce your aggregation scope your search results.  Hope that helps!

**Comment by YatishGupta** [comment]
Thanks a lot Greg for immediate help.
Exactly what I was looking for.
