### ISSUE TITLE
How to Inspect the query being sent to elastic

### ISSUE THREAD

**Issue by sallgeud** [elastic/elasticsearch-net#1473]
I had thought, based on ISearchRequest, that I could simply do a JsonConvert.Serialize(mySearchDescriptor) and get the value that would be sent. However, this does not appear to be the case.  Any advice would be appreciated.

**Comment by gmarz** [comment]
You need to use the same Json.Net settings/contract as the client in order to serialize it the same way.  

For that reason, `IElasticClient` exposes it's serializer:

```
var client = new ElasticClient(...);
var json = Encoding.UTF8.GetString(client.Serializer.Serialize(mySearchDescriptor))
```

The above should work, however a better and easier approach is to inspect the [ConnectionStatus.Request](https://github.com/elastic/elasticsearch-net/blob/develop/src/Elasticsearch.Net/Domain/Response/IElasticsearchResponse.cs#L59) property on response after the request has been sent, which will contain the exact JSON payload:

```
var response = client.Search<ElasticsearchProject>(...);
var json = Encoding.UTF8.GetString(response.ConnectionStatus.Request);
```

You can also enable pretty JSON for better readability:

```
var settings = new ConnectionSettings(...).PrettyJson();
var client = new ElasticClient(settings);
```
