### ISSUE TITLE
No standard scroll parameter in ScrollRequestParameters

### ISSUE THREAD

**Issue by comdiv** [elastic/elasticsearch-net#1488]
Cannot provide pull request while i'm not a member of ES repository and cannot look at 
https://github.com/elasticsearch/elasticsearch-rest-api-spec and problem .cs file is auto generated.

Scroll API of ES has very important "scroll" GET parameter to set wait timeout for subsequent calls to Scroll queries. 

For now i need to use AddQueryString("scroll","1m") to work with it. 

It's  very important because without this parameter ES drops scroller after first call to it.

Assert to check https://github.com/elasticsearch/elasticsearch-rest-api-spec and if there is mistake in it to request fix.

**Comment by Mpdreamz** [comment]
Are you using the highlevel client (`ElasticClient`) or the lowlevel client `ElasticsearchClient` ?

If you are using the highlevel client we force the request to be a POST (because scroll_id's can be huge!) and do in fact allow you to set the `scroll`

https://github.com/elastic/elasticsearch-net/blob/08b27b7028ca10bc8fbcf5f2eec238e74801c815/src/Nest/DSL/ScrollDescriptor.cs#L26

The `scroll` param is so important we forced on the request and constructor itself in the highlevel client:

https://github.com/elastic/elasticsearch-net/blob/08b27b7028ca10bc8fbcf5f2eec238e74801c815/src/Nest/DSL/ScrollDescriptor.cs#L35

We do not generate it on the requestparameters so that there are not two ways to set `scroll` in the highlevel client.

**Comment by comdiv** [comment]
ElasticsearchClient, ok will use addquerystring
