### ISSUE TITLE
Emulating one to many relationship

### ISSUE THREAD

**Issue by shoushouleb** [elastic/elasticsearch-net#1532]
hi, 
I have a database tables t1 and t2, t1 has one to many relation with t2.
What I need to do is to create  class T1 that has propertyy t2fk, and each instance of this class may have many values of t2fk ( emulating one to many relationship of the database), how can i do it so I can use it in indexing and searching via NEST.( is multi fields applicable here?)

thanks

**Comment by KodrAus** [comment]
This isn't really a scenario for multi fields. 
Your choice of words 'emulating' is a good one, because Elasticsearch doesn't do complex hierarchies. You have 2 options here:

- [Nested objects](https://www.elastic.co/guide/en/elasticsearch/guide/current/nested-objects.html) if you're not really going to touch the children independently of the parent. The parent and its children are indexed together as a single document in Elasticsearch. This is easy to work with for indexing and searching.

- [Parent / Child](https://www.elastic.co/guide/en/elasticsearch/guide/current/parent-child-mapping.html) if you want to be able to manage the children independently of the parent. The children are indexed independently. You need to use [Aggregations](https://www.elastic.co/guide/en/elasticsearch/guide/current/children-agg.html) to fetch all the children for your parent.

For the nested objects, what you want is basically just a standard C# class hierarchy:

```
using System;
using System.Collections.Generic;
using Nest;

namespace Test
{
	public class Parent
	{
		public string MyProperty { get; set; }

		public List<Child> Children { get; set; }
	}

	public class Child
	{
		public string MyProperty { get; set; }
	}

	public class Program
	{
		static void Main(string[] args)
		{
			var client = new ElasticClient(new ConnectionSettings(new Uri("http://localhost:9200")));

			var parent = new Parent
			{
				MyProperty = "Parent",
				Children = new List<Child>
				{
					new Child
					{
						MyProperty = "Child 1"
					},

					new Child
					{
						MyProperty = "Child 2"
					}
				}
			};

			client.Index<Parent>(parent, idx => idx.Index("test_index"));
		}
	}
}
```

What you end up with in Elasticsearch is this:

```
GET test_index/_search
RESPONSE:
{
  "took" : 36,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test_index",
      "_type" : "parent",
      "_id" : "AU9fIYUuVHoamL62EY2V",
      "_score" : 1.0,
      "_source":{
  "myProperty": "Parent",
  "children": [
    {
      "myProperty": "Child 1"
    },
    {
      "myProperty": "Child 2"
    }
  ]
}
    } ]
  }
}

```

```
GET test_index/_mapping
RESPONSE:
{
  "test_index" : {
    "mappings" : {
      "parent" : {
        "properties" : {
          "children" : {
            "properties" : {
              "myProperty" : {
                "type" : "string"
              }
            }
          },
          "myProperty" : {
            "type" : "string"
          }
        }
      }
    }
  }
}
```
I haven't worked with parent/child hierarchies in Elasticsearch before, because I've never needed them personally. But if you want to try them out, have a look at the links above.

**Comment by shoushouleb** [comment]
Thank you for your help, I will go for the nested object, but my question now, how can I search for a property in the parent and in the child at the same time.

Thanks for being very helpful.

**Comment by shoushouleb** [comment]
Hi,
I have managed to do it using Head plugin :
<code>
   lstDoc = elastic.Search<Document>(s => s
                     .From(0)
                     .Size(1000)
                     .Query(q => q
                         .Bool(a => a.Must(b => b.Term("Document.lstChildren.NestedMultiField", input)))));

</code>

Thank you

**Comment by KodrAus** [comment]
All good, glad you've got it working!

**Comment by gmarz** [comment]
@KodrAus thanks for the awesome and detailed answer here- really, really appreciated!
