### ISSUE TITLE
Term Filter with string field and string.empty as term doesn't work

### ISSUE THREAD

**Issue by paolopiaggio** [elastic/elasticsearch-net#1552]
I've been playing with ES and NEST for last 2 weeks, so I am pretty new to it, but the following scenario seems to behave in an unexpected way to me. 

Must(m=>m.Term("someStringProperty", "")) 

is translated into 

"must": []

and not into

"must": [
    {
        "term" : 
        {
            "someStringProperty":""
        }
    }
]

NOTE:
If you instead use a Terms Filter, passing in the IEnumerable<string> collection two item, string.empty and another one, for instance "test", this is translated as expected to:

"must": [
    {
        "terms" : 
        {
            "someStringProperty":["","test"]
        }
    }
]

**Comment by Mpdreamz** [comment]
This is due to NEST's conditionless query support see: http://nest.azurewebsites.net/nest/writing-queries.html

You can use 

```
Must(m=>m.Verbatim().Term("someStringProperty", ""))
```

To force the query to be send verbatim even if its `conditionless`. You can also make `conditionless` queries an exception by using `.Strict()` anywhere in your query graph and it will propagate its strictness (on/off) to child queries. The documentation goes into this.

`Verbatim()` is not well documented, something we're mitigating in the 2.0 release.

**Comment by paolopiaggio** [comment]
Wonderful, thanks!
