### ISSUE TITLE
Support for multi field attribute-based mapping

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch-net#1561]
This has been requested multiple times in the past.  Should we support this?

If so, how should it look in the [new 2.0 mapping API](https://github.com/elastic/elasticsearch-net/pull/1520)?  How should we distinguish the main field form sub-fields?

Thinking out loud, here are a few ideas:

**One approach (order of attributes):**

```csharp
public class Foo
{
    [String]
    [String(Name = "bar.raw", Index = FieldIndexOption.NotAnalyzed)]
    public string Bar { get; set; }
}
```

Order of the attributes matter, the first attribute is the main field.

**Another approach (explicit sub-field flag):**

```csharp
public class Foo
{
    [String(SubField = true, Name = "bar.raw", Index = FieldIndexOption.NotAnalyzed)]
    [String]
    public string Bar { get; set; }
}
```

Order doesn't matter, sub-fields are indicated via a flag and we throw when we find more than one main field.

**Comment by TheFireCookie** [comment]
I think you/we need to take the decision of how you/we want NEST users to write the mappings.
Either you push to use the attribute and you then add multifield support in attribute (I prefer the second approach in your post, I don't like to be dependant of the attribute order).

Either you push to use the mapping fluent API and then you restrict the attribute mapping to the strict minimum (name?).

**Comment by Mpdreamz** [comment]
+1 @TheFireCookie this is very much what we set out to do. 

Mapping in code is always preferred simply because attributes can never express everything since it needs to be a compile time constant.

That said bootstrapping mapping from attribute can be really really handy and is used quite often, we even briefly discussed getting rid of attribute based mapping all together but received some push back on that when we sampled some of our users.

If we are going to support this I would like to see

```
public class Foo
{
    [String(Name = "bar")]
    [MultiField(Name = "raw", Index = FieldIndexOption.NotAnalyzed)]
    public string Bar { get; set; }
}
```

MultiField being a subclass of StringAttribute and thus limiting ourselves to only support string multifields in attribute based mapping. A multifield attribute that does not have an accompanying string attribute should result in an exception.

Off topic:

@gmarz going over our current `IStringMapping` i think it needs to be split moving all the properties that the attribute can set to `IStringAttributeMapping` that `IStringMapping` then implements.

[StringAttribute](https://github.com/elastic/elasticsearch-net/blob/2.0/src/Nest/Mapping/AttributeBased/StringAttribute.cs) can then implement `IStringAttributeMapping` explicitly and proxy the current non nullable properties to these. 

Then [this constructor](https://github.com/elastic/elasticsearch-net/blob/2.0/src/Nest/Mapping/Types/Core/String/StringProperty.cs#L54) will no longer use `default(T)` for various options never specified.

**Comment by Mpdreamz** [comment]
@gmarz do you feel strongly about supporting multifield through attribute mapping? 

I vote :-1:

**Comment by russcam** [comment]
Supporting `multi_field` through attributes feels awkward to me with the potential to easily get it wrong; if it were to be supported, I quite like @gmarz's second option with an explicit `SubField` property.

I think we should be encouraging usage of the fluent mapping API for this though so vote :-1: overall

**Comment by gmarz** [comment]
I'm fine with not supporting this for now.  However, if it comes up again I think we should reconsider.

**Comment by RobinRieger** [comment]
Bit late to the party, but I would have thought it would be a good idea to support multi field attributes. I mean, I was hand writing all the mappings but am now changing to use Nest to make the mappings. I can do everything via the attributes and have all my logic re the mapping for a class in the same file with the attributes.... except multi fields. I need to move the logic re the multi fields to the 'map' call, away from all my other mapping logic in the 'class'. Personally I don't like splitting logic like that across different places. I would feel it is easier to maintain the mappings and logic for the mappings all in the 'class' files via attributes.... Just my two cents.....

**Comment by Romanx** [comment]
Just a thought here as i also started migrating to 2.0 and required multi_field mappings and had to split them into the fluent mapping and my poco.

Perhaps the user could implement some kind of interface `IMultifieldMapper` or something which has a simple method which has the signature `TypeMappingDescriptor Map<T, TypeMappingDescriptor>` that will allow you to define the `multi_field` mapping exactly as you do in the fluent interface but while keeping the logic localized to the type class in question. The AutoMapper could then look for this interface and map using that.

Excluding the awful naming would anyone be opposed to this idea apart from the fact you would have two approaches for performing the same action?

**Comment by RobinRieger** [comment]
Lol. I did something very similar to this today after posting my comment. All my classes for ES now use an interface similar to what U described. It seems to work well because attributes come first and then get overriden if the method in the interface has an class specific logic. After building this today I actually don't need an attribute anymore because I can use the fluent mapping and still keep all the logic in one spot, which was my issue this morning when I saw the attribute was missing :P

**Comment by gmarz** [comment]
@Romanx @RobinRieger You can actually achieve this using a custom `PropertyVistitor` and passing it to `.AutoMap()`.  See [the docs on AutoMap](https://github.com/elastic/elasticsearch-net/blob/master/src/Tests/ClientConcepts/HighLevel/Mapping/AutoMap.doc.cs#L746) for details (sorry our new documentation is still a WIP).

For multi fields, It would look something like this:

```csharp
public class MyPropertyVisitor : NoopPropertyVisitor
{
	public override void Visit(IStringProperty type, PropertyInfo propertyInfo, ElasticsearchPropertyAttribute attribute)
	{
		if (propertyInfo.Name == "MyProperty")
		{
			type.Fields = new Properties
			{
				{ "raw", new StringProperty { Index = FieldIndexOption.NotAnalyzed } }
			};
		}
	}
}
```

Then when calling `AutoMap()`:

```csharp
.Map<MyType>(m => m.AutoMap(new MyPropertyVisitor()))
```
This would add a non-analyzed string sub-field named `raw` to any string property named `MyProperty` on your POCO.

Alternatively, total different route, but you can also leverage [dynamic templates](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/dynamic-templates.html) to accomplish the same thing.  [Check out how we setup our indices for our unit tests](https://github.com/elastic/elasticsearch-net/blob/master/src/Tests/Framework/Integration/Bootstrappers/Seeder.cs#L74).  We add a non-analyzed string subfield to all string types.

Hope that makes sense.

**Comment by catmanjan** [comment]
Please add this

**Comment by stevejgordon** [comment]
@catmanjan We don't currently have a plan to revisit this decision so this won't be something we plan to add to the client.

**Comment by catmanjan** [comment]
@stevejgordon its very annoying in libraries when you start using data annotations only to find you’re going to have to use fluent anyway - I might as well have gone for a neat poco and all fluent

Perhaps you could document the limitations with data annotations that you have no plans addressing?

**Comment by russcam** [comment]
Hey @catmanjan, this is documented (last paragraph): https://www.elastic.co/guide/en/elasticsearch/client/net-api/7.17/attribute-mapping.html

**Comment by stevejgordon** [comment]
@catmanjan As Russ noted, this is called out in the docs, but that has discoverability challenges. In v8 we plan to remove annotation support due to the technical limitations of combining them with the new serializer we're using, along with the complexity of choice they provide.

**Comment by catmanjan** [comment]
@stevejgordon thanks, well I guess I better not invest too much more time into annotations!
