### ISSUE TITLE
Update a document using scripting and using a partial document

### ISSUE THREAD

**Issue by TheHunter** [elastic/elasticsearch-net#1565]
Hi everyone,
I would like to know if It's possible to update a document using a partial document, and at the same time using an script used to perform another action, for example:

    var respo = this.Client.Update<object>(descriptor => descriptor
                        .Id(myId)
                        .Type(myDocType)
                        .Index(myIndex)
                        .Doc(myPartialDocument)
                        .Version(myVersion)
                        .Script(string.Format("ctx._source.remove(\"{0}\")", "\\" + SessionFieldName))
                        );

Actually, I want to update a document, but at the same time I would like to delete a document property, for this reason I need to use a script.

Now, I make an update in two steps, so the first one is using the partial document, after that I remove property for the given document... as you can see make two instructions for update document is not very smart, but mainly an ugly situation is that the last update increases the document version (and I don't like it so much).

Please, I want to know if there's a way to do this job in the right way.. so avoiding (if It's possible) calling Update method twice, or maybe avoiding the last increasing version number.

Thanks.

Manuel

**Comment by KodrAus** [comment]
Is there a particular reason you need to _delete_ the field rather than just making it _empty_?

You could do this all in one step if you do the partial update through the script too... but that means you'd have to actually perform the update in the script.

I haven't tested whether you can just do simple square bracket indexing on docs in scripts so give me a sec and I'll try it out.

**Comment by KodrAus** [comment]
Ok, so a quick demo of using a script to partially update a doc and delete a field in a single transaction:

I've created an index like so:

```
{
   "testindex": {
      "mappings": {
         "doc": {
            "properties": {
               "propa": {
                  "type": "string"
               },
               "propb": {
                  "type": "string"
               },
               "propc": {
                  "type": "nested",
                  "properties": {
                     "propca": {
                        "type": "string"
                     },
                     "propcb": {
                        "type": "string"
                     }
                  }
               }
            }
         }
      }
   }
}
```

I've added a partial document that looks like this:

```
PUT testindex/doc/1
{
  "propa": "my val",
  "propb": "delete me",
  "propc": {
    "propca": "my val"
  }
}
```

Note that `propb` is the one we want to delete. I'm using an update that looks something like this:

```
POST testindex/doc/1/_update
{
  "script": "doc.each { k, v -> ctx._source[k] = v }; ctx._source.remove('propb')",
  "lang": "groovy", 
  "params": {
    "doc": {
      "propc": {
        "propcb": "my nested val"
      }
    }
  }
}
```

The `doc` param contains the partial document properties we're updating. In the script we iterate over all the values in `doc`, and update `ctx._source`, then we remove `propb`.

The script makes our doc look like this:

```
{
   "_index": "testindex",
   "_type": "doc",
   "_id": "1",
   "_version": 2,
   "found": true,
   "_source": {
      "propa": "my val",
      "propc": {
         "propcb": "my nested val"
      }
   }
}
```

*NOTE:* See how our `propc.propca` is now gone. This is because we're totally overwriting that object graph with the incomplete `propc` we supplied to the script. If you need to avoid this, you'll have to modify the script to recursively update the source if the `v` is a map itself.

**Comment by TheHunter** [comment]
Hi @KodrAus:
thanks for your suggestion, I've tried this morning and I can confirm you It's the solution in my case.

The reason for deleting a property is because It's temporally, that property serves in order to hide the document for other sessions (clients) which cannot modify and read it.
Once that document is OK for the session has generated it, that document becomes persistent definitely, so the property that i intend to delete must be deleted in order to render visible to other clients.

If you want to suggest me, be free to do it..

Thanks a lot (now I would have another question for you)..

**Comment by gmarz** [comment]
Thanks @KodrAus !
