### ISSUE TITLE
Support date in index name

### ISSUE THREAD

**Issue by jeremistadler** [elastic/elasticsearch-net#1574]
It is sometimes useful to have indexes per day so we could make it possible to map the index names with a func to resolve the index name runtime or have  a index name format that gets formated runtime.

Example: 
 new ConnectionSettings(pool)
                .MapDefaultTypeIndices(m => m.Add(typeof(LogDocument), "log-{yyyy-MM-dd}"))

**Comment by Mpdreamz** [comment]
I kinda like the idea of registering funcs along with fixed strings. 

Will let this idea bake over the weekend, :+1: for the suggestion!

**Comment by Mpdreamz** [comment]
Although I do like the idea of generalized funcs to resolve index names since Elasticsearch has support for date math in index names now in 2.0 

https://www.elastic.co/guide/en/elasticsearch/reference/current/date-math-index-names.html

I'm going to close this issue and go KISS on IndexName resolving in NEST.
