### ISSUE TITLE
Create a Linq provider for Nest

### ISSUE THREAD

**Issue by SeanFarrow** [elastic/elasticsearch-net#1581]
Hi,

It would be nice to have aa implementation of IQuaryable and IQueryProvider for Nest.

I'm happy to write this if this is of interest.

**Comment by KodrAus** [comment]
I personally am a bit skeptical of most Linq providers because while they let you expose a common query model, they bundle up a lot of complexity about the target system and can be challenging to debug when results aren't what you expect.

I'd be interested to see how the Elasticsearch API would map to the Linq though. If it's of interest to you then you should do it! That's the beauty of open source :)

**Comment by andrewrimmer** [comment]
There is already ElasticLINQ. There is no reason why you couldn't run both NEST and ElasticLINQ?

**Comment by Mpdreamz** [comment]
Indeed we have no plans of our own to abstract Elasticsearch behind `IQueryable`, we typically recommend folks to look at ElasticLINQ if they want this. 

ElasticLINQ now also support using Elasticsearch.net for the connection pooling bits as per: https://github.com/CenturyLinkCloud/ElasticLINQ/issues/76 

Hopefully in the future ElasticLINQ can also take a more direct approach by translating LINQ queries to NEST's [ISearchRequest](https://github.com/elastic/elasticsearch-net/blob/2.0/src/Nest/Search/Search/SearchRequest.cs#L12)
