### ISSUE TITLE
Querying enum values with StringEnumConverter

### ISSUE THREAD

**Issue by filpen** [elastic/elasticsearch-net#1624]
Hello,

I am using the StringEnumConverter to store enum values as their string representation in elastic search, but it seems that I can't use the enum value to filter the query results.

For example, suppose you have a Car class with an EngineType enum:

    public class Car
    {
        public EngineType EngineType { get; set; }
    }

And you want to filter the results based on the EngineType like this:

    client.Search<Car>(s => s.Query(q => q.Term(p => p.EngineType, EngineType.Diesel)));

Then if you are using a StringEnumConverter, the query won't return any result. It seems that the StringEnumConveter is not used when querying. I might be missing something, but if I am not, is it a design choice, or can the StringEnumConverter be plugged on the query-side?

**Comment by gmarz** [comment]
This should work.  It might be that it's not serializing your enums as you're expecting though (ie camelCase vs exact).  Can you share the generated query and your mapping here?

If this is indeed the case then you can add `[EnumMember(Value ="expectedSerializedValue")]` to your enum just as we do with ours: https://github.com/elastic/elasticsearch-net/blob/develop/src/Nest/Enums/FieldIndexOption.cs

**Comment by filpen** [comment]
Thanks, I think we are on the right path. 

This is the query:

	{
	  "query": {
		"term": {
		  "engineType": {
			"value": "Diesel"
		  }
		}
	  }
	}

That I got by doing the following:

	var searchDescriptor = new SearchDescriptor<Car>().Query(q => q.Term(p => p.EngineType, EngineType.Diesel));
    var json = Encoding.UTF8.GetString(client.Serializer.Serialize(searchDescriptor));

Don't know if it matters but this is the enum:

    public enum EngineType
    {
        Diesel,
        Standard
    }

I didn't specify any particular mapping for this example, I just pass instances of Car to the Index() method on the client.

I had a look at how the data is serialized on ES (there are some other properties that have been defined for testing purposes):

	{  
		"name":"Car0",
		"price":10,
		"length":0,
		"sold":true,
		"timestamp":"2010-01-01T00:00:00",
		"carType":"Type0",
		"engineType":"Diesel",
		"weight":5
	}

So I would have expected it to match the string `Diesel` against `Diesel`, but it does not. As you pointed out, it seems to be the camel case setting in the serializer, because if I set the following on the connection:

    .AddContractJsonConverters(t => t.IsEnum ? new StringEnumConverter() { CamelCaseText = true } : null);

The generated query is

	{
	  "query": {
		"term": {
		  "engineType": {
			"value": "diesel"
		  }
		}
	  }
	}

And the data in elastic search is

	{  
		"name":"Car0",
		"price":10,
		"length":0,
		"sold":true,
		"timestamp":"2010-01-01T00:00:00",
		"carType":"Type0",
		"engineType":"diesel",
		"weight":5
	}

The query now works. A question still remains, why doesn't it match `Diesel` with `Diesel`, but it matches `diesel` with `diesel`?

**Comment by michaelbudnik** [comment]
Because the string is analyzed and is stored as lowercase by default.
Term query is very low level query for which input string doesn't get analyzed and that's why it doesn't match.
If you'd try match query it would match irrelevant of the case (match query goes trough analyze phase).

Read this: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-dsl-term-query.html, especially part "Why doesn’t the term query match my document?"

and this: https://www.elastic.co/guide/en/elasticsearch/guide/current/term-vs-full-text.html

**Comment by gmarz** [comment]
Thanks @michaelbudnik, I was just typing a similar response but you beat me to it :).

@filpen Elasticsearch still keeps your original document around, exactly how it was serialized and stores it in a special field called `_source`, which is what you're looking at in your search results.

Since you didn't specify any analyzers in your mapping when you indexed your document, Elasticsearch chose the standard analyzer by default- which ends up lowercasing `Diesel`.

**Comment by filpen** [comment]
Thanks everyone, that helped a lot!
