### ISSUE TITLE
Move GetManyExtensions to IElasticClient interface

### ISSUE THREAD

**Issue by rikkit** [elastic/elasticsearch-net#1627]
Would you consider a PR to move the extension methods from GetManyExtensions to the client interface? As it stands these methods are impossible mock out in unit testing using Rhino (and other mocking frameworks that can't deal with static methods).

**Comment by Mpdreamz** [comment]
I mostly want to keep `IElasticClient` free of any of the `"convenience"` methods that do not really translate to an Elasticsearch API endpoint. I'm dead set against though, @gmarz @russcam you guys have a strong opinion on this?

**Comment by russcam** [comment]
I think it's prudent to keep any kind of convenience methods separate from the client in order to keep methods aligned with the Elasticsearch API.

That said, we do have [`ReIndex<T>`](https://github.com/elastic/elasticsearch-net/blob/82c938893b2ff4ddca03a8e977ad14a16da712ba/src/Nest/Document/Multiple/Reindex/ElasticClient-Reindex.cs) on the client directly in master (though a [ReIndex API is being proposed](https://github.com/elastic/elasticsearch/issues/15201)) :smile:

**Comment by gmarz** [comment]
Agreed for the same reasons above.

**Comment by Mpdreamz** [comment]
I meant to say I'm **not** dead set against :D We might re-evaluate come 3.0.
