### ISSUE TITLE
2.0 Tests run in both integration and unit mode (mixed mode) 

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#1659]

**Comment by gmarz** [comment]
Closed via https://github.com/elastic/elasticsearch-net/commit/e8efe897a606b95b3c950d6d0e372c59baac0e8b

tests.yml now has a `mode` option (instead of `integration_override`) that supports the following values:

`i` or `integration`: run only integration tests
`u` or `unit`: run only unit tests
`m` or `mixed`: run both unit and integration tests
