### ISSUE TITLE
Support DNXCore

### ISSUE THREAD

**Issue by atmclarke** [elastic/elasticsearch-net#1697]
It'd be very handy if the project supported DNXCore, allowing you to target more operating systems.

error NU1002: The dependency Elasticsearch.Net 1.7.1 in project <YourProjectHere> does not support framework DNXCore,Version=v5.0.

**Comment by Mpdreamz** [comment]
We have a, little out of date, dnx branch in the works which compiles but is completely untested. A big reason our first release of the 2.0 (now master) will be an alpha is not because its not well tested but more because our pcl/coreclr story is weak. 

After the first alpha is out getting PCL / coreclr (dotnet tfm) builds that are tested and fully part of our CI chain will be our main focus before releasing 2.0 GA.

**Comment by attilalaszlo** [comment]
Do you have any idea about the time of the first alpha with coreclr?
Thanks!

**Comment by blais0u** [comment]
Hi,
I've got the same error : error NU1002: The dependency Elasticsearch.Net 1.7.1 in project does not support framework DNXCore,Version=v5.0. 

I will wait for your version with DNXCore V5.0, do you have an ETA ? Because my project need to run on linux. 

Thanks a lot

**Comment by russcam** [comment]
There is a [.NET Core branch for NEST 2.x](https://github.com/elastic/elasticsearch-net/tree/vnext/dnx-support) targeting `dotnet5.1` and `net45` but not for NEST 1.x. We are focused on getting all the integration tests passing for this as a priority :smile:

**Comment by gmarz** [comment]
Closing this as the DNX branch has been merged into master.
