### ISSUE TITLE
Please update Doc at http://nest.azurewebsites.net/ for version 2.0

### ISSUE THREAD

**Issue by alkampfergit** [elastic/elasticsearch-net#1718]
Hi, 

To access ES 2.0 we should use the 2.0 version of NEST, acutally in pre-release, but it seems that there are some breaking changes, at least the code does not compile because ElasticPropertyAttribute and other attributes are missing.

Could you please update documentation at http://nest.azurewebsites.net/ explaining how to migrate code to connect to ES 2.0?

Another question, once code is ported to use NEST 2.0, it can connect to older 1.x version of ES?

Thanks.

**Comment by Mpdreamz** [comment]
Hi @alkampfergit 

The major reason why we are in pre-release is because we are still ramping up the docs which we will publish with the first GA release. 

Parts may work (just as NEST 1.x may work again Elasticsearch 2.x) but Elasticsearch itself has breaking changes so only `NEST 1.x <=> Elasticsearch 1.x` and `NEST 2.x <=> Elasticsearch 2.x` is supported.

 Our release notes details the  changes with the attributes:

https://github.com/elastic/elasticsearch-net/releases/tag/2.0.0-alpha1

Hope this helps

**Comment by alkampfergit** [comment]
Thanks. 

The fact that the version are tied to ES makes sense, because ES 2.0 has breaking changes, but this is a strong limitation because it is impossible to create a software that targets both 2.x or 1.x version.
