### ISSUE TITLE
Cannot disable norms in 2.0.0-alpha1

### ISSUE THREAD

**Issue by joelse** [elastic/elasticsearch-net#1723]
The old ElasticPropertyAttribute exposed an OmitNorms property, but with the changes done for 2.0.0-alpha1, there does not seem to be a way to disable norms for specific fields.

**Comment by gmarz** [comment]
Norms is an object now (see https://www.elastic.co/guide/en/elasticsearch/reference/2.1/norms.html and
https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Mapping/Norms/NormsMapping.cs).

We can't support objects in our attributes, only scalar values.  You can still use attributes for other fields on your type, but you'll have to use the code based mapping approach for the field that you want to configure norms on:

```csharp
.Map<MyType>(m => m
    .AutoMap() // <-- Will automatically resolve any attributes on your type, or infer the property types
    .Properties(ps => ps
        .String(s => s // <-- Override auto mapped properties and enable norms for MyField
	        .Name(p => p.MyField)
	        .Norms(new NormsMapping { Enabled = true, Loading = NormsLoading.Eager })
        )
	)	
)
```

As I write this, I've also noticed `Norms()` should have a fluent API rather than accepting a `NormsMapping` object...going to push a fix for that, so it'll change to:

```csharp
.Norms(n => n
    .Enabled()
    .Loading(NormsLoading.Eager)
)
```

Hope that makes sense.  Check out https://github.com/elastic/elasticsearch-net/blob/master/src/Tests/ClientConcepts/HighLevel/Mapping/AutoMap.doc.cs for more info on using the mapping API.

**Comment by joelse** [comment]
OK, thanks a bunch. (Feel free to close the issue if you don't want it open for the small fix you suggested.)
