### ISSUE TITLE
Can't see the raw query even after the request is made

### ISSUE THREAD

**Issue by RTodorov** [elastic/elasticsearch-net#1759]
Hi there,

Using version 2.0.0-alpha2 on dnx 1.0.0-rc1-update1

SearchResponse.ApiCall.RequestBodyInBytes is empty
SearchResponse.ApiCall.ResponseBodyInBytes is empty
SearchResponse.CallDetails.RequestBodyInBytes is empty
SearchResponse.CallDetails.RequestBodyInBytes is empty

Which one is the right one: ApiCall or CallDetails?

May it be a problem related to dnx only?

Also, where is EnableTrace() on 2.0.0?

Thank you!

**Comment by gmarz** [comment]
Have you set [DisableDirectStreaming()](https://github.com/elastic/elasticsearch-net/blob/master/src/Tests/ClientConcepts/LowLevel/Connecting.doc.cs#L102) on `ConnectionSettings`?  This replaces the old `ExposeRawResponse()` setting.

EnableTrace() was removed when the transport bits were refactored.  We plan to add it back, I'll open a new issue now.

**Comment by gmarz** [comment]
@RTodorov FYI https://github.com/elastic/elasticsearch-net/issues/1762

**Comment by RobinRieger** [comment]
@gmarz 

Is there some sort of performance or security or whatever reason for not returning by default? 
Is it safe to always have `DisableDirectStreaming` 'enabled'?

Or should I e.g. wrap the connection in `#if DEBUG` to only have it 'turn on' the 'disable direct streaming' for debug mode?

**Comment by russcam** [comment]
@RobinRieger, it's primarily for performance reasons, since the request and response are not buffered in memory in order to be made available on the response; they are written to the request stream and read from the response stream (then disposed), respectively.

Being able to inspect them is useful for development purposes and to potentially diagnose issues from the client side. Your mileage may vary in terms of whether you want them to always be on, it's an option provided nonetheless. 

Using symbols is one way you can switch enabling/disabling direct streaming. Other ways might be to define configuration that comes from a file (such as `app.config`/`web.config`) so that it can be changed in your deployment environment without requiring your application to be recompiled/redeployed.

**Comment by RobinRieger** [comment]
Cool, makes sense.

Yeah `web.config` is probably easier.... six of one, half a dozen of the other really :smile: 

Thanks :+1:

**Comment by RTodorov** [comment]
Hi @gmarz ! Thank you for the prompt reply and for opening #1762 !

Actually, even with ```DisableDirectStream(true)``` the ```RequestBodyInBytes``` is still null!

For me the request is much more important than the response for debugging purposes. Is there another way of actually seeing what's being send to the ES server?

I'm also not being able to use the provided Serializer, it always return an empty Stream..

Thanks!

**Comment by russcam** [comment]
@RTodorov, are you using `InMemoryConnection` or running against a real cluster? Can you provide a small example that reproduces what you're seeing?

**Comment by RTodorov** [comment]
Sorry @russcam , it was some sort of dnx caching issue, after a ```dnu restore``` it started being populated correctly (with ``DisableDirectStream(true)```).

Thanks again!

**Comment by russcam** [comment]
Awesome, @RTodorov :+1:
