### ISSUE TITLE
Possibility to use MapFromAttributes with an array of Types

### ISSUE THREAD

**Issue by huilaaja** [elastic/elasticsearch-net#1780]
Currently we have to declare all the types we want to map explicitly like this:

```csharp
client.Map<IndexObjBase>(id => id.Index(IndexName).MapFromAttributes());
client.Map<NewsIndexObj>(id => id.Index(IndexName).MapFromAttributes());
client.Map<PersonIndexObj>(id => id.Index(IndexName).MapFromAttributes());
```

We would like to use the Reflector to search for the types from binaries and find the types as a array and map those types. So if there would be Map()-method which would get as a parameter the list of Types or just a Type it would make the use of Reflector much easier.
Example:

```csharp
var types = new[] { typeof (IndexObjBase), typeof (PersonIndexObj), typeof (NewsIndexObj) };
foreach (var type in types) {
    client.Map(id => id.Index(IndexName).Type(type).MapFromAttributes());
}
```

**Comment by Mpdreamz** [comment]
The `Map<>` call is typically only used to update mappings, this has implications. You can not alter existing fields. The way mapping works also means that the name property on type x in index y needs to have the same mapping as type z in index y. This is why `DeleteMapping` is gone in 2.x because the implications of removing a type's mapping are hard to ratify.

A good read on this: https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping.html

When you create an index you can also specify mappings and it does allow you to pass in the typename like this:

```csharp
this.Client.CreateIndex(this.Index, c=>c
	.Mappings(mm=>mm
		.Map<Project>(Seeder.MapProject)
		.Map("typename", Func)
	)
);
```

We will add this for `Map<>()` on `ElasticClient` too though, I just wanted to point the above caveats out.

**Comment by Mpdreamz** [comment]
After looking at this further we are not going to update `client.Map<>()` to have  a non generic `client.Map()` fluent API sibbling. Another way to do this right now without having to resort to reflection is possible using the object initializer syntax:

```csharp
var types = new[] { typeof (IndexObjBase), typeof (PersonIndexObj), typeof (NewsIndexObj) };
foreach (var type in types) 
{
    var properties = new PropertyWalker(type, visitor: null).GetProperties();
    var mappingRequest = new PutMappingRequest(IndexName, type)
    {
        Properties = properties
    };
    client.Map(mappingRequest));
}
```

Thanks for raising the issue :+1:
