### ISSUE TITLE
GeoLocation implicit conversion fails when running under other cultures

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#1813]
https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/QueryDsl/Geo/GeoLocation.cs#L113

```csharp
if (latLon.Split(',')).Length > 2) throw new ArgumentException("Murica, FTW!");
```

**Comment by gmarz** [comment]
To clarify, I believe the issue is that the conversion fails with European numbers that contain commas instead of decimals (eg `40,7127,74,0059` vs `40.7127,74.0059`).

I think this is a non-issue as it's invalid GeoJSON.  A lat or lon coordinate shouldn't contain commas and we already thrown an exception if we don't parse exactly 1 comma.
