### ISSUE TITLE
Query with an empty value not serialized into the JSON

### ISSUE THREAD

**Issue by EricKeij** [elastic/elasticsearch-net#1872]
Using this code should snippet

```
var response = ElasticClient.Search<MyType>(new SearchRequest() {
         Query = new TermQuery(){Field="surname", Value ="" }
});
```

should result is this request:
```
POST /<index>/<type>/_search
{
   "query": {
      "term": {
         "surname": {
            "value": ""
          }
       }
    }
}
```
But instead the whole query section is not there in case the value is an empty string. This did work in NEST 1.7.

**Comment by gmarz** [comment]
Hey @EricKeij this is the conditionless query behavior kicking in since `Value` is empty.  See the [conditionless queries section here](http://nest.azurewebsites.net/nest/writing-queries.html).

If you switch to the fluent syntax, you can disable this simply by calling `Verbatim()`:

```csharp
ElasticClient.Search<MyType>(s => s
  .Query(q => q
    .Verbatim()
    .Term(t => t
      .Field("surname")
      .Value("")
    )
  )
);
```

However, it's not as straight forward if you're using the object syntax as in your example:

```csharp
var query = new TermQuery
{
	Field = "surname",
	Value = ""
};
var container = new QueryContainer(query);
((IQueryContainer)container).IsVerbatim = true;
ElasticClient.Search<MyType>(new SearchRequest { Query = container });
```

I think we can work to simplify the above as well.  I'll open a new issue for that.

**Comment by EricKeij** [comment]
Thanks @gmarz. Your solution works fine.
