### ISSUE TITLE
Does WordDelimiterTokenFilter removed?

### ISSUE THREAD

**Issue by GokGokalp** [elastic/elasticsearch-net#1884]
Hello.
I saw **WordDelimiterTokenFilter ** class in Breaking changes 2.2 Removed Types. But Nest 2.0.4 still have. If that class really removed (or will delete), how can we use Word Delimiter Token? Because Elastic 2.2 still have and we must to use this filter for protected words.

Thanks.

**Comment by gmarz** [comment]
[It hasn't been removed](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Analysis/TokenFilters/WordDelimiter/WordDelimiterTokenFilter.cs) and can very much still be used.

I think this is an error in the tool we used to generate the assembly diffs since it's reporting all of the token filter classes as removed.

@Mpdreamz any idea?

**Comment by GokGokalp** [comment]
Okey, thanks for your information.

**Comment by Mpdreamz** [comment]
yeah that assembly diff was very rudimentary.
