### ISSUE TITLE
ScriptDescriptor - set language of script

### ISSUE THREAD

**Issue by michaelbudnik** [elastic/elasticsearch-net#1903]
Shouldn't ScriptDescriptor inherit from ScriptDescriptorBase?

https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/CommonOptions/Scripting/ScriptBase.cs#L44

**Comment by Mpdreamz** [comment]
Yes it should :-1:

**Comment by tomasfalt** [comment]
Is it the same thing with BucketAggregate, i.e. it should inherit from BucketAggregateBase?

https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Aggregations/Bucket/BucketAggregate.cs

**Comment by Mpdreamz** [comment]
No :) cc @gmarz

**Comment by gmarz** [comment]
At first glance I agreed this was an issue, but actually it's correct the way it is.

ScriptDescriptorBase is the base class for actual script implementations (FileScriptDescriptor, InlineScriptDescriptor, and IndexedScriptDescriptor).  

ScriptDescriptor just returns the respective implementation, in which Params and Lang can be set on.  This is because setting File() and Inline() for instance on the same ScriptDescriptor would be invalid, so it made sense to separate them.

@tomasfalt BucketAggregate is a special intermediate object used for deserialization.  See https://github.com/elastic/elasticsearch-net/pull/1806 for details.  It will be removed in the next major version once #1806 is merged.
