### ISSUE TITLE
NEST DefaultIndex ConnectionSettings.DefaultIndex() is ignored

### ISSUE THREAD

**Issue by guillaume86** [elastic/elasticsearch-net#1906]
I use NEST 2.0.4 (last Nuget release) and it looks like the DefaultIndex parameter is ignored when doing a Search query.

			var node = new Uri(settings.Server); // workaround: + "/logstash-*/"
			var connectionSettings = new ConnectionSettings(node)
				.DefaultIndex("logstash-*")
				.DefaultFieldNameInferrer(p => p)
				.OnRequestCompleted(info => 
				{
					// info.Uri is /_search/ without the default index
					// my ES instance throws an error on the .kibana index (@timestamp field not mapped because I sort on @timestamp) 
				});

			var client = new ElasticClient(connectionSettings);
			var response = client.Search<ESLogEvent>(...);

I can workaround by giving the index in the base URL but it's just a ugly hack.

Side note: IApiCallDetails contains null for request and body bytes, is it expected?

**Comment by Mpdreamz** [comment]
This happens when you use the untyped `SearchRequest() {}` in place of the `...` your example:

```csharp
var response = client.Search<ESLogEvent>(new SearchRequest() {});
```

`new SearchRequest<T>()` and the fluent interface `s=>s` will both default the `/{infered_index}/{inferred_type}/_search`

See the attached test that showcases this behavior

https://github.com/elastic/elasticsearch-net/blob/3f53763f6e376ea8dab7183d54d6243c5fe0c96c/src/Tests/Reproduce/GithubIssue1906.cs

The xmldocs should mention what kind of path you are building.

**Comment by guillaume86** [comment]
Thanks!

**Comment by llRandom** [comment]
Is there any way to override this behaviour for untyped `SearchRequest` or at least specify index for `SearchRequest` object after it was created? I use wrapper class for `ElasticClient` and want to specify default index for `SearchRequest` object passed to my wrapper class so I can't pass it to `SearchRequest` constructor.
