### ISSUE TITLE
ResponseBodyInBytes is null when the response is not parseable

### ISSUE THREAD

**Issue by TioLuiso** [elastic/elasticsearch-net#1909]
In our scenario, we do not call directly ElasticSearch. We have a Web Load Balancer in the middle to balance the load between Nodes. Plus, we have an Nginx in the same server for security reasons.

Each one of those elements can return a response by themselves, and thus, the response might not be parseable by NEST. I those cases, it's vital for us to have the raw response. In NEST 1.7 we could read it. Now we cannot.

We have DisableDirectStreaming set to true, and we haven't set ThrowExceptions

**Comment by TioLuiso** [comment]
Also, if the Status Code of the response is 4XX - 5XX, it will throw the exception, so ResponseBodyInBytes will be null, also

**Comment by gmarz** [comment]
Hey @TioLuiso this has already been fixed and will be in the next release (v2.0.5).  See https://github.com/elastic/elasticsearch-net/issues/1856 for details.

**Comment by TioLuiso** [comment]
Looks really great. Any idea when 2.0.5 will be out?

**Comment by TioLuiso** [comment]
Just a question. With the default HttpConnection implementation, that uses an HttpWebRequest, when it issues the request, if it receives a 4XX - 5XX status code, it will throw a WebException. That will be caught by OnRequestCompleted handler, but a response won't be returned to the caller (other than the exception).

I have tried you HttpConnection-CoreFx, which uses HttpClient instead, will let you handle the responses and the status codes peacefully.

Do you have any plan to:
a) Update the HttpWebRequest based HttpConnection so that it will return a response.
b) Make HttpClient based HttpConnection available for regular .NET framework?

Thanks a lot

**Comment by Mpdreamz** [comment]
So by default webexceptions won't bubble out of the client mimicing the behavior of `HttpClient`. 

Using the default WebRequest based HttpConnection if we see a 500 you will get back an invalid response (response.IsValid == false) and `response.ApiDetails.Response` will have a copy of the response if you disable directstreaming (since #1856). 

However if the response is not json or empty we would still throw (something now fixed as per #1913) again something that will make it into 2.0.5 which we'll release today.
