### ISSUE TITLE
Dynamic Source/Include stop working in v2

### ISSUE THREAD

**Issue by azubanov** [elastic/elasticsearch-net#1976]
Hello!

In 1.x version this code works well:

```
public class MyType
{
   public string Field1 {get; set; }
   public Dictionary<string, int> ComplexField { get; set; }
}
```

--------------------------------------------------------

```
var subfiled = new []{"f1","f2"};
var fields = new Expression<Func<MyType, object>>[]
            {
                a => a.Field1
            }
            .Union(subfiled.Select<string, Expression<Func<MyType, object>>>(sl => a => a.ComplexField[sl]));
descriptor.Source(p => p.Include(f => f.Fields(fields.ToArray())));
```

and I got following query

> post /mydb/mytype/_search
> {
>   ...
>   "_source": {
>     "include": [
>       "field1",
>       "complexField.f1",
>       "complexField.f2"
>     ]
>   },
>   "query": {
>    ... 

In v2.x i got:

> post /mydb/mytype/_search
> {
>   ...
>   "_source": {
>     "include": [
>       "field1",
>       "complexField.f1",
>       "complexField.**f1**"
>     ]
>   },
>   "query": {
>    ...

**Comment by russcam** [comment]
Thanks for reporting @azubanov - This has been fixed in [NEST 2.3.1](https://www.nuget.org/packages/NEST/2.3.1) and is related to incorrectly caching the expression. Another [important fix for a memory leak around the caching of expressions went into 2.3.1](https://www.elastic.co/blog/nest-2-3-1-released) so I would recommend updating to 2.3.1 as soon as possible :+1:
