### ISSUE TITLE
Floating point uses float instead of double

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch-net#2003]
We need to ensure `AutoMap()` also adheres to this.

https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_mapping_changes.html#_floating_points_use_literal_float_literal_instead_of_literal_double_literal

Should this be considered breaking?

**Comment by russcam** [comment]
It's breaking because the default mapping for a number type is now `float` and no longer `double`, so going from double precision floating point to single precision floating point. This breaks the default `NumberType` for the [`NumberAttribute`](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Nest/Mapping/Types/Core/Number/NumberAttribute.cs#L26),  [`NumberProperty`](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Nest/Mapping/Types/Core/Number/NumberProperty.cs#L36) and also the [`ContentLengthField` on `AttachmentProperty`](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Nest/Mapping/Types/Specialized/Attachment/AttachmentProperty.cs#L33-L37) (which uses `NumberProperty`). 

I think we're OK with auto mapping _generally_ because if you specify a property as type `double`, [mapping inference will map it as a `double`, and likewise for `float`; if you specify `float`, it'll be mapped as a `float`](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Nest/Mapping/Visitor/PropertyWalker.cs#L99-L124).

Overriding auto mapping using `.Properties()` is also a breaking change.
