### ISSUE TITLE
Missing public Norms property on StringAttribute (among others)

### ISSUE THREAD

**Issue by stromblom** [elastic/elasticsearch-net#2038]
Elastic: 2.1.2
Nest: 2.2.0

Can't set norms on the StringAttribute. Seems to be missing a public property for it. Might be missing on other attributes as well, didn't look to closely.

**Comment by russcam** [comment]
hey @stromblom, In NEST 2.x, norms can't currently be set using attribute based mapping since the property changed from being a [boolean in NEST 1.x](https://github.com/elastic/elasticsearch-net/blob/1.x/src/Nest/Domain/Mapping/Attributes/ElasticPropertyAttribute.cs#L30) to an [`INorms` in NEST 2.x](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Nest/Mapping/Types/Core/String/StringAttribute.cs#L13) that supports being enabled and whether norms are lazy or eager loaded.

It can be set with fluent mapping though and this can be combined with attribute based mapping:

```c#
var descriptor = new CreateIndexDescriptor("myindex")
    .Mappings(ms => ms
        .Map<Company>(m => m
            // infer mappings based on POCO property types and take into
            // account attribute mappings
            .AutoMap()
            // override certain inferred or attribute based mappings
            // from Automapping
            .Properties(ps => ps
                .String(s => s
                    .Name(c => c.Name) 
                    // omit norms equivalent in Elasticsearch >= 2.0 
                    .Norms(n => n
                        .Enabled(false)
                    )
                )
            )
        )
    );
```

Hope that helps :smile:
