### ISSUE TITLE
Nest + Xamarin iOS / Android is not working

### ISSUE THREAD

**Issue by Sohojoe** [elastic/elasticsearch-net#2091]
I am trying to get ES working on a Xamarin.iOS / Android app; it's not clear if iOS / Android is intended to be supported (which it should be) or if I'm doing something wrong

if you can clarify what the intent is, then i will fill out either as a bug or feature request.

**NEST/Elasticsearch.Net version**:

**Elasticsearch version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide `DebugInformation` (if relevant)**:

**Describe the feature**:

**Comment by russcam** [comment]
Hey @Sohojoe, I take it you're using the core clr builds (`dotnet5.1` TFM)  of NEST and Elasticsearch.NET?

**Comment by Sohojoe** [comment]
@russcam - I'm trying to include v2.3.1 from NuGet which does not target iOS or Android. Is there an alternative package? (that would be awesome)

error output:

> Adding NEST...
> Adding 'NEST 2.3.1' to SynergyScout.iOS.
> Could not install package 'NEST 2.3.1'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
>

**Comment by russcam** [comment]
If I'm reading the most recent [.NET Platform Standard documentation](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md) correctly, Xamarin iOS/Android requires `netstandard1.5` .NET Platform Standard version, although looking at the [Target Framework documentation on Nuget](https://docs.nuget.org/create/targetframeworks#user-content-net-platform-standard), it requires `netstandard1.4` (`dotnet5.5`). I'm inclined to go with the version specified in the .NET Platform Standard Documentation as it is a newer document than the one on Nuget.

Right now, we have a `dotnet5.1` (`netstandard1.0`) compatible version of NEST in the 2.x releases of Nuget, which is _experimental_ (it's unit and integration tested; experimental because .NET Core is not RTM'ed). The solution is currently using DNX RC1 tooling to build targeted versions.

To release a Xamarin iOS/Android compatible version, we would need to update to target `netstandard1.5` which would also require moving over to using RC2 tooling for the build. With the recent announcement that `project.json` will be retired (which is what we use for RC1), we would need to understand what the impact will be to the solution setup.

**Comment by russcam** [comment]
A problem that we have in updating to `netstandard1.x` right now is that there is [not a compatible version of Json.Net available on nuget](https://github.com/JamesNK/Newtonsoft.Json/issues/618#issuecomment-215907853)

**Comment by russcam** [comment]
Hey @Sohojoe, [we released a .NET Core 1.0 RTM, Elasticsearch 2.x compatible client yesterday](https://www.nuget.org/packages/NEST/2.4.1) if you'd like to give it a try with iOS or Android? It's a `netstandard1.3` targeted release so should work for Xamarin iOS, which requires `netstandard1.4`.

Let me know if you have any issues.
