### ISSUE TITLE
EnableHttpCompression behavior

### ISSUE THREAD

**Issue by azubanov** [elastic/elasticsearch-net#2132]
**NEST/Elasticsearch.Net version**: 2.3.2

**Elasticsearch version**: 2.3.3

**Description of the problem including expected versus actual behavior**:
Set compression for client, requires support compression from server
It would be more convenient to check ES response encoding before decompression

**Steps to reproduce**:
 1. call EnableHttpCompression for ConnectionSettings
 2. do not set http.compression: true in ES settings
 3. try use client

**Comment by gmarz** [comment]
I don't think we can or should do anything differently here.  Compression has to be enabled on both ends for it to work, otherwise it's an error.

> It would be more convenient to check ES response encoding before decompression

It is ES that's complaining since it doesn't understand the compressed request, not the client trying to decompress a non-compressed response.  There's no way of knowing whether compression is enabled on the server ahead of time, and even if we could, it'd be better to throw an exception rather than continuing without compression.

@azubanov Does that make sense or am I misunderstanding the issue?

**Comment by Mpdreamz** [comment]
We do have a slight call to action here with regards to 5.x

2.x won't accept compressed request without `http.compression` and throw.

in 5.x since https://github.com/elastic/elasticsearch/pull/18066 it will always accept it:

see: https://github.com/elastic/elasticsearch/blob/master/docs/reference/migration/migrate_5_0/http.asciidoc

> Before 5.0, Elasticsearch accepted compressed HTTP requests only if the setting http.compressed was set to true. Elasticsearch accepts compressed requests now but will continue to send compressed responses only if http.compressed is set to true.

but we need to make sure the response is compressed or not before we send it trough a decompress.

**Comment by azubanov** [comment]
Thanks for explanation!

**Comment by gmarz** [comment]
> but we need to make sure the response is compressed or not before we send it trough a decompress.

I'll open a new issue for 5.x 👍

**Comment by gmarz** [comment]
Actually, I'm not sure there's anything to do here.  If I understand correctly, [AutomaticDecompression](https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Connection/HttpConnection.cs#L48) will decompress if the response only if it's compressed.
