### ISSUE TITLE
NEST/ElasticSearch-Net with Graph-plugin api

### ISSUE THREAD

**Issue by SujoySaha-work** [elastic/elasticsearch-net#2151]
Hi, I was curious if NEST/ElasticSearch-Net had any methods/associated documentation to call the graph-plugin api, to perform analytics.

**Comment by gmarz** [comment]
Hi @SujoySaha-work Yes, NEST has had support for the Graph since our [2.3.0](https://github.com/elastic/elasticsearch-net/releases/tag/2.3.0) and [5.0.0-alpha1](https://github.com/elastic/elasticsearch-net/releases/tag/5.0.0-alpha1) releases.

There aren't any client docs *yet*, but the only API is `.GraphExplore()` which maps closely to the actual Graph API.  So just following the actual [Graph docs](https://www.elastic.co/guide/en/x-pack/v5.0.0-alpha4-docs/xpack-graph.html) should be sufficient.
