### ISSUE TITLE
Fail to serialize TimeSpan.FromHours(25)

### ISSUE THREAD

**Issue by emmekappa** [elastic/elasticsearch-net#2170]
**NEST/Elasticsearch.Net version**: 2.4.1

**Elasticsearch version**: 2.3.1

**Description of the problem including expected versus actual behavior**:

`"unit [.] not supported for date math [-1.04d]"}}`

**Steps to reproduce**:
Querying

`.DateRange(d => d.Field(f => f.RefreshTimestamp).LessThan(DateMath.Now.Subtract(TimeSpan.FromHours(25))));
`

**Comment by gmarz** [comment]
Thanks for reporting @emmekappa, we shouldn't be converting to fractional values.  I think taking the floor here makes the most sense, i.e. `.Subtract(TimeSpan.FromHours(25))` should round to `now-1d`.

Will push a fix for the next release :+1:.

**Comment by gmarz** [comment]
Discussed this offline with @Mpdreamz and we decided that it makes a lot more sense drop the time unit  a level when fractional values are computed, which will give us exact precision, rather than rounding to the floor value.

For instance, `Now.Substract(TimeSpan.FromHours(25)` will resolve to `now-25h` (as opposed to `now-1d`).

Going to revise the above PR.

**Comment by Mpdreamz** [comment]
Submitted two new PR's for this to `2.x` and `master` should make it in the new `2.x` and `5.x` releases. 

Thanks again for raising this @emmekappa :+1:
