### ISSUE TITLE
Empty Query returns random results 

### ISSUE THREAD

**Issue by hesenp** [elastic/elasticsearch-net#2179]
Hey there, 

I assume that empty query should return nothing right? Some how using Elasticsearch.net, we are retrieving random documents if the request if empty. Here's an example: 

`           var connection_pool = new SingleNodeConnectionPool(new Uri(server));
            ConnectionSettings settings = new ConnectionSettings(connection_pool).DefaultIndex(default_index);
            ElasticClient client = new ElasticClient(settings);

            QueryContainer qc = new MatchQuery
            {
                Field = "text",
                Query = "" 
            }; 

            var result = client.Search<dynamic>(q => q.Query(m => qc).Type("page"));

            Console.WriteLine(result.Hits.Count()); `

This would get us quite a few randomly selected documents. 

However if we use JSON RESTful request, we would get no hits. How did this happen? Thanks a lot.

**Comment by gmarz** [comment]
This is the conditionless query feature kicking in, see [Conditionless Queries](https://www.elastic.co/guide/en/elasticsearch/client/net-api/1.x/writing-queries.html#conditionless-queries) for details.

Since the value is empty, NEST rewrites and nullifies the query which results `/_search` with no body, which is effectively a match all.

You can disable this by setting `IsVerbatime = true`

```csharp
QueryContainer qc = new MatchQuery
{
    IsVerbatime = true,
    Field = "text",
    Query = "" 
}; 
```
