### ISSUE TITLE
GetAlias ignores the alias parameter in descriptor

### ISSUE THREAD

**Issue by plmaheu** [elastic/elasticsearch-net#2194]
**NEST/Elasticsearch.Net version**:
2.4.2

**Elasticsearch version**:
2.3.5

**Description of the problem including expected versus actual behavior**:

This overload is ignoring the alias name parameter.
`IGetAliasesResponse GetAlias(Func<GetAliasDescriptor, IGetAliasRequest> selector = null)`
Was working before in 1.7.2.

I'm getting /_alias in url while it should be /_alias/somealiasname

This overload, `IGetAliasesResponse GetAlias(IGetAliasRequest request)`, works as expected.

**Steps to reproduce**:
 1. `elasticClient.GetAlias(x => x.Alias("testalias"));`
 2. Look at request url (I sniffed requests using Fiddler). Will be /_alias instead of /_alias/testalias

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by russcam** [comment]
Thanks for reporting @plmaheu! The following will do what you need, using `.Name(Names name)`

```c#
client.GetAlias(a => a
    .Name("alias-name")
);
```

which yields

```
GET http://localhost:9200/_alias/alias-name
```

It looks like `.Alias(string alias)` is an artifact of the 1.x refactoring and should have been removed. I'll mark it as deprecated and map it to the same route value as `Name` so that it still works in 2.x. I'll remove it in `master`, tracking 5.x

**Comment by russcam** [comment]
[I've just merged a PR into 2.x to address this](https://github.com/elastic/elasticsearch-net/pull/2203); it will go into the next release.

Thanks again fr reporting @plmaheu :+1:
