### ISSUE TITLE
Unifying PutMappingDescriptor and TypeMappingDescriptor

### ISSUE THREAD

**Issue by foresightyj** [elastic/elasticsearch-net#2196]
This problem has been asked in stackoverflow by someone before but received no attention:
http://stackoverflow.com/questions/38088851/sharing-index-mapping-configuration-in-nest-2-3-3

The syntax for both `Func<TypeMappingDescriptor<EsType>, ITypeMapping>` and `Func<PutMappingDescriptor<EsType>, IPutMappingRequest>` is **identical**. Right now I have to maintain two copies of the same mapping twice, one for CreateIndex and one for update index mapping. It is hard to keep them in sync.

Is this a design flaw introduced when migration NEST from es1.x to es2.x?

**Comment by gmarz** [comment]
The common interface is now `ITypeMapping` (which `IPutMappingRequest` implements).  It's not a design flaw per se, but I do see the inconvenience.

The reasoning behind separating them was because `IPutMappingRequest` also contains request specific information (e.g. URL paths), which feels wrong to be passing around to other APIs that are only concerned about the mapping properties.

You could easily create an extension method for `Map<>` that takes an `ITypeMapping` and maps it to back `IPutMappingRequest`.  Or perhaps we can add a `.TypeMapping(ITypeMapping mapping)` method to `PutMappingDescriptor` that does this for you.

Thoughts @Mpdreamz @russcam ?

**Comment by foresightyj** [comment]
Thanks a lot for your response. 

I still have problems following your suggestions. Probably I am not experienced enough with C# lambdas.  Right now I have:

```
        public override Func<TypeMappingDescriptor<EsTopicPost>, ITypeMapping> GetMappingDescriptor()
        {
            Func<TypeMappingDescriptor<EsTopicPost>, ITypeMapping> descriptor = map => map
                .AutoMap()
                .AllField(a => a.Enabled(false))
                .Properties(ps => ps
                    .String(s => s
                        .Name(e => e.Title)
                        .Analyzer(ElasticsearchAnalyzers.MmsegAnalyzer)
                        .Similarity(SimilarityOption.BM25)
                        .Fields(fs => fs
                            .String(fss => fss
                                .Name("Pinyin")
                                .Analyzer(ElasticsearchAnalyzers.HuohuoSearchPinyinAnalyzer)
                            )
                        )
                    )
                );
            return descriptor;
        }

```
Above code is used in:

```
        private static Func<CreateIndexDescriptor, CreateIndexDescriptor> GetCreateIndexDescriptor(string indexName)
        {
            var topicPost = new EsTopicPostService();
            var company = new EsCompanyService();
            var user = new EsUserService();

            return i => i
                    .Index(indexName)
                    .Settings(s => s
                        .NumberOfShards(3)
                        .NumberOfReplicas(0)
                        .RefreshInterval(10)
                        .Analysis(ElasticsearchAnalyzers.GetAnalysisDescriptor())
                        )
                    .Mappings(ms => ms
                        .Map(topicPost.GetMappingDescriptor()) // <===== Used HERE!!!
                        .Map(company.GetMappingDescriptor())
                        .Map(user.GetMappingDescriptor())
                        )
                    .Similarity(s => s.BM25(HuoHuoSimilarity, b => b.B(0.75).K1(0.3).DiscountOverlaps()));
        }

```

On the other hand I have a update mapping method which I could call to update mapping on an existing index:

```

        public void UpdateMapping()
        {
            Func<PutMappingDescriptor<EsTopicPost>, IPutMappingRequest> desc =
            m => m
                .AutoMap()
                .AllField(a => a.Enabled(false)).Properties(ps => ps
                    .String(s => s
                        .Name(e => e.Title)
                        .Analyzer(ElasticsearchAnalyzers.MmsegAnalyzer)
                        .Similarity(SimilarityOption.BM25)
                        .Fields(fs => fs
                            .String(fss => fss
                                .Name("Pinyin")
                                .Analyzer(ElasticsearchAnalyzers.HuohuoSearchPinyinAnalyzer)
                            )
                        )
                    )
                );

            esClient.Map(desc);
        }

```

What I wanted to have is to write my `UpdateMapping` simply as:

```
       public void UpdateMapping()
        {
            esClient.Map(GetMappingDescriptor());
        }
```

So my problem is not about converting `IPutMappingRequest` to `ITypeMapping` but converting the entire `Func<TypeMappingDescriptor<EsTopicPost>, ITypeMapping>` to `Func<PutMappingDescriptor<EsTopicPost>, IPutMappingRequest>`. 

Read Nest's source code, I found their signatures as:
```
	public partial class PutMappingDescriptor<T> where T : class
```
and
```
	public class TypeMappingDescriptor<T> : DescriptorBase<TypeMappingDescriptor<T>, ITypeMapping>, ITypeMapping where T : class
```

They have no inheritance relationships, so I have no way of converting some `Func` involving `PutMappingDescriptor` into another `Func` involving `TypeMappingDescriptor`.

**Comment by gmarz** [comment]
`TypeMappingDescriptor` implements `ITypeMapping` and so does `PutMappingDescriptor` and `PutMappingRequest` via `IPutMappingRequset`.  So they all share `ITypeMapping` as a common interface.  You won't see that looking at `PutMappingRequest.cs` because it's a partial class, and the portion that implements `IPutMappingRequest` is in the [generated file](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/_Generated/_Descriptors.generated.cs#L2833).

You don't need to return a `Func<>` from your method.  You can return `PutMappingDescriptor<>` directly, or `PutMappingRequest<>`, or anything that implements `ITypeMapping`.

For instance

```csharp
client.Map<Project>(m => GetMapping());

client.CreateIndex("projects", c => c
    .Mappings(ms => ms
        .Map<Project>(m => GetMapping())
    )
);
```
```csharp
public PutMappingDescriptor<Project> GetMapping()
{
    return new PutMappingDescriptor<Project>()
        .AutoMap()
        // ...snip...
}
```

Hope that makes sense.

**Comment by foresightyj** [comment]
With your help, I was able to get away without using `TypeMappingDescriptor`. `PutMappingDescriptor<EsTopicPost>` can be used in both places. Thanks a lot :+1:
