### ISSUE TITLE
Allow per document index operations on BulkAll

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#2220]
The [BulkAll helper introduced in `master`](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Document/Multiple/BulkAll/ElasticClient-BulkAll.cs) is really helpful for setting up bulk indexing. It could be even more helpful if per document modifications were allowed to each bulk index operation. For example, it's not possible to bulk index a collection of child documents with the helper and set the `_parent` for each index operation.

**Comment by budzynski** [comment]
I think it is related to this issue - there is no option to specify [op_type (OpType)](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#operation-type) for bulk indexing.

**Comment by Mpdreamz** [comment]
@budzynski there is no `op_type` in the `_bulk` api but you can call different actions e.g `index/create/update/delete`. 

Thanks for voicing your need here though since I've opened up #2402 which will allow you to control in a more general fashion then this ticket requested how the buffer of `IList<T>` is translated into a `BulkRequest` using the `BulkAll` helper 👍
