### ISSUE TITLE
Clearing a cache created in terms lookup by key

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch-net#2229]
NEST version: 1.7.2
ES version: 1.7.2

In using terms lookup, I'm having it create a named cache for the terms.  Periodically, when I detect that the source of those terms has changed, I want to invalidate that cache.  I've discovered the endpoint and syntax for a raw request, for example:
POST posts,comments/_cache/clear?filter_keys=members_123
if the members list in the 123 document changes.

I cannot see how I can generate that request using NEST.   What I see in
`public IIndicesResponse ClearCache(List<string> indices, ClearCacheOptions options)`
is close, but it doesn't support `filter_keys` nor a way to pass those keys in.  Is there a way to accomplish this that I'm missing?

Thanks,
Tom Doman

**Comment by russcam** [comment]
Hey @tdoman, [`filter_keys` is exposed on `ClearCache`](https://github.com/elastic/elasticsearch-net/blob/1.x/src/Nest/DSL/_Descriptors.generated.cs#L3186-L3191) however the parameter type is a `bool`, which is a bug :disappointed:. This part of the client is generated from the [rest api specs](https://github.com/elastic/elasticsearch/blob/1.7/rest-api-spec/api/indices.clear_cache.json#L35-L37) of Elasticsearch, [so I have submitted a PR to address this.](https://github.com/elastic/elasticsearch/pull/20292)

You can work around that issue for the moment whilst still using the strong request type, by appending to the query string yourself. To do this, you just need to cast the `ClearCacheRequest` to `IRequest<ClearCacheRequestParameters>` in order to get access to the explicitly implemented interface properties. Here's an example

```c#
var filterKeys = new[]
{
    "members_123"
};

var clearCacheRequest = new ClearCacheRequest
{
    Indices = new IndexNameMarker[] { "posts", "comments" }
};

// cast to IRequest<ClearCacheRequestParameters> 
// to get access to explicit interface implementation
((IRequest<ClearCacheRequestParameters>)clearCacheRequest).RequestParameters.AddQueryString("filter_keys", string.Join(",", filterKeys));

client.ClearCache(clearCacheRequest);
```

which yields

```
POST http://localhost:9200/posts%2Ccomments/_cache/clear?filter_keys=members_123
```

**Comment by tdoman** [comment]
@russcam awesome!  Thanks, I tried that out this morning and it works great!  I really appreciate the support, it was very timely as we're about to push and I really needed to be able to cache larger lists that may exist in our system.  Thanks again!

**Comment by russcam** [comment]
No worries @tdoman :+1: 

If you're using many `not_analyzed` string fields, also consider enabling [`doc_values`](https://www.elastic.co/guide/en/elasticsearch/guide/1.x/doc-values.html); whilst they are marginally slower than loading field data into JVM heap and take up slightly more disk space, they take advantage of a columnar data structure that can be managed by the filesystem cache thereby reducing memory pressure on the JVM heap. To enable, you'd need to reindex your data as additional work is done at index time. I thought I'd mention this in case it may help. `doc_values`  are enabled by default for `not_analyzed` string fields in Elasticsearch 2.0 onwards.

I'll keep this issue open until the `filter_keys` change is applied.

**Comment by tdoman** [comment]
Thanks for the tips Russ.  We're a strange breed among ES users these days, we actually use ES for full-text search!  ;)  Even so, we do have some cases where `doc_values` would be good and I'm glad the default is changing.  We're looking to upgrade to 2.x hopefully within the next few months.

**Comment by russcam** [comment]
This is now in release 1.9.1. Thanks again for raising, @tdoman :+1:
