### ISSUE TITLE
5.0.0 -> Default inferrer not using default settings

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2341]
I have the following on my `ConnectionSettings` `settings..DefaultTypeNameInferrer(p => p.Name.ToLowerUnderscoredWords()).DefaultFieldNameInferrer(p => p.ToLowerUnderscoredWords()) `

I'm then using the client created from these connection settings and doing `string organizationIdFieldName = infer.Field(nameof(IOwnedByOrganization.OrganizationId));`

To me this, should automatically use the `DefaultFieldNameInferrer` to resolve this field (as there is no type info).

**Comment by niemyjski** [comment]
Looks like this just calls a static method called `ParseFieldName` and doesn't even look at the connection settings :(.

**Comment by russcam** [comment]
[strings are always passed verbatim](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/field-inference.html#camel-casing) so using `nameof(IOwnedByOrganization.OrganizationId)` will pass `"OrganizationId"`

**Comment by niemyjski** [comment]
Yes, it will Pass "OrganizationId)" as the field, but I was expecting it to convert the passed in value to the actual inferred name (does this make sense)?

**Comment by russcam** [comment]
We assume when passed strings that the consumer knows best, so they are passed through verbatim. Part of this is to be consistent with how strings for field names are treated when

1. coming from NEST attributes or serializer specific attributes e.g. `JsonPropertyAttribute`
2. specified as strings in search request
3. specified as strings in mappings

**Comment by niemyjski** [comment]
I figured when I called the client.Inferrer.Field("string") would be passed to `.DefaultFieldNameInferrer(p => p.ToLowerUnderscoredWords())`

**Comment by niemyjski** [comment]
To add, this inferrer takes expressions as well as reflection data and resolves the proper name, but when I pass in a string it does something completely different. I don't think this is consistent or intuitive.

**Comment by russcam** [comment]
The way strings are handled for field names is consistent within NEST i.e. we treat them verbatim as documented 😄 

The intention with inference is to take "some thing" and resolve a string from it that represents the field name in Elasticsearch. The "some thing" supported are

1. A member access lambda expression
2. A `PropertyInfo`
3. A string

For the first two, obtaining the reflected property name for the expression would result in a pascal-cased string, if you're following C# guidelines. Since idiomatic json favours camel-casing (or snake casing), it makes sense for NEST to have support for transforming this pascal-cased string to whatever you're preferred convention is, defaulting to camel-casing.

With a string however, we don't run this through the same transformation as we assume the string you've provided is the field name as it should be passed to Elasticsearch. I think it would be counter-intuitive and more confusing to apply the transform to strings coming from attributes, string `Field`s in search requests, etc., and special case out those strings that you don't want the transform applied to.

**Comment by niemyjski** [comment]
I get why you are doing it, it just doesn't make sense from an end users perspective. When I pass something to an inferrer I'd expect it to be transformed the same way regardless of how I call it (consistency). If I had just the raw string and I knew it was the actual name, why on earth would I (a consumer ever call the inferrer :))?
