### ISSUE TITLE
Range GreaterThan and LessTHan only accepts a Double

### ISSUE THREAD

**Issue by DavidRooney** [elastic/elasticsearch-net#2377]
I have the following range query in elasticsearch:

{
	"from": 0,
	"size": 200,
	"query": {
		"bool": {
			"filter": {
				"bool": {
					"must": {
						"bool": {
							"must": [
								{
									"range": {
										"network_start_ip": {
											"from": null,
											"to": "5.8.92.0",
											"include_lower": true,
											"include_upper": true
										}
									}
								},
								{
									"range": {
										"network_last_ip": {
											"from": "5.8.95.255",
											"to": null,
											"include_lower": true,
											"include_upper": true
										}
									}
								}
							]
						}
					}
				}
			}
		}
	}
}

Note that the range token above uses a string. the NEST API only allows for a Double to be used Like so: ".Range(r => r.Field("network_start_ip").GreaterThanOrEquals(**Need to put a string here but only allows doubles**))".

Thanks!

**Comment by russcam** [comment]
Hi @DavidRooney, because the Elasticsearch `range` query allows different options for numbers, dates or strings, it is split out into three different methods (with overloads and async variants) in 2.x+:

1. [`.Range()`](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/numeric-range-query-usage.html) for numeric ranges
2. [`.DateRange()`](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/date-range-query-usage.html) for date ranges
3. [`.TermRange()`](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/term-range-query-usage.html) for term (string) ranges

See https://github.com/elastic/elasticsearch-net/issues/2307 for more details
