### ISSUE TITLE
No ISearchResponse.Highlights in 5.0.0-rc1?

### ISSUE THREAD

**Issue by rm2k** [elastic/elasticsearch-net#2392]
**NEST/Elasticsearch.Net version**: 5.0.0-rc1

**Elasticsearch version**: 5.0.1

**Description of the problem including expected versus actual behavior**:
I can't seem to have the `Highlights` field in `ISearchResponse` in v5.0.0-rc1. am I missing something or Highlights not implemented in v5.0.0-rc1?

**Comment by russcam** [comment]
@rm2k `.Highlights` is removed in 5.x onwards because it is abstraction that can throw exceptions in certain scenarios due to its implementation e.g. searching across different types in the same index with the same ids, or same types in different indices with same ids.

See #2168 for more discussion.

Since it was a convenience property, you can still get all of the highlights information with 

```c#
foreach (var highlightsInEachHit in response.Hits.Select(d=>d.Highlights))
{
	foreach (var highlightField in highlightsInEachHit)
	{
		if (highlightField.Key == "field_name")
		{
			foreach (var highlight in highlightField.Value.Highlights)
			{
				// do something with highlight
			}
		}
   	}
}
```

**Comment by rm2k** [comment]
thanks @russcam
