### ISSUE TITLE
InferMappingFor.Ignore for inherited property

### ISSUE THREAD

**Issue by Grastveit** [elastic/elasticsearch-net#2556]
**NEST/Elasticsearch.Net version**: 5.0.1 (and also in 2.4)

**Elasticsearch version**: 5.1.2

**Description of the problem including expected versus actual behavior**:

I'd like to ignore an inherited property without using attributes. `InferMappingFor` is the other option then, however I'm only able to ignore declared properties. 

**Steps to reproduce**:

The snippet below makes a mapping with a single inheritedProp-field, instead of no fields, as I expected.

```c#
void Main()
{
	new ElasticClient(new ConnectionSettings(new Uri("http://localhost:9200"))
		.InferMappingFor<Foo>(i => i
			.Ignore(f => f.InheritedProp)
			.Ignore(f => f.DeclaredProp))
	).CreateIndex("fooindex", c => c.Settings(s => s.NumberOfShards(1).NumberOfReplicas(0))
		.Mappings(ms => ms.Map<Foo>(m => m.AutoMap()))
	);
}

public class FooBase
{
	public int InheritedProp { get; set; }
}

public class Foo : FooBase
{
	public int DeclaredProp { get; set; }
}
```

I also unsuccessfully tried `InferMappingFor<FooBase>`.

**Comment by Mpdreamz** [comment]
I agree this is unexpected:

At the time `AutoMap()` reflects the properties we have no `ConnectionSettings` to check against so this is by design. 

I've added https://github.com/elastic/elasticsearch-net/pull/2560 though so that when `Properties` are written we double check against `ConnectionSettings` 

Thanks for opening this one @Grastveit 👍

**Comment by Mpdreamz** [comment]
Jotting this down for future googlers: programmatically ignoring/renaming base properties for serialization on connection settings works fine
