### ISSUE TITLE
Time parser acuracy

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2569]
I noticed that we have it set to 30 days in a month. This isn't that accurate (https://www.quora.com/What-is-the-average-number-of-days-in-a-month) Should we be updating this?

**Comment by russcam** [comment]
Are you referring to 

```c#
Time time = "1M";
```

evaluating to milliseconds of 30 days? What would be the benefit of choosing another value e.g. `30.4375`?

**Comment by niemyjski** [comment]
Yes, We'll it could change the range or accuracy of returned data over time? I'm trying to remember what all takes a time unit and what accepts a double..... But I could see it if you were expecting better accuracy like maybe parsing a based in time unit and applying it to the returned date time aggregation (which we do in the foundatio project). Food for thought, I just logged this as I know in our code base we are using specific fractions of time to represent days in month and this wasn't...

**Comment by gmarz** [comment]
We purposely do not calculate milliseconds when [months or years](https://github.com/elastic/elasticsearch-net/blob/master/src/Tests/CommonOptions/TimeUnit/TimeUnits.doc.cs#L83) are passed because accuracy is impossible.

An approximate fraction like `30.4375` is just as wrong (or approximate) as `30`, so I don't think we should do anything here.
