### ISSUE TITLE
5.2.0 Integration Tests Failing

### ISSUE THREAD

**Issue by natebunton** [elastic/elasticsearch-net#2633]
**NEST/Elasticsearch.Net version**:
5.2.0
**Elasticsearch version**:
5.2.1
**Description of the problem including expected versus actual behavior**:
The integration tests are failing with the following errors...I expect the integration tests to succeed.  When I run fiddler, I see a lot of web request succeeding and failing.

**Steps to reproduce**:
 1.  Create a branch from tag 5.2.0
 2.  In the root of the repo, run build.bat Integrate 5.2.1

**Provide `ConnectionSettings` (if relevant)**:
N/A
**Provide `DebugInformation` (if relevant)**:

Running build failed.
Error:
System.Exception: Calling packages/build/xunit.runner.console/tools/xunit.console.exe resulted in unexpected exitCode 1
   at FSI_0005.Tooling.Tooling.execProcess@76.Invoke(String message)
   at FSI_0005.Testing.Tests.testDesktopClr()
   at FSI_0005.Testing.Tests.RunIntegrationTests()
   at FSI_0005.Targets.clo@51-18.Invoke(Unit arg00@)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 492

Here is the full build console output:  
[build console output.txt](https://github.com/elastic/elasticsearch-net/files/794791/build.console.output.txt)

**Describe the feature**:

**Comment by gmarz** [comment]
Ah, yea the `BulkAllApiTests` are flaky.  We've hit this before locally and in [CI](http://elastic-dotnet.westeurope.cloudapp.azure.com/project.html?projectId=Nest5x) (which is failing at the moment for a different reason, which looks to be due to another flaky test).  If you run the tests again does it pass or does it fail consistently?

Rest assured, we always make sure the integration tests are all green before releasing, and did so against 5.2.1 -- so I'm fairly confident it's a bug in the test itself.

**Comment by natebunton** [comment]
It is consistently failing.  Any ideas or work arounds to get the integration tests to pass?

**Comment by gmarz** [comment]
Sorry, I just looked at the output again and it's also failing the x-pack tests because you don't have a valid license file:

```
FATAL called: Server has license plugin installed,  but the license was not found!
```

This is done by obtaining a license and setting `%ES_LICENSE_FILE%` to its path.  This needs to be beyond the basic license though in order to run all of the x-pack tests (Graph, Watcher, etc...).

We have a way to filter the test runner to run only specific tests (or groups of tests) via the build script, but not filter *out* tests (@Mpdreamz correct me if I'm wrong).  We should definitely add this so you can easily run all tests except x-pack.

Curious though, do you have some requirement for all the integration tests to pass on your end?

**Comment by russcam** [comment]
> We have a way to filter the test runner to run only specific tests (or groups of tests) via the build script, but not filter out tests

Correct - the test filtering is inclusive

**Comment by natebunton** [comment]
I saw the error for not having the license installed.  We have a license for x-pack I just haven't configured the path on the machine.  Even though the x-pack tests were failing due to no license, I was expecting a test summary with a count of success, failed, ignored, but I don't see that.  I only see that the build failed.

@russcam can you provide me an example on how to run integration tests with inclusive filtering.

@gmarz I don't have any special requirements that ll integration tests must past, I was just trying to be thorough in my testing to ensure that all functionality is working as expected after my changes.

**Comment by gmarz** [comment]
@natebunton I just opened https://github.com/elastic/elasticsearch-net/pull/2635

Which will make cluster filtering much easier.  After it's merged, you'll be able to do

```build integrate 5.2.1 -xpack```

To run all the integration tests except xpack.

**Comment by natebunton** [comment]
Awesome, thanks.  I'll give it a try.
