### ISSUE TITLE
TermsIncludeExcludeJsonConverter Problem

### ISSUE THREAD

**Issue by giocaputo** [elastic/elasticsearch-net#2655]
**NEST/Elasticsearch.Net version**:5.2.0

**Elasticsearch version**:5.2.2

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Create a term aggregation with null or empty value as exclude parameter 
aggregations.Terms("aggregationName", t => t
						 .Field(f => f.Name)
						 .Size(10)
						 .Include("value")
						 .Exclude("")

aggregations.Terms("aggregationName", t => t
						 .Field(f => f.Name)
						 .Size(10)
						 .Include("value")
						 .Exclude(null)
 

It create an wrong json syntax error.
writer.WriteEndObject(); is executed **only if** not termsIncludeExclude.Pattern.IsNullOrEmpty

Also
The property partition and num_partitions not exists for exclude property

{"error":{"root_cause":[{"type":"parsing_exception","reason":"[terms] failed to parse field [exclude]","line":1,"col":2048}],"type":"parsing_exception","reason":"[terms] failed to parse field [exclude]","line":1,"col":2048,"caused_by":{"type":"illegal_argument_exception","reason":"Unrecognized field [partition]"}},"status":400}

**Comment by russcam** [comment]
@giocaputo, an empty string or null is not a valid pattern for Include or Exclude; what are you trying to do by setting it to one of these?

[`Partition` and `NumberOfPartitions` are only valid on `Include`](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values_with_partitions); The XML documentation on the properties indicate this. The properties exist on `Exlude` because both include and exclude share a common type in 5.x unfortunately and changing this in 5.x would be a binary breaking change. There are plans to split these out into separate types in 6.x to ensure these properties do not exist for exclude.

**Comment by giocaputo** [comment]
I have a private method that is passed to exclude function, sometimes it return null string to ignore include/exclude in aggregation.
Use this to maintain a single statement for declaration of aggregation. With previous version (2.x) it worked.
