### ISSUE TITLE
NewtonSoft.Json 10.0.1 support

### ISSUE THREAD

**Issue by h0gh** [elastic/elasticsearch-net#2687]
Please update the dependency on NewtonSoft.Json to support the new 10.0.1 release.

**Comment by draganjovanovic1** [comment]
Any reason why Newtonsoft.Json reference is bound to <10 in NEST.nuspec? Can we expect NuGet 2.5.*  which allows Newtonsoft.Json to be updated? 

build/NEST.nuspec
```xml
<dependencies>
    <group targetFramework=".NETFramework4.5">
        ...
        <dependency id="Newtonsoft.Json" version="[9,10)" />
    </group>
    <group targetFramework=".NETFramework4.6">
        ...
        <dependency id="Newtonsoft.Json" version="[9,10)" />
    </group>
    <group targetFramework=".NETStandard1.3">
        ...
        <dependency id="Newtonsoft.Json" version="[9,10)" />
    </group>
</dependencies>
```

The issue we have is that FSharp List can't be deserialized when using F# 4.1 and Newtonsoft.Json 9.0.1 (https://github.com/JamesNK/Newtonsoft.Json/issues/1180). Newtonsoft.Json 10.* solves the issue but we can't update to it because of NEST limitation.

**Comment by Mpdreamz** [comment]
Hi @draganjovanovic1 

The reason its bound to that is because we only test with 9. The last major jump from 8 to 9 broke some things for us so we tend to fixate it to a major version.

We will release an update within the next couple days to `2.x` and `5.x` releases of the client which bumps to Json.NET to 10. 

The releases for those from last week are still on `9.x` to give folks fixated on those a chance to upgrade too.

Every major release of Json.NET we get a ticket asking to upgrade, or if we are too fast with bumping asking to downgrade :smile:

**Comment by draganjovanovic1** [comment]
Hi @Mpdreamz 

Thanks for the update. Can't wait for the new version...

**Comment by draganjovanovic1** [comment]
Hi @Mpdreamz, any news on schedule for a new version? Thanks.

**Comment by hughbe** [comment]
I've found this requirement on 9.0.1 means that I get errors loading any assemblies referencing 10.0.1

**Comment by Mpdreamz** [comment]
Ok we just did new releases for `2.x` and `5.x` bumping to `Json.NET` `10.x` 

# 2.x
Nuget: https://www.nuget.org/packages/NEST/2.5.4
Release Notes: https://github.com/elastic/elasticsearch-net/releases/tag/2.5.4

# 5.x

Nuget: https://www.nuget.org/packages/NEST/5.3.1
Release notes: https://github.com/elastic/elasticsearch-net/releases/tag/5.3.1

Sorry this took a little longer then expected!

**Comment by zidad** [comment]
Can we still get a 1.x client version with JSON.Net 10.x? We're running into dependency conflicts with other packages, but upgrading Elastic has proven a lot of (too much) effort...

**Comment by russcam** [comment]
@zidad there are no plans to release another 1.x client as it, along with Elasticsearch 1.x, are no longer supported.
