### ISSUE TITLE
Bug when failing over using rancher and Nest

### ISSUE THREAD

**Issue by imranazad** [elastic/elasticsearch-net#2701]
I am using a docker container that is a search api making use of Nest 2.0.2, the container talks to another container which is a load balancer for two elastic search instances. What I've noticed is that when one of the the elastic search instances goes down, the search API is unable to call elastic via the load balancer, despite the fact that I can curl on the box to the load balancer which returns a response from the single elastic instance that is still up. The elasticsearch instances are not a cluster they are just separate instances.

Any ideas what's going on?

**Comment by russcam** [comment]
Hi @imranazad , 

GitHub is reserved for bug reports and feature requests. The best place to ask a general question like this is at the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch; it'll get more eyeballs on the forum. If this turns out to be a bug in NEST then we can open this issue back up.

Thanks!
