### ISSUE TITLE
NEST converts first letter of field name to lowercase

### ISSUE THREAD

**Issue by LlewellynJones** [elastic/elasticsearch-net#2727]
This is an issue with the latest version of Nest.

In a query NEST converts the first letter of the field name to lowercase. See the code below. I've include the mapping in Elasticsearch. NEST translates "SceneText" into "sceneText" even though the field name is actually SceneText in ElasticSearch. This means no results come back from the query.

                    var searchResponse = _EsClientDAL.Current.Search<DTO.RiAll>(s => s
                        .Query(q => q
                        .Match(m => m
                            .Field(f => f.SceneText)
                            .Query(queryString))
                    ));

Valid NEST response built from a successful low level call on POST: /ri/RiAll/_search
# Audit trail of this API call:
 - [1] HealthyResponse: Node: http://localhost:9200/ Took: 00:00:00.1293725
# Request:
{"query":{"match":{"sceneText":{"query":"hide"}}}}
# Response:
{"took":2,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}

"mappings": {
    "RiAll": {
      "properties": {
        "SceneKey": {
          "type": "text",
          "analyzer": "standard"
        },
        "BookKey": {
          "type": "text",
          "analyzer": "standard"
        },
        "Title": {
          "type": "text",
          "analyzer": "standard"
        },
        "Author": {
          "type": "text",
          "analyzer": "standard"
        },
        "SceneText": {
          "type": "text",
          "analyzer": "english"
        }
      }
    },

**Comment by russcam** [comment]
Hi @LlewellynJones, this is not an issue but expected behaviour. By default, NEST camel cases the property names on the POCO when serializing the POCO into a JSON document to send to Elasticsearch. You can change this behaviour by using the `.DefaultFieldNameInferrer(Func<string,string>)` method on `ConnectionSettings`. [Take a look at the documentation for more details.](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/field-inference.html#camel-casing)

**Comment by LlewellynJones** [comment]
Thanks. The only problem I'm having is the following error:
The name 'WithConnectionSettings' does not exist in the current context

**Comment by russcam** [comment]
Take a look at the Getting Started section on [Connecting](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/nest-getting-started.html#_connecting_2). 

`WithConnectionSettings()` is a method used in the docs that creates a `ConnectionSettings` and passes it to the method. The documentation is generated from tests so that it stays in line with changes in the code; you can always see the original file from which it was generated by clicking the `EDIT` button in the docs to take you to Github where the doc file is, then finding the URI of the original C# file in the `IMPORTANT NOTE` section at the top of the doc file e.g. https://github.com/elastic/elasticsearch-net/tree/5.x/src/Tests/ClientConcepts/HighLevel/Inference/FieldInference.doc.cs for field inference.

For your case, the following will work

```c#
var settings = new ConnectionSettings()
    .DefaultFieldNameInferrer(s => s);

var client = new ElasticClient(settings);
```

**Comment by LlewellynJones** [comment]
Thanks. That works. This usage of the function seems more intuitive than
using the WithConnectionSettings method (which I couldn't find).


Cheers,
James
my own book <http://myownbook.org>
