### ISSUE TITLE
Scroll issue

### ISSUE THREAD

**Issue by slorena** [elastic/elasticsearch-net#2760]
Hello,

I'm using Elasticsearch 5.1.1 and Nest 5.0 and I'm trying to search items by query and after that to delete these items.

This is the code:
var searchDescriptor = new SearchDescriptor()
.Index(indexName)
.Size(itemsPerShard)
.StoredFields((Field)"Id")
.Scroll("1m")
.Sort(ss => ss.Ascending(SortSpecialField.DocumentIndexOrder))
.Query(qd => qd
.QueryString(snd => snd
.Query(deleteByQuery)
.DefaultOperator(Operator.And))
);
var scanResults = client.Search(s => searchDescriptor);
var results = client.Scroll<object>("1m", scanResults.ScrollId);

When itemsPerShard > 10.000, I receive this error:
{Invalid NEST response built from a unsuccessful low level call on POST: /index/_search?scroll=1m}.
And in elasticsearch log file:
Batch size is too large, size must be less than or equal to: [10000] but was [10001]. Scroll batch sizes cost as much memory as result windows so they are controlled by the [index.max_result_window] index level setting.

This code works in with Nest 1.X.

Thank you!

**Comment by KodrAus** [comment]
So there's an [`index.max_result_window` parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#dynamic-index-settings) in Elasticsearch that defaults to `10000`. This isn't actually part of NEST directly.

If you need to increase the max size you can use [`UpdateIndexSettings`](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Indices/IndexSettings/UpdateIndexSettings/ElasticClient-UpdateIndexSettings.cs#L15) on your client and pass in a new value for `index.max_result_window`, but that limit exists as a sanity check because Elasticsearch keeps heap memory proportional to that number available when scrolling. If you set it too high your Elasticsearch node might run out of memory!
