### ISSUE TITLE
NU1603 Warnings

### ISSUE THREAD

**Issue by jwu-au** [elastic/elasticsearch-net#2831]
**NEST/Elasticsearch.Net version**:
5.4/5.5

**Description of the problem including expected versus actual behavior**:
```
warning NU1603: NEST 5.4.0 depends on Newtonsoft.Json (>= 10.0.0 && < 11.0.0) but Newtonsoft.Json 10.0.0 was not found. An approximate best match of Newtonsoft.Json 10.0.1 was resolved.
```
Shouldn't have these warnings when build in latest vs2017

**Steps to reproduce**:
 1. Updated VS2017 to Version 15.3.0
 2. Build the project having reference on NEST 5.4/5.5

**Comment by benhilty** [comment]
Same problem with versions 2.4.6/2.4.6.

> error NU1603: NEST 2.4.6 depends on Newtonsoft.Json (>= 9.0.0 && < 10.0.0) but Newtonsoft.Json 9.0.0 was not found. An approximate best match of Newtonsoft.Json 9.0.1 was resolved.

**Comment by anurse** [comment]
I also hit this. Specifically when trying to use NEST in a .NET Core project.

This is caused by NEST's `nuspec` file setting a lower-bound on Newtonsoft.Json of `10.0.0` but that version does not exist, the best match would be `10.0.1`. Releasing new packages with updated lower-bounds to that would fix this issue. The reason these warnings are reported is that it negatively impacts package restore performance because the NuGet has to check the package feed for version `10.0.0` each time a restore is done (though there is some caching) before it falls back to `10.0.1`.

See https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings#nu1603 for more.

I'd have sent a PR but I haven't had a chance to dig into the build scripts enough or set things up locally to test. I believe this line is the culprit:

https://github.com/elastic/elasticsearch-net/blob/2efdb55a6d40e71ca60b42ed9a23ddc7e6125863/build/scripts/Releasing.fsx#L37

**Comment by kwilliamssbs** [comment]
I've taken @anurse 's suggestion and raised a PR - it's not a blocker for us, but it does mean that all dependencies that reference Newtonsoft.Json have warning triangles in VS, which makes it hard to find the actual warnings.

**Comment by xplatsolutions** [comment]
Any update when the next release fixing this will be available?

**Comment by russcam** [comment]
@xplatsolutions Hoping to get a new 5.x release out within the next week. We've been focused on getting the 6.x version of the client shipped as a priority.
