### ISSUE TITLE
Term unable to find keyword records

### ISSUE THREAD

**Issue by btecu** [elastic/elasticsearch-net#2858]
**NEST/Elasticsearch.Net version**:
5.5.0

**Elasticsearch version**:
5.52

**Description of the problem including expected versus actual behavior and steps to reproduce**:
I have a class `Activity`:
```
	[ElasticsearchType(Name = "activity")]
	public class Activity {
		...
		[Keyword]
		public Guid AppId { get; set; }
		[Date(Name = "@timestamp")]
		public DateTime Timestamp { get; set; }
	}
```

Then in my ElasticClient I use a `ConnectionSettings` where I map the indices:
`settings.MapDefaultTypeIndices(m => m.Add(typeof(Activity), "activities-*"));`

The issue is `term` is not able to find any records matching the `AppId` (which is a keyword):
`.Search<Activity>(s => s.Query(q => q.Term(t => t.AppId, someId)))`

However, the following works:
`.Search<Activity>(s => s.Query(q => q.Term(t => t.Field("appId.keyword").Value(someId))))`

The first one used to work until I updated to 5.x.

**Comment by russcam** [comment]
@btecu It looks to me like you may have indexed an activity document _before_ explicitly applying a mapping for activity that used your attributes. 

By default, [Elasticsearch will infer a `text` datatype field for a JSON string property, with a `keyword` datatype _sub-field_ (i.e. indexed as a `multi-field`)](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/multi-fields.html#_default_mapping_for_string_properties), which is why the second search query works.

So, in order to apply the mapping specified by the attributes, you'll need to delete the index and add the mapping at the same time as creating the index, _before_ you index any documents into it (as by default, Elasticsearch will create an index if you attempt to index a document into an index that doesn't exist). The following would do it

```c#
var client = new ElasticClient(); // pass your connection settings here, if needed

if (client.IndexExists("activity-1").Exists)
    client.DeleteIndex("activity-1");

var createIndexResponse = client.CreateIndex("activity-1", c => c
    .Mappings(m => m
        .Map<Activity>(d => d
            .AutoMap()
        )
    )
);
```

If you have documents in the old index that you want to keep, then you could create a new index with the mapping applied, then reindex those documents into it.

I hope this helps. I'm going to close this as it doesn't look like a bug or a feature.
