### ISSUE TITLE
MatchPhrase on Nest 5.5.0 is generating deprecated match:{ type: "phrase" }

### ISSUE THREAD

**Issue by edmarsj** [elastic/elasticsearch-net#2920]
**NEST/Elasticsearch.Net version**: 5.5.0

**Elasticsearch version**: 5.5.0

**Description of the problem including expected versus actual behavior**:
After our migration to Elasticsearch 5.5.0, our QA team caught some queries on Kibana dev tools with the message 

`#! Deprecation: Deprecated field [type] used, replaced by [match_phrase and match_phrase_prefix query]`.

After spending some time debugging our code, we discovered that our calls to .MatchPrase() are the reason for this messages. As we are using pretty much what the documentation states, we believe that this is an issue with Nest itself. 

**Steps to reproduce**:
 1. The issue can be easily reproduced with the following console application:

```

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Nest;

namespace TestMatchPrase
{
    class Program
    {
        public class Person
        {
            public int Id { get; set; }
            public string FirstName { get; set; }
            public string LastName { get; set; }
        }

        static void Main(string[] args)
        {            
            var settings = new ConnectionSettings(new Uri("<our V5 cluster url>"))
                .DisableDirectStreaming()
                .DefaultIndex("people");

            var client = new ElasticClient(settings);

            var searchResponse = client.Search<Person>(s => s
                .From(0)
                .Size(10)
                .Query(q => q
                    .MatchPhrase(m => m
                        .Field(f => f.FirstName)
                        .Query("Martijn")
                    )
                )
            );

            Console.WriteLine(Encoding.UTF8.GetString(searchResponse.ApiCall.RequestBodyInBytes));
            Console.ReadLine();
        }
    }
}

```
The output on my tests was: 

```{
    "from": 0,
    "size": 10,
    "query": {
        "match": {
            "firstName": {
                "type": "phrase",
                "query": "Martijn"
            }
        }
    }
}
```

I assume that the above sample should be generating something like:

```
{
    "from": 0,
    "size": 10,
    "query": {
        "match_phrase": {
            "firstName": "Martijn"
        }
    }
}
```
Is that correct, or we are missing something?

**Comment by russcam** [comment]
Hey @edmarsj, NEST's [current implementation of the Match family queries uses the `"type"` field to discriminate the type of match query](https://github.com/elastic/elasticsearch-net/blob/bef4b9df32aba4c959eb7a4dc0214d4ca738c959/src/Nest/QueryDsl/FullText/Match/MatchQuery.cs#L61). 

The deprecation warning is _just a warning_ so will continue to work as expected for Elasticsearch 5.x. Due to the inherent nature of the implementation and our design philosophy of not breaking binary compatibility within a major version, the implementation will be changed in 6.x to remove the deprecation warnings but won't be changed in 5.x. No action will be required when updating to 6.x.

I hope that answers your question.
