### ISSUE TITLE
Elasticsearch .NET only allow me to upload 80 times

### ISSUE THREAD

**Issue by betimer** [elastic/elasticsearch-net#3036]
**NEST/Elasticsearch.Net version**: 5.5

**Elasticsearch version**: 5.1.1

**Description of the problem including expected versus actual behavior**:

I have the following code which bulk index the documents to Elasticsearch.

            var node = new System.Uri(restEndPoint);
			var settings = new ConnectionSettings(node);
			var lowlevelClient = new ElasticLowLevelClient(settings);

			var index = indexStart + indexSuffix;

			var items = new List<object>(list.Count() * 2);
			foreach (var conn in list)
			{
                items.Add(new { index = new { _index = index, _type = "doc", _id = getId(conn) } });
				items.Add(conn);
			}

			try
			{
				var indexResponse = lowlevelClient.Bulk<Stream>(items);
				if (indexResponse.HttpStatusCode != 200)
				{
					throw new Exception(indexResponse.DebugInformation);
				}

				return indexResponse.HttpStatusCode;
			}
			catch (Exception ex)
			{
				ExceptionManager.LogException(ex, "Cannot publish to ES");
				return null;
			}

It runs fine, can publish documents to Elasticsearch, but it only can run 80 times, after 80 times, it will always get exception: 

    # OriginalException: System.Net.WebException: The operation has timed out
       at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
       at System.Net.HttpWebRequest.GetRequestStream()
       at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 148

Also create a ticket on stackoverflow: https://stackoverflow.com/questions/48256570/elasticsearch-net-only-allow-me-to-upload-80-times

**Comment by Mpdreamz** [comment]
```csharp.
var indexResponse = lowlevelClient.Bulk<Stream>(items);
```

Will return the response stream to you, in this case you are responsible for closing (disposing) it. Since you are not actually using `response.Body` you might have better luck using the built in `VoidResponse`. This is a special type that will not read the response body and automatically closes the response. 

That said the bulk API will return `200` even if individual items fail, so you really should be inspecting the `response.Body` by parsing it. Is there a reason why you are not using the high level client NEST?

Closing this but feel free to reopen if my diagnosis was incorrect.

**Comment by betimer** [comment]
@Mpdreamz After I make use of `VoidResponse `instead of Stream, the issue has been fixed. Thanks very very much.
