### ISSUE TITLE
Cant search for multiple types using a common interface

### ISSUE THREAD

**Issue by tanorion** [elastic/elasticsearch-net#3063]
**NEST/Elasticsearch.Net version**: 6.1.0-ci20180124T063911

**Elasticsearch version**: 6.1.2

**Description of the problem including expected versus actual behavior**:  Im having problem using an interface as T in search and searching multiple indexes with multiple types. I get a json deserialization error. Could not create an instance of type ISearchObject. Type is an interface or abstract class and cannot be instantiated. We are migrating from version 2.3.2 so it worked in that version atleast.

**Steps to reproduce**:
 var result = client.Search`<ISearchObject>`(body => body.Index("type_*")
.Type(Types.Type(typeof(SearchObject1), typeof(SearchObject2), typeof(SearchObject3)))

where SearchObject 1,2 and 3 all implement ISerachObject.

**Comment by Mpdreamz** [comment]
`_type` is going to go away completely. While you could use it today in `6.x` to distinguish between types from different indices in the long run (7.x and beyond) this discriminating column will no longer be available. 

I've tried to argue internally to keep `_type` around internally for this purpose but was unsuccessful in convincing my peers :) This means that for `NEST 6.x` we chose to completely rip out support for covariant search results OOTB.

You will now need to index a discriminating marker as part of `_source` which is the official guideline to moving from multiple types to a single type index.

One way to do so is to set `TypeNameHandling.All` on your `Nest.JsonNetSerializer` `SourceSerializer` to burn in this marker as part of `_source`. Previously this was not possible because setting that would also cause our request and response mappings to include `$type` which would obviously not be accepted by Elatsticsearch. With `6.x` we clearly separated our types vs user provided type serialization.

See also: https://www.elastic.co/guide/en/elasticsearch/client/net-api/master/covariant-search-results.html

**Comment by flons** [comment]
@Mpdreamz : could you maybe post a complete example on how to use the TypeNameHanling.All flag in NEST - we're trying to upgrade from ES v5.6 to v6 with no luck. Injecting the flag and burning the $type into the source seems to break the OOTB types e.g. geo points, which now also have the $type burned into them - and ES don't like it. Any help would be much appreciated. Thanks

**Comment by russcam** [comment]
Which version of NEST are you using @flons?

**Comment by flons** [comment]
hi @russcam - we're using the latest NEST 6.1.0
