### ISSUE TITLE
NEST 6.0: Aggregation response breaking changes between beta1 and rc1

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch-net#3064]
Since our earliest usage of NEST, we've always just walked through the aggregations one `SingleBucketAggregate` at a time.  As such, there's lots of runtime casting going on but the various buckets, etc. are reasonable enough to parse through for the data models we want to project to middle tier code.  As I've looked at the helpers, it really hasn't looked like those would help though, if I'm being brutally honest, the documentation on aggregation usage in NEST is pretty sparse.  I preface what follows with all this because it's entirely possible there's a better way to do this that I haven't discovered.  However, being that our general approach worked in beta1, I'd like to continue in this vein for now but I'm open to other suggestions as well.

With the rc1 of the NEST 6.0 library, I see now that some of my previous sub-aggregations that come in `KeyedBucket`s have Keys and Values instead of Aggregations.  In my previous approach, there was an `.Aggregations()` method  on `KeyedBucket` that allowed me to walk through each key\value pair and, based on the key name, write code to handle the sub-aggregation value, say, a couple like a `ValueAggregate` and perhaps another `SingleBucketAggregate`.  As I debug through the responses now, I see that I could essentially follow the same approach if I could get access to the `BackingDictionary`.  To be honest, I don't understand why the Keys and Values have been separated since, as I said, I use the key names to determine how to process the Values.  They're pairs, don't they belong together?  I'd consider `.Zip()`ping them back up as tuples but seeing what's there now makes me feel like I'm not understanding something important here.

By the way, I had started to make changes since I noticed that some things that used to be in `Aggregations` (ie. in some cases, there's a field by that name but it's `null`, in others the `.Aggregations()` method is gone) showed up in `Values` now and those seemed straightforward enough until I arrived at one of my aggregations `KeyedBucket` that had more than 1 sub-aggregation `Values` in it so I thought I'd ask for some clarification.

**Comment by tdoman** [comment]
For the time being, I've actually taken the `.Zip()` strategy but like I was saying, it definitely seems like I'm misunderstanding something about what changed and why:
```
var keyItem = bucketItem as KeyedBucket<object>;
                                        var subAggPairs = keyItem.Keys.Zip(keyItem.Values, (key, value) => (Key: key, Value: value));
```

**Comment by russcam** [comment]
You can still enumerate the `KeyValuePair<string, IAggregate>`  of `KeyedBucket<T>`, it's just rather than the dictionary being exposed as the `Aggregations` property of the bucket, the bucket itself is a dictionary of `<string, IAggregate>` e.g.

```c#
    var response = client.Search<Question>(s => s
        .Query(q => +q
            .Term(f => f.Type, "question")
        )
        .Size(0)
    	  	.Aggregations(a => a
    			.Terms("top_tags", m => m
    		  		.Field(f => f.Tags)
    		  		.Size(5)
    		  		.ShardSize(20)
    				.Aggregations(sa => sa
    					.Stats("score_stats", st => st
    						.Field(f => f.Score)
    					)
    				)
    			)
    	  	)
    	);
    	
    var termBuckets = response.Aggregations.Terms("top_tags").Buckets;
    
    foreach(var bucket in termBuckets)
    {
        foreach(var aggregate in bucket)
        {
            aggregate.Dump();   // .Dump() is a LinqPad method
        }      
    }
```

which looks something like the following in LinqPad:

<table id="t1"><tr><td class="typeheader" colspan="2">KeyValuePair&lt;String,IAggregate&gt;</td></tr><tr id="sum2"><td colspan="2" class="summary">[score_stats, Nest.StatsAggregate]</td></tr><tr><th class="member" title="System.String">Key</th><td>score_stats</td></tr><tr><th class="member" title="Nest.IAggregate">Value</th><td><table id="t3"><tr><td class="typeheader" colspan="2">StatsAggregate</td></tr><tr id="sum4"><td colspan="2" class="summary">Nest.StatsAggregate</td></tr><tr><th class="member" title="System.Double?">Average</th><td>1.73389505221873</td></tr><tr><th class="member" title="System.Int64">Count</th><td>1457906</td></tr><tr><th class="member" title="System.Double?">Max</th><td>7668</td></tr><tr><th class="member" title="IReadOnlyDictionary&lt;System.String,System.Object&gt;">Meta</th><td><i>null</i></td></tr><tr><th class="member" title="System.Double?">Min</th><td>-81</td></tr><tr><th class="member" title="System.Double?">Sum</th><td>2527856</td></tr></table></td></tr></table></div><div class="spacer"><table id="t5"><tr><td class="typeheader" colspan="2">KeyValuePair&lt;String,IAggregate&gt;</td></tr><tr id="sum6"><td colspan="2" class="summary">[score_stats, Nest.StatsAggregate]</td></tr><tr><th class="member" title="System.String">Key</th><td>score_stats</td></tr><tr><th class="member" title="Nest.IAggregate">Value</th><td><table id="t7"><tr><td class="typeheader" colspan="2">StatsAggregate</td></tr><tr id="sum8"><td colspan="2" class="summary">Nest.StatsAggregate</td></tr><tr><th class="member" title="System.Double?">Average</th><td>1.86282977152099</td></tr><tr><th class="member" title="System.Int64">Count</th><td>1303971</td></tr><tr><th class="member" title="System.Double?">Max</th><td>18957</td></tr><tr><th class="member" title="IReadOnlyDictionary&lt;System.String,System.Object&gt;">Meta</th><td><i>null</i></td></tr><tr><th class="member" title="System.Double?">Min</th><td>-78</td></tr><tr><th class="member" title="System.Double?">Sum</th><td>2429076</td></tr></table></td></tr></table></div><div class="spacer"><table id="t9"><tr><td class="typeheader" colspan="2">KeyValuePair&lt;String,IAggregate&gt;</td></tr><tr id="sum10"><td colspan="2" class="summary">[score_stats, Nest.StatsAggregate]</td></tr><tr><th class="member" title="System.String">Key</th><td>score_stats</td></tr><tr><th class="member" title="Nest.IAggregate">Value</th><td><table id="t11"><tr><td class="typeheader" colspan="2">StatsAggregate</td></tr><tr id="sum12"><td colspan="2" class="summary">Nest.StatsAggregate</td></tr><tr><th class="member" title="System.Double?">Average</th><td>2.03999968135502</td></tr><tr><th class="member" title="System.Int64">Count</th><td>1129784</td></tr><tr><th class="member" title="System.Double?">Max</th><td>4513</td></tr><tr><th class="member" title="IReadOnlyDictionary&lt;System.String,System.Object&gt;">Meta</th><td><i>null</i></td></tr><tr><th class="member" title="System.Double?">Min</th><td>-125</td></tr><tr><th class="member" title="System.Double?">Sum</th><td>2304759</td></tr></table></td></tr></table></div><div class="spacer"><table id="t13"><tr><td class="typeheader" colspan="2">KeyValuePair&lt;String,IAggregate&gt;</td></tr><tr id="sum14"><td colspan="2" class="summary">[score_stats, Nest.StatsAggregate]</td></tr><tr><th class="member" title="System.String">Key</th><td>score_stats</td></tr><tr><th class="member" title="Nest.IAggregate">Value</th><td><table id="t15"><tr><td class="typeheader" colspan="2">StatsAggregate</td></tr><tr id="sum16"><td colspan="2" class="summary">Nest.StatsAggregate</td></tr><tr><th class="member" title="System.Double?">Average</th><td>0.983671644765366</td></tr><tr><th class="member" title="System.Int64">Count</th><td>1114013</td></tr><tr><th class="member" title="System.Double?">Max</th><td>3241</td></tr><tr><th class="member" title="IReadOnlyDictionary&lt;System.String,System.Object&gt;">Meta</th><td><i>null</i></td></tr><tr><th class="member" title="System.Double?">Min</th><td>-147</td></tr><tr><th class="member" title="System.Double?">Sum</th><td>1095823</td></tr></table></td></tr></table></div><div class="spacer"><table id="t17"><tr><td class="typeheader" colspan="2">KeyValuePair&lt;String,IAggregate&gt;</td></tr><tr id="sum18"><td colspan="2" class="summary">[score_stats, Nest.StatsAggregate]</td></tr><tr><th class="member" title="System.String">Key</th><td>score_stats</td></tr><tr><th class="member" title="Nest.IAggregate">Value</th><td><table id="t19"><tr><td class="typeheader" colspan="2">StatsAggregate</td></tr><tr id="sum20"><td colspan="2" class="summary">Nest.StatsAggregate</td></tr><tr><th class="member" title="System.Double?">Average</th><td>1.78443044615312</td></tr><tr><th class="member" title="System.Int64">Count</th><td>1021712</td></tr><tr><th class="member" title="System.Double?">Max</th><td>4595</td></tr><tr><th class="member" title="IReadOnlyDictionary&lt;System.String,System.Object&gt;">Meta</th><td><i>null</i></td></tr><tr><th class="member" title="System.Double?">Min</th><td>-50</td></tr><tr><th class="member" title="System.Double?">Sum</th><td>1823174</td></tr></table></td></tr></table>
thank you for your feedback through these prerelease @tdoman, it's been very much appreciated and helpful 👍

**Comment by tdoman** [comment]
@russcam And there it is, the piece I was missing!  My brain had ignored in the debugger that the `SingleBucketAggregation` and `KeyedBucket` items were enumerable.  Based on that, I'm not sure why the `SingleBucketAggregation` still has an `Aggregations` field that's always `null` but I applied this info (got rid of my hacky zips) everywhere and it looks great.  And no, thank **you** very much for your support!  It's exciting for us to get all those breaking changes done in one large jump from 1.7.5 all the way to 6.1.1!

On aggregations, I need to revisit the helpers.  From early on, what I created was an abstraction where each aggregation implementation knows how to make itself into an aggregation descriptor (and optionally apply itself as a filter) and how to handle it's associated response into our models.  From there, as we search, we dynamically choose Terms, Sum, Histograms, and Sub-aggregations and they all know how to take care of themselves.  Unfortunately, this approach leaves us making what I call "hopeful" casts and verifying structure through unit tests and debugging.  Being able to use the helpers and get strong typing for compile time insurance would be ideal.  I may be able to use the helpers if I make my key names include a clue about what type of aggregation that key represents.  Then I can work through them and call, say, `.Terms(my_key)` as you showed in your example.  For now, understanding what I was missing will keep our current approach viable.  Thanks again!
