### ISSUE TITLE
ElasticClient.GetIndex(...).Indices.Keys does not contain a list of the index names

### ISSUE THREAD

**Issue by mjdaly** [elastic/elasticsearch-net#3119]
**NEST/Elasticsearch.Net version**:
6.0.1

**Elasticsearch version**:
6

**Description of the problem including expected versus actual behavior**:
`ElasticClient.GetIndex(...).Indices.Keys` does not contain a list of the index names. 

Example index name causing issue:
`tests-a57cfaff-2ff0-4ff4-9c6a-144df548b90d-2018-03-02t17:48:38`

Response stored in `ElasticClient.GetIndex(...).Indices.Keys`:
`48:38`

Note: Index names are available via ElasticClient.GetIndex(`...).Indices.Select(i => i.Value.Settings["index.provided_name"].ToString()).ToList()`.

**Steps to reproduce**:
 1. Call `ElasticClient.GetIndex(...).Indices.Keys`

**Comment by russcam** [comment]
The first colon is determined to be a cluster separator such that everything before the first colon is the cluster name, and everything after is the index name. You should see that the `tests-a57cfaff-2ff0-4ff4-9c6a-144df548b90d-2018-03-02t17` value is assigned to the `IndexName.Cluster` property.

The cluster name as part of the index name is used within [cross cluster search](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cross-cluster-search.html#_using_cross_cluster_search). To avoid confusion, I'd strongly recommend using an index name that doesn't contain colons.

I'm going to close this as it's expected behaviour to support cross cluster search.
