### ISSUE TITLE
Parsing docs when query on several indexes

### ISSUE THREAD

**Issue by PetterBronsta** [elastic/elasticsearch-net#3122]
**NEST/Elasticsearch.Net version**:  6.1

**Description of the problem including expected versus actual behavior**:

Hi, in earlier versions we could do a search across multiple indexes, and with type `T` set to `object` like so:

`
.Search<object>(s => s
    .Type(Types.Type(typeof(aType), typeof(bType), typeof(cType)))
    .Index("SharedAlias")
)
`

This still works just fine, but in previous versions when checking the document's types, it would be parsed correctly as type = `aType`, `bType` or `cType`, and we could take advantage of `if(document is aType)` or `document as aType.` 

In NEST 6.1 type is set as `object`. I know we are moving away from type field, but would it be possible to do this? I am using the option where you set defaultmappingfor type:

`settings.DefaultMappingFor(typeof(aType), t => t.IndexName("SomeIndexName"))`

I see this as more of a question about what's possible than a bug / feature. cheers!

**Comment by russcam** [comment]
Hey @PetterBronsta, Covariant search results are no longer a feature in the client; the client no longer automatically deserializes the type type as specified in the `_type` field. This is in part because of the removal of types.

It's still possible to support returning disparate types however with one of the following options:

- [Hooking up `Nest.JsonNetSerializer`](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html) and using something like Json.NET's [TypeNameHandling](https://www.newtonsoft.com/json/help/html/SerializeTypeNameHandling.htm)

- Returning [`ILazyDocument`](https://github.com/elastic/elasticsearch-net/blob/5617675f61c368be30c93e710c9440adeec1289d/src/Nest/CommonAbstractions/LazyDocument/LazyDocument.cs) instead of `object`, and lazily converting to the correct type with `.As<T>()` or `.As(Type)`, perhaps using the document metadata to understand which type to convert to.

Hope that helps!
