### ISSUE TITLE
Unable to add language for Phrase suggester collate query

### ISSUE THREAD

**Issue by mehtaishita8** [elastic/elasticsearch-net#3227]
**NEST/Elasticsearch.Net version**: 5.4.1

**Elasticsearch version**:5.4.1

**Issue** :
Unable to add language for collate query .I am trying to write a NEST object which uses collate.
Basically i want to have json something like this:
```
"collate": {
      "query": {
        "lang" : "my_own_language",
        "inline" : "my_scripting_code"
      },
```
But, when i try to build a NEST object for above query and try adding .Lang("my_own_language"), it throws error.
Is there any way to add language type for collate queries?

```
.Collate(c => c
              .Query(q => q
                      .Inline("my_scripting_code")
                      .Lang("my_own_language")
                          )
              .Prune()
)

```

**Comment by russcam** [comment]
What language are you looking to support, @mehtaishita8 ?

**Comment by mehtaishita8** [comment]
I am trying to write a native plugin which would use custom language and the plugin would be called through "inline" script. Something similar to this (https://www.elastic.co/guide/en/elasticsearch/reference/5.5/modules-scripting-engine.html).
But i am not able to do this in collate query.

**Comment by stevejgordon** [comment]
I'm cleaning up old issues and I'm not sure this is even supported in Elasticsearch. The Collate parameter on the phrase suggester takes a moustache [Search Template](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html) to use. 

@mehtaishita8 Did you eventually work around this? If you can provide any more info to help me triage this, then please do. Otherwise, I'll look to close this old issue out in a week or so.

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Please let us know if this issue is still a relevant priority for your usage?
