### ISSUE TITLE
Expose IndexNotFoundException on CatIndices()

### ISSUE THREAD

**Issue by dejonghee** [elastic/elasticsearch-net#3303]
**NEST/Elasticsearch.Net version**: v6.0

**Elasticsearch version**: v6.2.4 running on Elastic Cloud - Amazon (EU Ireland)

**Description of the problem including expected versus actual behavior**:
When executing a ElasticClient.CatIndices() request on an a cluster which contains no indices (or no indices matching the specified pattern) AND that is protected with X-Pack security (for example an index hosted in Elastic Cloud) the NEST API throws an exception:

> Nest.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IReadOnlyCollection`1[Nest.CatIndicesRecord]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.

This is due to the fact that Elastic Cloud will return an IndexNotFoundException and not an Array:

> Elasticsearch clusters with X-Pack security enabled apply the /_all wildcard, and all other wildcards, to the indices that the current user has privileges for, not the set of all indices on the cluster. While creating or retrieving aliases by providing wildcard expressions for alias names, if there are no existing authorized aliases that match the wildcard expression provided an IndexNotFoundException is returned.

(Source: https://www.elastic.co/guide/en/elastic-stack-overview/current/security-limitations.html#_changes_in_index_wildcard_behavior)

I wouldn't it be better to expose the IndexNotFoundException?
No it's impossible to detect why the method throws the exception. Is it because there is a network issue? Or is it because there are no indices found? Would be cool if we could do something like this:

> try
> {
> _client.CatIndices();
> }
> catch(IndexNotFoundException e){
> // Index does not exist
> }
> catch(Exception e){
> // Possible network issue.
> }

**Comment by Mpdreamz** [comment]
Thank you for this report @dejonghee the underlying issue was definitely a bug. Opened https://github.com/elastic/elasticsearch-net/pull/3345 to address this.

When a server-side error occurs it returns an object where an array is expected in any of the Cat related API's. 

After that PR's is merged if you enable `.ThrowExceptions()` an `ElasticsearchClientException` should bubble out. We do not map server exceptions to client exceptions 1-1.

https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/thrown-exceptions.html
