### ISSUE TITLE
Support of .NET Framework 4.5 for nuget package

### ISSUE THREAD

**Issue by dark-spoon** [elastic/elasticsearch-net#3334]
**NEST/Elasticsearch.Net version**: 6.2.0

**Elasticsearch version**:

**Description of the problem including expected versus actual behavior**:
Nuget package does not include libs for target framework .NETFramework4.5. 
Declarations in the dependencies section of the nuspec file of both of the package (NEST and Elasticsearch.Net) refers to the target framework NETFramework4.5.

Is the support for .NET Framework 4.5 is officially dropped or just the files are missing ?

**Comment by Mpdreamz** [comment]
Hi we did indeed drop it 4.5 support with .netstandard1.3 and net46 as the new baseline.

We did this so that we can start introducing a netcoreapp2.1 TFM and focus on bringing all the performance work in there over to the client.

Can you tell us a bit more about your environment ?

.NET 4.5 is from 2012 and only 4.5.2 from 2014 is supported by Microsoft still. At some point though we need to make the hard decision to drop 4.5.2 so we can focus more on current and more recent .NET versions. Just as us dropping .NET 3.5 a couple a years back was not an easy decision. 

Can you describe what prevents you from moving to e.g .net 4.6?

**Comment by dark-spoon** [comment]
Hi,

Thanks for your reply.

We don't have any strong constraint that prevents us to move on more recent version of .NET Framework.

So we will move forward :)

**Comment by Mpdreamz** [comment]
Awesome! glad to hear @dark-spoon 😄
