### ISSUE TITLE
Inconsistent filter generation in search request json

### ISSUE THREAD

**Issue by tjkolev** [elastic/elasticsearch-net#3338]
**NEST/Elasticsearch.Net version**:
6.1.0

**Elasticsearch version**:
6.3

**Description of the problem including expected versus actual behavior**:
I am experiencing an inconsistent filter-s generation. Using [the + unary operator](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/bool-queries.html#unary-plus-operator) does not always put the queries under the query's bool **filter** node in the json search request as I would expect. Sometimes the first filter goes under the query's bool **must** node as another bool. And sometimes all filters go there.

**Steps to reproduce**:
I am attaching a sample NUnit code with four tests, along with their corresponding output.

If this is as designed:
1. Where in the documentation with an explanation for it?
2. What is the reasoning behind this behavior?

If this is a bug:
1. When can I expect it to be fixed?

Either way:
1. What is a suggested work around to get all + queries under the filter node in all cases? (Using object initialization syntax.)

Thank you.
tjk :)

[NestFilterTests.zip](https://github.com/elastic/elasticsearch-net/files/2211302/NestFilterTests.zip)

**Comment by Mpdreamz** [comment]
Hey @tjkolev this is all down to the order at which the operators are applied

```csharp
var fullTextQuery = new BoolQuery()
{
	Should = new QueryContainer [] { new MatchAllQuery() },
};
sr.Query &= fullTextQuery;
```

Means `AND` the query under `sr.Query` which is empty with `fullTextQuery resulting in:

```json
{
  "bool": {
    "should": [{ "match_all": {} }]
  }
}
```

because `sr.Query` is empty its not wrapped in a bool must clause. Extending it further with our first `+`'d filter query:

```csharp
var fullTextQuery = new BoolQuery()
{
	Should = new QueryContainer [] { new MatchAllQuery() },
};
sr.Query &= fullTextQuery;
sr.Query &= +new TermQuery { Field = "accid", Value = 101 };
```

will AND `sr.Query` (empty) AND `fullTextQuery` and `accid filter`

```csharp

{
  "bool":{
    "must":[
      { "bool":{"should":[{"match_all":{}}]}},
      {"bool":{"filter":[{"term":{"accid":{"value":101}}}]}}]
  }
}
```

Adding another `&= +query`

```csharp
var fullTextQuery = new BoolQuery()
{
	Should = new QueryContainer [] { new MatchAllQuery() },
};
sr.Query &= fullTextQuery;
sr.Query &= +new TermQuery { Field = "accid", Value = 101 };
sr.Query &= +new TermQuery { Field = "size", Value = 50 };
```

will see a query with only must clauses on the left and decide the query is allowed to live as filter on that query rather that wrapping once again.

```json
{
  "bool":{
    "must":[
      {"bool":{"should":[{"match_all":{}}]}},
      {"bool":{"filter":[{"term":{"accid":{"value":101}}}]}}
    ],
    "filter":[{"term":{"size":{"value":50}}}]
  }
}
```


Any more `&= +query` will see a bool with only must and filter clauses and will all be added to the `filter` section of the previous query.

I think you'll get better results by not relying on the assignment operators and instead do everything in one go:

e.g:

```csharp
sr.Query =
	( 
		new PrefixQuery { Field = "title", Value = "perf" }
		|| new PrefixQuery { Field = "title", Value = "book" }
		|| new PrefixQuery { Field = "title", Value = "base" }
	)
	&&
	(
		+new TermQuery { Field = "accid", Value = 101 }
	 	&& +new TermQuery { Field = "size", Value = 50 }
		&& +new TermQuery { Field = "pages", Value = 3 }
	);
```

This gives you better control over the desired evaluation order.

**Comment by Mpdreamz** [comment]
Also thank you for opening an issue with test code, much appreciated 👍 😄

**Comment by tjkolev** [comment]
Thanks for the explanation. I already had a workaround when I submitted the issue. I explicitly put the sub-queries in the must, filter, should containers of the main query.
Best,
tjk :)
