### ISSUE TITLE
ElasticClient.SearchAsync doesn't work with Generic type anymore (upgrading from <v6.0 to v6.4)

### ISSUE THREAD

**Issue by kanup** [elastic/elasticsearch-net#3459]
How to search across multiple indexes (generic type) and get results in their specific/concrete types in current version (6.4.0)? The old method doesn't work.

**NEST 6.4.0 / Elasticsearch.Net 6.4.0**:

**Elasticsearch 6.4.0**:

In 6.4.0, the definition of mapping for any type has changed from, for example:
```ConnectionSettings.MapDefaultTypeIndices(x => x.Add(typeof(News), "news")```
to:
```ConnectionSettings.DefaultMappingFor<News>(x => x.IndexName("News"))```

This new syntax might be missing some configuration steps inside the library because my generic search doesn't work as before.

Consider the following search command:
```Nest.ElasticClient.SearchAsync<Content>(ISearchRequest)```

Instead of returning documents of mixed derived types such as News, Stories, etc. in the result, it is returning documents of same plain generic type "Content" for everything.

**Comment by kanup** [comment]
The classes ConcreteTypeConverter and CovariantSearch was creating concrete types when deserialising the results.

**Comment by russcam** [comment]
@kanup [Covariant search results](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/covariant-search-results.html) feature was removed in 6.x because types are going away in Elasticsearch. Also take a look at the [blog post release of 6.x](https://www.elastic.co/blog/nest-elasticsearch-net-6-0-ga#covariant-searches). We didn't take this decision lightly, and did so in order to better prepare users for the type change going forward. 

You can implement covariant search results by hooking up [`JsonNetSerializer`](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html#_jsonnetserializer) and configuring [`TypeNameHandling`](https://www.newtonsoft.com/json/help/html/SerializeTypeNameHandling.htm). If you don't have a discriminator field on your documents, it would be possible to add one using [`Update by query` API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html).
