### ISSUE TITLE
Bump JSon.NET version to 12.x for Elasticsearch 2.x

### ISSUE THREAD

**Issue by AGiorgetti** [elastic/elasticsearch-net#3581]
Will it be possible to update the 2.x drivers to Newtonsoft.Json 12.x ?

Or maybe consider removing the upper limit to the 2.x NuGet package, so the users can decide to update the library at their own risk (given the fact 2.x is a really old version and should be updated anyway sooner or later).

**Comment by Mpdreamz** [comment]
This is something we'll discuss tomorrow. It has come up in the past.

We totally can do a release whenever we drop support for a major version to do a last release where we drop the upperbound restrictions of dependencies. 

This will get you out of a bind if other dependencies force you to upgrade and you are not ready to update Elasticsearch yet. 

The downside is that major version of Json.NET can carry breaking changes and we never tested that version and now we need to field off questions when it does break or do a break fix release on an unsupported/EOL branch which `2.x` is. 

Since `6.x` the dependency is gone so this story becomes moot.

**Comment by codebrain** [comment]
We discussed this recently and decided to close the issue based on the following:

- `2.x` is end of life and has been for some time: https://www.elastic.co/support/eol
- The current released version of `2.x` is known to work with the dependencies as published. This is not guaranteed to be the case if we remove the upper bound for dependencies, and those dependencies introduce breaking changes in the future.
- Making public changes to `2.x` sends the wrong signal that it is being maintained, and creates additional scope for issues to be raised against this newly released version.

Our suggestion would be to fork the code base and modify the dependency to your required version and to validate that the change does not introduce any issues.

Thanks
