### ISSUE TITLE
Cannot read from a closed textreader -> ingesting a ParallelQuery

### ISSUE THREAD

**Issue by Angr1st** [elastic/elasticsearch-net#3590]
**Elasticsearch.Net version 6.5**:

**Elasticsearch version 6.6.1 **:

**Description of the problem including expected versus actual behavior**:

I am writing a library to insert  Csvs into elasticsearch using TinyCsv and Elasticsearch.net see [here](https://github.com/Angr1st/TinyCsvToElasticsearch) I encountered a System.Aggregate Exception with the InnerException ObjectDisposedException: Cannot read from a closed TextReader. TinyCsv returns me a ParallelQuery<T> which I try to feed to the PostData.MultiJson. If the csv is really small only 10 lines it works fine but moving to a more realistic size 200k lines or more I get this exception. 

**Steps to reproduce**:
 1.Clone [this](https://github.com/Angr1st/TinyCsvToElasticsearch) repo and checkout this branch FixingClosedTextReader
 2. Open the sln and debug the TinyCSVToES.csproj
 3. Experience the exception.

**Comment by russcam** [comment]
The problem is that `BulkInsert` attempts to send _all_ records in a single bulk request i.e. a single HTTP call. It should partition the `IEnumerable<CsvMappingResult<Person>>` that the `ParallelQuery<CsvMappingResult<Person>>` represents so that multiple bulk requests are made. How many records should go in a single bulk request is going to vary on a number of factors, but a general rule is to limit the total size of the request to a _reasonable_ byte size e.g. 1-5 MB.

NEST has an observable helper, `BulkAll`, that can partition an `IEnumerable<T>` into multiple concurrent bulk requests. I've sent you a PR with a working example https://github.com/Angr1st/TinyCsvToElasticsearch/pull/4

**Comment by Angr1st** [comment]
Thanks a ton. I just tested it on my system and your example works like a charm. 
During next week I will adjust my code generation to match the new code. 
There is only one thing, is there an async way of doing all this?

**Comment by russcam** [comment]
@Angr1st I would highly recommend looking at [Rx .NET](http://reactivex.io/) as you're wanting to do async programming on observables.

**Comment by Angr1st** [comment]
Thanks I will look into it 😊

Russ Cam <notifications@github.com> schrieb am Mo., 18. März 2019, 01:11:
