### ISSUE TITLE
7.0.0 - Cannot parse hits._source into ISearchResponse.Documents

### ISSUE THREAD

**Issue by bagamoon** [elastic/elasticsearch-net#3689]
**NEST/Elasticsearch.Net version**:
7.0.0-alpha1

**Elasticsearch version**:
7.0.0

**Description of the problem including expected versus actual behavior**:

Hi, I've sent search request via Nest IElasticClient.SearchAsync() as following:

```json
GET /player_profile*/_search
{
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "LoginId": {
              "query": "loginId1"
            }
          }
        },
        {
          "match": {
            "MobileNumber": {
              "query": "loginId1"
            }
          }
        },
        {
          "match": {
            "Email": {
              "query": "loginId1"
            }
          }
        }
      ]
    }
  },
  "_source": {
    "includes": [
      "PlayerId"
    ]
  }
}
```

result
```json
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 0.6931472,
    "hits" : [
      {
        "_index" : "player_profile",
        "_type" : "doc",
        "_id" : "663b433e-f36b-1410-8104-004df507d47e",
        "_score" : 0.6931472,
        "_source" : {
          "PlayerId" : "663b433e-f36b-1410-8104-004df507d47e"
        }
      }
    ]
  }
}
```

POCO class in c#
```c#
public sealed class PlayerElkData
{
        public Guid PlayerId { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string LoginId { get; set; }
}
```

The search result could be deserialized into ISearchResponse.Hits, however ISearchResponse.Documents and ISearchResponse.Hits[0].Source are both empty objects  

It should deserialize "663b433e-f36b-1410-8104-004df507d47e" into PlayerId property 

Is there something wrong in request, response or the POCO class?

Any suggestion would be appreciated, thank you!

**Provide `DebugInformation` (if relevant)**:

(some part of ip address were masked)

Valid NEST response built from a successful low level call on POST: /player_profile/_search?typed_keys=true
Audit trail of this API call:
 - [1] SniffOnStartup: Took: 00:00:00.2516981
 - [2] SniffSuccess: Node: http://172.16.**.**:9200/ Took: 00:00:00.2463194
 - [3] PingSuccess: Node: http://172.16.**.**:9200/ Took: 00:00:00.0203828
 - [4] HealthyResponse: Node: http://172.16.**.**:9200/ Took: 00:00:00.0987998
Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
Response:
<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>

**Comment by Mpdreamz** [comment]
Thanks for reporting this @bagamoon will investigate deeper soon. 

Initial thoughts might be related to the fact the class is sealed.

**Comment by russcam** [comment]
the serializer in NEST 7.0 is stricter with regards to JSON field -> POCO property name casing. Where 6.x would be somewhat case insensitive during deserialization, 7.x is not. 

The default casing is Camel casing in NEST, so the serializer looks for a `playerId` field in JSON to deserialize into the `PlayerId` property. If the `DefaultFieldNameInferrer()` is specified to use Pascal casing then deserialization works as expected

```
void Main()
{
	
	var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));

	var bytes = Encoding.UTF8.GetBytes(@"{
  ""took"" : 1,
  ""timed_out"" : false,
  ""_shards"" : {
    ""total"" : 5,
    ""successful"" : 5,
    ""skipped"" : 0,
    ""failed"" : 0
  },
  ""hits"" : {
    ""total"" : {
      ""value"" : 1,
      ""relation"" : ""eq""
    },
    ""max_score"" : 0.6931472,
    ""hits"" : [
      {
        ""_index"" : ""player_profile"",
        ""_type"" : ""doc"",
        ""_id"" : ""663b433e-f36b-1410-8104-004df507d47e"",
        ""_score"" : 0.6931472,
        ""_source"" : {
          ""PlayerId"" : ""663b433e-f36b-1410-8104-004df507d47e""
        }
      }
    ]
  }
}");

	var connection = new InMemoryConnection(bytes);
	
	var settings = new ConnectionSettings(pool, connection)
		.DefaultFieldNameInferrer(f => f);

	var client = new ElasticClient(settings);
	
	var searchResponse = client.Search<PlayerElkData>(s => s.Index("foo"));
	//  663b433e-f36b-1410-8104-004df507d47e as expected
	var id = searchResponse.Documents.First().PlayerId;
}

public sealed class PlayerElkData
{
	public Guid PlayerId { get; set; }
	public string MobileNumber { get; set; }
	public string Email { get; set; }
	public string LoginId { get; set; }
}
```

@Mpdreamz @codebrain being more lenient here for document POCOs would have a performance impact, as it would require encoding differently cased property names into an `AutomataDictionary` against which the POCO property name is matched.

**Comment by codebrain** [comment]
I think it is reasonable for the user to expect `PlayerId` in the json to deserialise into a `PlayerId` property on the POCO, without having to specify the empty `DefaultFieldNameInferrer` lambda.

The `AutomataDictionary` is a ranked list of attemptable property names? I'm wondering if the move to the different serialiser requires some additional thought around the settings/configuration?

**Comment by russcam** [comment]
> I think it is reasonable for the user to expect PlayerId in the json to deserialise into a PlayerId property on the POCO, without having to specify the empty DefaultFieldNameInferrer lambda.

I feel it's a little more nuanced, and I'll try to explain why. 

I think that the serializer should be able to deserialize what it serializes. The serializer in NEST has defaulted to camel casing since the beginning (_I believe_, @Mpdreamz will know 😄 ), so were the JSON in Elasticsearch to have been serialized by the client, the fields would be camel cased and there would be no problem in the client deserializing them. With the `DefaultFieldNameInferrer()` configuration option, the ability to override the casing convention globally is provided, and with `DataMemberAttribute`, `PropertyNameAttribute` and the other respective `ElasticsearchPropertyAttributeBase` attributes, a way to override on an individual basis is provided.

When a `JsonFormatter<T>` is generated for some POCO `T`, the `DefaultFieldNameInferrer` and attributes influence the property keys generated for POCO property names, which end up as `byte[]` and compared to `byte[]` that are read from the response stream (buffered in a `byte[]`) representing the JSON property names. This is done for performance purposes and reduces the number of string allocations that happen. At this level, in order to perform case insensitive searches (or at a minimum, camel cased and pascal cased I suspect), property keys would need to be generated for each case variant, doubling the number of keys in `AutomataDictionary`.

Changing the default from camel cased property names would be a massive breaking change not on the binary level, but to expectations, which I don't think we should do. We could generate pascal cased keys for non NEST/Elasticsearch.NET types in addition to whatever `DefaultFieldNameInferrer()` will generate, but it means **all users** will pay this performance cost.

**Comment by Mpdreamz** [comment]
I agree I would like to remove this leniency moving forward. We inheritted this leniency from Json.NET. Our move to internalize this dependency was all about becoming json lib agnostic. 

Say System.Text.Json sweeps the .NET world and doesn't have this leniency, would we be expected to keep it if we move from our UTF8Json to it? 

Like @russcam mentioned NEST has always serialized camelCase. I'd be in favor of not reintroducing this leniency put performance first as we have a lot of mechanisms to control this explicitly already.

**Comment by russcam** [comment]
I'll close this if you're OK with removing this leniency, @codebrain?

**Comment by codebrain** [comment]
Having read the arguments, I think it is fine to remove the leniency, I think that we ought to call this out in the documentation for `7.x` so that we make customers aware.

@russcam - feel free to close.

**Comment by russcam** [comment]
Thanks @codebrain. This is something we should definitely call out 👍
