### ISSUE TITLE
why Nest/Ealsticsearch.Net first time call take longer time when i search small data's index?

### ISSUE THREAD

**Issue by sunweiconfidence** [elastic/elasticsearch-net#3721]
NEST/Elasticsearch.Net version: 6.6

Elasticsearch version:6.7.1

Expected: first time search response time take less than 1 second
Actual: first time search response time take 15 seconds

Steps to reproduce:
var searchResultTemp = ESClient.LowLevel.Search<StringResponse>("people", "test", PostData.Serializable(new
            {
               from = 0,
                size = 10
            }));

then use postman tool to call search web api to wait for result, it will take 15 seconds to return the result, but second time it is very fast, why so slow in first time call, could you provide some methods to reduce the response time? Thanks

**Comment by russcam** [comment]
The very first call will be slower than others because the client caches a lot of type metadata on the first call that is needed for serialization. If this a problem for your application, you can initiate the first call during client setup, when the application starts. 15 seconds seems like a long time, how have you measured that all or the majority of this time is spent by the client?

As this is a question rather than a bug or feature request, and since you have also [asked it on the discuss forums](https://discuss.elastic.co/t/whether-nest5-2-0-and-elasticsearch-net-5-2-0-can-support-elasticsearch6-7-1-query-aggregation-sort/177750/3?u=forloop), I'm going to close this issue.
