### ISSUE TITLE
Linq support

### ISSUE THREAD

**Issue by zengpu2109** [elastic/elasticsearch-net#3845]
ElasticLINQ is not maintain and not support for netcore,does nest can support iqueryable<T>,or wrapper response like IQueryable<EsEntity<T>>,linq support sometimes is very usefull

**Comment by Mpdreamz** [comment]
Not at the moment, I've always stayed clear of implementing `IQueryable` since I do not think it translates well to Elasticsearch search DSL and would not be something I personally use. 

Now that Elasticsearch supports SQL we might end up supporting `IQueryable` which translates to a sql string either internally or document a 3rd party library that already does a great job of that.

Marking this as `Won't fix` but its on our low priority/low hanging fruit backlog.
