### ISSUE TITLE
TimespanToStringFormatterResolver implementation

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#3857]
Also remove TODO comment in `NestFormatterResolver`

**Comment by russcam** [comment]
This is a little more involved than first thought. An `IJsonFormatterResolver` only has access to `T`, the type, to determine whether to return a formatter. With `TimeSpan` and `TimeSpan?`, a `TimeSpanToStringFormatter` should be returned only when a _property_ of `TimeSpan` and `TimeSpan?` is attributed with `StringTimeSpan`. 

To allow for this, `IJsonProperty` can be extended to allow a formatter type to be identified based on attributes of a property. This formatter type would need to be propagated to `MetaMember` so that a formatter field of the type is emitted in the generated formatter for the POCO on which the property is declared.
