### ISSUE TITLE
Issue with Compound queries wrap other compound or leaf queries

### ISSUE THREAD

**Issue by peiqinli** [elastic/elasticsearch-net#3898]
**NEST/Elasticsearch.Net version**:
6.5.0
**Elasticsearch version**:
6.8
**Description of the problem including expected versus actual behavior**:
I have an issue with function score compound query wrap Bool compound query. if I just passing the filter bool query inside the query of function score query. I got empty JSON result back.
**Steps to reproduce**:
 1. var boolquery = new BoolQuery(){ Filter= # filter here}
 2. new FunctionScoreQuery(){Query = boolquery }
 3. return empty json {}

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Describe the feature**:

**Comment by russcam** [comment]
This is by design.

A function_score query without functions is considered [_conditionless_](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/verbatim-and-strict-query-usage.html) by NEST. Consider

```c#
var client = new ElasticClient();
var boolquery = new BoolQuery { Filter = new QueryContainer[] { new MatchAllQuery() } };
var query = new FunctionScoreQuery { Query = boolquery };
var searchRequest = new SearchRequest { Query = query };
Console.WriteLine(client.RequestResponseSerializer.SerializeToString(searchRequest));
```

results in 

```json
{}
```

Conditionless queries are a feature designed to make writing complex queries easier, without a NEST user needing to `if`/`else` check when inputs are `null`, and empty collection, etc. Conditionless behaviour can be disabled with `IsVerbatim` when using the object initializer syntax, or `Verbatim()` using the fluent lambda syntax

```c#
var client = new ElasticClient();
var boolquery = new BoolQuery { Filter = new QueryContainer[] { new MatchAllQuery() } };
var query = new FunctionScoreQuery() 
{ 
	Query = boolquery,
	IsVerbatim = true // <-- serialize this query exactly as is
};

var searchRequest = new SearchRequest { Query = query };
Console.WriteLine(client.RequestResponseSerializer.SerializeToString(searchRequest));
```

results in

```json
{
  "query": {
    "function_score": {
      "query": {
        "bool": {
          "filter": [
            {
              "match_all": {}
            }
          ]
        }
      }
    }
  }
}
```
