### ISSUE TITLE
TypeName is wrong. _type": "_doc",

### ISSUE THREAD

**Issue by bogiahuy** [elastic/elasticsearch-net#3903]
I Using .DefaultMappingFor<Course> But in es  is no Type. 

ES 7.2, NEST 7.0

**Comment by russcam** [comment]
@bogiahuy please can you follow the issues guidelines to provide more detail:

```
<!--
GitHub is reserved for bug reports and feature requests. The best place
to ask a general question is at the Elastic Discourse forums at
https://discuss.elastic.co. If you are in fact posting a bug report or
a feature request, please include one and only one of the below blocks
in your new issue.
-->

<!--
If you are filing a bug report, please remove the below feature
request block and provide responses for all of the below items.
-->

**NEST/Elasticsearch.Net version**:

**Elasticsearch version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

<!--
If you are filing a feature request, please remove the above bug
report block and provide responses for all of the below items.
-->

**Describe the feature**:
```

**Comment by bogiahuy** [comment]
**NEST/Elasticsearch.Net version**: 7.0.0
**Elasticsearch version**: 7.2
**Description of the problem including expected versus actual behavior**: don't create Type  when using .DefaultMappingFor<Course>

  var settings = new ConnectionSettings(new Uri(url))
                .DefaultIndex(defaultIndex)
                .DefaultMappingFor<Course>(m => m                    
                    .PropertyName(p => p.Id, "id")                    
                )
After IndexDocumentAsync(course)  type in document is "_doc". correct is "course"

**Comment by russcam** [comment]
@bogiahuy Types are deprecated in APIs in 7.0, with breaking changes to the index creation, put mapping, get mapping, put template, get template and get field mappings APIs. [See Removal of mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/removal-of-types.html).

Specifying types in requests is deprecated. For instance, indexing a document no longer requires a document type. Note that in 7.0, `_doc` is a permanent part of the path, and represents the endpoint name rather than the document type.
