### ISSUE TITLE
ElasticClient not IDisposable

### ISSUE THREAD

**Issue by sybaris** [elastic/elasticsearch-net#4018]
Hi,

ElasticClient does not implement IDisposable, but use IDisposable objects as instance fields (Transport field).
This can cause memory leaks.

Sybaris

**Comment by codebrain** [comment]
Hi @sybaris,

The expectation is that the `ElasticClient` is registered as a Singleton in your application. We have some recommendations around object lifetimes: https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/lifetimes.html
...and recommendations for the transport: https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/transports.html

The concern here is that by having `ElasticClient` implement `IDisposable` we are surfacing the potential for `HttpClient` to become disposed and this can cause some serious side effects: https://stackoverflow.com/questions/15705092/do-httpclient-and-httpclienthandler-have-to-be-disposed

Hopefully this provides some guidance on how we envisage the client and underlying transport is to be used.

**Comment by sybaris** [comment]
Hi,

Thanks you very much for these informations. I will take a look on the recommandations...

Regars,
Sybaris

**Comment by codebrain** [comment]
We have decided to look towards implementing `IDisposable` on the client in `8.0.0`, on the basis that the client can technically become the "owner" of an object that implements `IDisposable` in some of the default constructor arguments.

An example is here: https://github.com/elastic/elasticsearch-net/blob/fd5716fd6cf0edb6cd9d07fdb2c1bcf865a6f9c9/src/Nest/ElasticClient.cs#L95

We would potentially implement, in `8.0.0` a pattern whereby if the client was the defacto "owner" of a created object then the `Dispose` method on the client would invoke the necessary chain of disposal for all child objects. Since this is a potentially disruptive change in behaviour it is something we would implement in the next major version.

I am going to close this ticket for the time being as hopefully I have answered your original issue.
