### ISSUE TITLE
NEST is dropping terms search criteria when its given an empty list of terms, leading to unabated searches and incorrect results

### ISSUE THREAD

**Issue by StingyJack** [elastic/elasticsearch-net#4020]
**NEST/Elasticsearch.Net version**:
6.6
**Elasticsearch version**:
6.6

Given the simplified example of...
``` csharp
var documentIds = someOtherList.Select(d => d.DocumentId).Distinct();

var result = await eClient.SearchAsync<CollectedArtifact>(c =>
   c.Source(sr => sr.Includes(ic => ic.Fields(fd => fd.ArtifactId,
   fd => fd.Alerts,
   fd => fd.EffectiveDate, 
   fd => fd.DocumentTypeName,
   fd => fd.DocumentSubTypeName)))
  .Query(q => q.Terms(t => t.Field(fd => fd.ArtifactId).Terms(documentIds)))
); //example was from trimmed existing code, I didnt count the perens and commas, etc. 
```
... if the list of documentIds has any values, then NEST generates the "terms" criteria with the documentId values given, and the result represents documents that had an artifactId field that matched an entry in that documentId's list.

If the list of documentID's has no values, then NEST omits the "terms" criteria entirely from the query, and the result represents any document that can be served, not just ones that match items in the terms criteria.  

It is expected that the query generation is consistent, not that it bring back results that do not meet the command given to the API. This defect could expose sensitive details

**Comment by russcam** [comment]
This is a feature of the client known as _conditionless_ queries; If the input to a query is determined to be conditionless, it is omitted in the serialized request. For a `terms` query, these conditions are

https://github.com/elastic/elasticsearch-net/blob/623c724a3205b21ffca9cf88338f94697efef677/src/Nest/QueryDsl/TermLevel/Terms/TermsQuery.cs#L25-L37

1. `Field` is conditionless (filed resolves to a null or empty string)
2. `Terms` is `null`, an empty collection, or all terms are null or empty

    or

    `TermsLookup` is `null` or any components of `TermsLookup` are `null`

Conditionless behaviour is intended to make writing complex queries easier, avoiding the need for the user to check inputs and conditionally add components of a query. Conditionless behaviour can be overridden on a per query basis using `Verbatim`

```c#
var searchResponse = client.Search<Question>(s => s
	.Query(q => q
		.Terms(t => t
			.Field(f => f.Tags)
			.Terms("")
			.Verbatim()
		)
	)
);
```

which will emit

```json
POST http://localhost:9200/posts/_search
{"query":{"terms":{"tags":[""]}}}
```

_(An aside - no documents will be a match for this query)_.

Conditionless queries have been a feature of the client since 1.x, so I think it's unlikely that they would change at this point. There is documentation on [Verbatim and Strict queries](https://www.elastic.co/guide/en/elasticsearch/client/net-api/6.x/verbatim-and-strict-query-usage.html) but it is somewhat hidden. I think we can say more about them in the [Search section](https://www.elastic.co/guide/en/elasticsearch/client/net-api/6.x/search.html), similar to the [1.x](https://www.elastic.co/guide/en/elasticsearch/client/net-api/1.x/writing-queries.html#conditionless-queries) and [2.x documentation](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/verbatim-and-strict-query-usage.html).

**Comment by StingyJack** [comment]
> Conditionless behaviour is intended to make writing complex queries easier

Every query in elasticsearch seems to be complex and counter intuitive, and made harder by non-standard or just plain odd terminology. "Query" or "Search"? "Sources" or "Fields"? "match" or "terms"? The presence of a source/field/term/key with a null value is treated the same as the absence of the field. Etc. etc. </soapbox> Sorry.

> (An aside - no documents will be a match for this query)

Yes, thats correct. No matching terms means 0 results to pass along to the user. I'm sure you understand the detriment associated with the current behavior but I'll state it anyway; users are getting access to documents and data that they should not have permission to see, and general usage is affected when mysterious unrelated document results are retrieved for users or background processes.

> feature

I'm sorry but I expect the query I crafted to be sent to the server, and not for parts of it to be dropped that will _completely_ alter the scope and returned results. The workaround I had to go with was to add a conditional branch that can avoid querying ES if the term list is going to be empty.

Can there be a tag for issues to cover "illogical gotchas"?  All this feedback regarding difficulty of use needs to not go to a developer and stop there "as designed".

**Comment by russcam** [comment]
> Every query in elasticsearch seems to be complex and counter intuitive, and made harder by non-standard or just plain odd terminology. "Query" or "Search"? "Sources" or "Fields"? "match" or "terms"? The presence of a source/field/term/key with a null value is treated the same as the absence of the field. Etc. etc. Sorry.

I'm not sure what to say here. Much of the Elasticsearch terminology is _inherited from/aligned with_ Lucene, and the client aligns with Elasticsearch. For example, 

- `match` and `terms` are types of query
- `Search` is an action performed against the `_search` API, and a `Query` forms part of the request input. 
- `Source` and `Fields` mean different things; the former relates to the original _source_ JSON document sent to Elasticsearch. `Fields` are individual fields from that JSON document.

> Yes, thats correct. No matching terms means 0 results to pass along to the user. I'm sure you understand the detriment associated with the current behavior but I'll state it anyway; users are getting access to documents and data that they should not have permission to see, and general usage is affected when mysterious unrelated document results are retrieved for users or background processes.

You can mark a query as `.Verbatim()` to send exactly as is. Query filters aren't designed for performing Document level security, so I would advise against using them for that purpose.

> Can there be a tag for issues to cover "illogical gotchas"? All this feedback regarding difficulty of use needs to not go to a developer and stop there "as designed".

As previously explained, _conditionless_ queries are a feature that have existed in the client for a long time, a feature that we know are used by many users. To therefore change how they work is something that would need to be discussed further, and if were to be changed, would very likely need to go into a future major release. I've opened #4050, I invite you to discuss conditionless queries there.

Closing this.
