### ISSUE TITLE
Terms aggregation response for a field of type long is of type double

### ISSUE THREAD

**Issue by mostmand** [elastic/elasticsearch-net#4063]
**NEST/Elasticsearch.Net version**:
7.2.0

**Elasticsearch version**:
7.3.1
**Description of the problem including expected versus actual behavior**:
When I use terms aggregation query for "elementId" field which is defined as long, the key of the KeyedBucket returned is double. I expected it to be long as it previously was in Nest 6.4.

**Steps to reproduce**:
```csharp
var elementCount = "elementCount";

var searchResult = client.Search<object>(x => x
                        .Size(0)
                        .Index(this.Indices)
                        .Query(q => query)
                        .Aggregations(a => a
                            .Terms(elementCount, c => c
                                .Size(1000)
                                .Field("elementId"))), cancellationToken);

foreach (KeyedBucket<object> elementItem in (searchResult.Aggregations[elementCount] as BucketAggregate).Items)
{
  var elementId = Convert.ToInt64((double)elementItem.Key);
}
```

**Comment by russcam** [comment]
This change is related to the change in serializer between 6.x, which internally uses Json.NET, and 7.x, which internally uses a fork of Utf8Json. We're unlikely to change the behaviour in Utf8Json to match that of Json.NET because it's an internal implementation detail, and would result in additional overhead for all cases where bucket keys are numeric values.

I would recommend using the generic `Terms<TKey>()` method to get the `KeyedBucket<TKey>` buckets, which alleviates the need to perform the cast in your code

```c#
foreach(var bucket in searchResponse.Aggregations.Terms<long>(elementCount).Buckets)
{
	Console.WriteLine(bucket.Key);
}
```
