### ISSUE TITLE
Indices.Exists returns always IsValid = false on none existing indices

### ISSUE THREAD

**Issue by UkrZilla** [elastic/elasticsearch-net#4094]
NEST/Elasticsearch.Net version:
7.3.0
Elasticsearch version:
7.3.2
.NET Framework 4.6.2
Description of the problem including expected versus actual behavior:

Indices.Exists always returns IsValid = false on none existing indices
This can be observed for Indices.ExistsAsync too.

I think it should return IsValid = true or I am mistaken?

**Comment by UkrZilla** [comment]
NEST 6.8 does not check statusCode and returns True in this case:
public virtual bool IsValid => (ApiCall?.Success ?? false) && ServerError == null;

NEST 7.3:
var statusCode = ApiCall?.HttpStatusCode;
if (statusCode == 404) return false;
return (ApiCall?.Success ?? false) && ServerError == null;

**Comment by russcam** [comment]
@UkrZilla The implementation for how all responses are handled and deserialized was revisited in 7.x and the implementation for `ExistsResponse` also revisited. 

It's been discussed numerous times over the years, both on issues and internally, about what the semantics should be for `IsValid` and exists responses:

- https://github.com/elastic/elasticsearch-net/issues/3707
- https://github.com/elastic/elasticsearch-net/pull/3873
- https://github.com/elastic/elasticsearch-net/issues/1621

The end decision at this time per #3873 is that a 404 is marked as `.IsValid = false`, so that it signals to the consumer that `.Exists` and status codes should also be checked. [This breaking change is listed in the 6.x -> 7.x breaking changes docs.](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/nest-breaking-changes.html#_high_level_client).

I'm going to close this issue as I don't think we'd want to change this behaviour going forward.
