### ISSUE TITLE
NEST - How to pass Sort value to result object

### ISSUE THREAD

**Issue by gang89** [elastic/elasticsearch-net#4181]
Hi,

**Issue**
I am currently unable to get the sort value populated in my result.Documents response object despite elasticsearch API returning Sort key-value.

How can i retrieve the Sort value efficiently from elasticSearch / NEST?

Am currently new to NEST and am stuck on this. Any help with be greatly appreciated

**System Pre-requisite**
- .Net Core 2.2
- NEST 7.3.1
- Elasticsearch 7.2.1

**Details:**

**Object Declaration:**
```
public class Restaurant
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        ...
        public GeoLocation  Location { get; set; }
    }

    [ElasticsearchType(RelationName = "Restaurant")]
    public class RestaurantResult : Restaurant
    {
        public double[] Sort { get; set; }
    }
```
**Implement Automap on object:**
```
var createIndexResponse = client.Indices.Create("restaurants", c => c
                .Map<Restaurant>(m => m.AutoMap())
                .Map<RestaurantResult>(m => m.AutoMap()));
```
**Sort Query with RestaurantResult as response:**
```
var result = await _elasticClient.SearchAsync<RestaurantResult>(s => s
                .Query(q => ...)
                 .Sort(ss => distanceSort)
                 .Source()
                    );

private SortDescriptor<RestaurantResult> DistanceSort(double lat, double lon)
        {
            var distanceSort = new SortDescriptor<RestaurantResult>().GeoDistance(g => g.
                    Field(p => p.Location)
                    .DistanceType(GeoDistanceType.Arc)
                    .Order(SortOrder.Ascending)
                    .Unit(DistanceUnit.Kilometers)
                    .Mode(SortMode.Min)
                    .Points(new GeoLocation(lat, lon))
                    .IgnoreUnmapped(true));

            return distanceSort;
        }

```

**Comment by gang89** [comment]
Even tried using scripted fields, but have no idea how to get the data in the Fields object. Any advise will be greatly appreciated.

**Comment by russcam** [comment]
The sort values are exposed on the hit metadata and can be retrieved with

```c#
var searchResponse = client.Search<Document>();
	
foreach (var hit in searchResponse.Hits)
{
    var sorts = hit.Sorts;
}
```

Since sort values can be any primitive JSON value, `hit.Sorts` is an `IReadOnlyCollection<object>`, so you'll need to cast to the expected type, which I think would be `double` in the case of a distance. You may also be interested in using the [`distance` functions on `geo_point`](https://www.elastic.co/guide/en/elasticsearch/painless/7.4/painless-api-reference-shared-org-elasticsearch-index-fielddata.html#painless-api-reference-shared-ScriptDocValues-GeoPoints) in a scripted field, to get the values returned in scripted fields; this may be useful in cases where you want the distance value but don't wish to sort on it.
