### ISSUE TITLE
Map index column to different property name

### ISSUE THREAD

**Issue by ghetze** [elastic/elasticsearch-net#4198]
**NEST/Elasticsearch.Net version**:
7.0.1
**Elasticsearch version**:
7.3.1
**Description of the problem including expected versus actual behavior**:

Hi , I have the following situation.
I want to read an index from elasticsearch into an c# classs.The problem is that one of the column from the index is different from my class property name.
index column name is : jsonrep.test.amount and my class property name is PriceAmount.

[ElasticsearchType(RelationName ="offers")]
    class Offers
    {
        public string name { get; set; }
        [Text(Name = "jsonrep.test.amount")]
        public decimal PriceAmount{ get; set; }
    }

The code for reading from elastic with nest is :  
var connectionSettings = new ConnectionSettings(new Uri(_applicationSettings.ElaticServerUrl))
                .DefaultMappingFor<Offers>(i => i.IndexName("offers"))
                 .EnableDebugMode()
                .PrettyJson()
                .RequestTimeout(TimeSpan.FromMinutes(2));
                
var client = new ElasticClient(connectionSettings);
var offers = client.Search<Offers>(s => s.Size(5000).Query(q => q.MatchAll())).Documents;
 
after this call the list its populated with the indexes but only the name property of every item is populated and the PriceAmount is 0.

Can you give an advice ? What am I doing wrong ? 
Thank you.

**Comment by codebrain** [comment]
Hi @ghetze.

Your mapping attribute looks correct, but you will need to also decorate the property with an attribute for serialisation/deserialisation.

You have some options here:

- https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/field-inference.html#data-member-field-attribute - using `DataMember` attribute.

- https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/field-inference.html#serializer-specific-field-attribute - using `PropertyName` / `JsonProperty` attributes.

Would you be able to try the above and report back?

Also, we have newer versions of the NEST library for 7 available, so you may want to consider upgrading.

Thanks

**Comment by codebrain** [comment]
Closing as no response received and a number of alternate solutions were offered.

**Comment by fluffynuts** [comment]
None of the above documentation exists for v9, and current documentation on subjects like mapping is very sparse. Is there a more up-to-date documentation index somewhere that can help with v9 clients?

**Comment by flobernd** [comment]
@fluffynuts Sure. Please check this: https://www.elastic.co/docs/reference/elasticsearch/clients/dotnet/source-serialization

**Comment by fluffynuts** [comment]
@flobernd thanks for links and info. Whilst I got this to work 100% with an elasticsearch docker container (v9.2.1) as well as on an ES Cloud _hosted_ instance, I can't seem to do this against ES Cloud _serverless_, which is unfortunately how things have been set up for now. I've posted a request to shift to hosted or host our own - will have to see how that goes down, but for now, I don't see a way to create this index in serverless. Attempting to do so returns the error:

```
Parameter [includes] is not allowed in source
```

So it seems as if serverless is not api-compatible with the "real deal" ):

**Comment by flobernd** [comment]
@fluffynuts The API surface of serverless and stack only differs very very slightly. The clients should be compatible in all cases which makes me suspecting a bug here.

Could you please open a new issue for this and paste a minimal reproducer (the single API call that fails should be sufficient).

I'll take care with high priority if it really turns out to be a bug.

**Comment by fluffynuts** [comment]
@flobernd just checking: open an issue here, on github? or is there another place I should be doing that? Also, when you say you want a minimal reproducer - can I repro with a C#/.net repo? or do you want me to capture the index creation request?

**Comment by flobernd** [comment]
@fluffynuts GitHub is the correct place 🙂

**Comment by fluffynuts** [comment]
@flobernd sorry, I was editing as you responded - is a C#/dotnet repo sufficient for reproduction? Or do you want me to capture the request?

**Comment by flobernd** [comment]
@fluffynuts Ah yes, a repo is definitely sufficient!

**Comment by fluffynuts** [comment]
@flobernd here you go - tested against a serverless instance I just created, and it failed as expected: https://github.com/fluffynuts/elasticsearch-index-create-serverless-fail

**Comment by flobernd** [comment]
@fluffynuts Thank you for the link. I was able to reproduce the issue. After asking around internally I found out that this indeed is not allowed with serverless for [technical reasons](https://github.com/elastic/elasticsearch/pull/107097).

The [documentation](https://www.elastic.co/docs/reference/elasticsearch/mapping-reference/mapping-source-field#include-exclude) for this feature unfortunately does not mention this. I'll ask internally to improve this.

As a workaround you could probably go with the default source mappings and use [source filtering](https://www.elastic.co/docs/reference/elasticsearch/rest-apis/retrieve-selected-fields) instead, if you are concerned about sending too much data over the line.

**Comment by fluffynuts** [comment]
@flobernd no, the use-case for these fields is that I want to put in a document with a bunch of integer fields and two name fields (exactly like the repo). The name fields should be _searchable_, but never _retrievable_. In the worst case where someone manages to gain control over our instance, they won't get any real personal data out of it - that's our intention here. So filtering to reduce request load isn't really going to help. The field I'm most interested in is `customer_id` - using the other fields to search for customers by name and their association to a group, callcenter, store, etc. In other words, I want to be able to ask "Find me customers with a first name like Frank", but I should never be able to, say, enumerate all documents and get a list of real human names.

We've already decided to switch to an hosted instance, though it hasn't been set up properly as yet.

**Comment by flobernd** [comment]
@fluffynuts 

> the name fields should be searchable, but never retrievable

I'm not 100% sure, but I think you can still retrieve these fields, even if you strip them from the source (see [fields](https://www.elastic.co/docs/reference/elasticsearch/rest-apis/retrieve-selected-fields#search-fields-param)).

If it was me, I'd only store salted hashes of the `name` fields to make sure they can't get reversed easily. You would still be able to search them - but I guess that's a different topic 🙂

**Comment by fluffynuts** [comment]
I don't think so, unless there's some secret sauce I'm missing. When I search without field specifiers, my models are mapped with nulls for those values. Even if one can get to them if one knows the name, at least that's less obvious, and thwarts a general dump from the service. But I'll verify on monday - not working on this tomorrow (: if I still can retrieve the fields somehow, that actually serves my personal purposes better - I was advocating from the start that we should host our own ES container in our nomad setup.

**Comment by fluffynuts** [comment]
@flobernd ok, I couldn't wait, so I ran the query with a Fields specifier that includes the name fields - no errors from ES, and the fields come back mapped to null, so I'm good with that.

**Comment by flobernd** [comment]
@fluffynuts I just tested and using `.DocvalueFields(new FieldAndFormat("firstName"))` returns me the field even if not included in the source (this works for `keyword` fields, but not for `text` fields).

**Comment by fluffynuts** [comment]
I just switched from `.Fields` to `.DocvalueFields` and I still get back no names. There must be something different between our setups?

**Comment by fluffynuts** [comment]
@flobernd actually, I was wrong - I wasn't using `.DocvalueFields` in the place where I was verifying in a a test. When I applied that in the correct place, I actually get back an error from ES - originally a lot of the same, but narrowing down to only ask for `first_name`, I get the same error:

```
      Reason: "all shards failed"
      RootCause: [ {
        AdditionalProperties: [  ]
        CausedBy: null
        Index: null
        IndexUUID: null
        Reason: "Fielddata is disabled on [first_name] in [test-shouldaddtheordertotheindex-20251128111608]. Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [first_name] in order to load field data by uninverting the inverted index. Note that this can use significant memory."
        StackTrace: null
        Type: "illegal_argument_exception"
      } ]
```
Interestingly, `first_name` _is_ registered as a keyword. So whilst the message is a little misleading (I think), it ends up at the same spot: no `first_name` for callers, even when they explicitly ask for it. I don't know if there's something I'm missing on this, but it feels like there's a generic "can't give you that field, sir" error, and a higher-level bit of code giving the generic advice above.

This issue is quite important because I've been given this guidance based on usage in another project, where PI data also has to be secured, and if this isn't working, that project (which does a lot of work, tbh) would need an overhaul. So I _am_ interested in whether I can break through defenses that I've been told are in place.

**Comment by flobernd** [comment]
Could you please verify the mappings for that index @fluffynuts . I don't think they got applied correctly for some reason.

I did a simple test like this:

```csharp
await client.Indices.CreateAsync<TestData>(x => x.
    Index("indexname")
    .Mappings(x => x
        .Properties(x => x
          .Keyword(x => x.Test)
        )
        .Source(x => x.Excludes("test"))
    )
);

// ... Ingest document (set value of `Test` to `"test"` ... //

var result = await client.SearchAsync<TestData>("indexname", x => x
    .Query(x => x
        .Term(x => x
            .Field(x => x.Test)
            .Value("test")
        )
    )
    .DocvalueFields(new FieldAndFormat("test"))
);
```

The response was similar to:

```json
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 0.2876821,
    "hits" : [
      {
        "_index" : "indexname",
        "_id" : "1",
        "_score" : 0.2876821,
        "_source" : { },
        "fields" : {
          "test" : [
            "test"
          ]
        }
      }
    ]
  }
}
```

Like I said, I'd personally use salted (cryptographic) hashes if you want to prevent the original value from being retrieved in plain text.

It's not a perfect solution either since the salt must be a global constant and can't be set individually per document, but this at least makes it harder to get access to the value since you need access to the Elasticsearch instance and also to the application in order to retrieve the salt. If the application is distributed to the user and does not run as a SaaS application (etc.), this of course makes it very easy for an attacker to extract the salt.

I guess it would be possible to use per document salts by using `script` search. This however will be very slow as it effectively defeats the purpose of indexing.

In the end you should probably make sure to harden your Elasticsearch instance instead to prevent somebody getting access to it in the first place (our Cloud or Serverless solutions already take care of tons of attack vectors btw. compared to a self-hosted solution).

**Comment by fluffynuts** [comment]
@flobernd I'm not using excludes - I'm defining includes on the index, in exactly the same way as in the demo project at https://github.com/fluffynuts/elasticsearch-index-create-serverless-fail provided earlier. I don't know how this changes the ES mappings, but I definitely have been unable to retrieve the keyword fields that were left out of `.Includes`. Try using the definition in that project and see if you can get the names out via some mechanism I've been unable to discover yet?

**Comment by fluffynuts** [comment]
@flobernd I'm also not entirely sure what you're talking about with encryption and salts - if I send encrypted fields, how would I be able to to substring searches? Sure, I could do full-name searches, but that's not what we're looking for.
