### ISSUE TITLE
Support for Brotli in EnableHttpCompression

### ISSUE THREAD

**Issue by symbiogenesis** [elastic/elasticsearch-net#4199]
EnableHttpCompression supports gzip. Any chance we can get a brotli option?

https://devblogs.microsoft.com/dotnet/introducing-support-for-brotli-compression/

**Comment by andrx** [comment]
Do you think it's available on elasticsearch server side or maybe you have already opened the same feature request ticket there?

**Comment by russcam** [comment]
Elasticsearch doesn't support Brotli as far as I am aware. In order to be able to use it in the client, it would need to be supported on the server side, as @andrx indicates. @symbiogenesis, you may want to open an issue under https://github.com/elastic/elasticsearch/issues/new for support.

I'm going to close this client issue for now, as it won't be actionable until the server supports brotli.
