### ISSUE TITLE
TrackTotalHits accepts only "bool" values

### ISSUE THREAD

**Issue by marceloodiniz** [elastic/elasticsearch-net#4241]
According to Elastic documentation, it's possible to send an integer value to "**track_total_hits**" search parameter. TrackTotalHits is currently accepting only "bool" values. 

[Elasticsearch Reference [master] » REST APIs » Search APIs » Request Body Search](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-body.html#request-body-search-track-total-hits)

**Comment by russcam** [comment]
`TrackTotalHits` method is generated from the REST API specs, which currently only specifies a `boolean` value

https://github.com/elastic/elasticsearch/blob/a17c47ec955811559357c2ee3356b1ba1dcc152f/rest-api-spec/src/main/resources/rest-api-spec/api/search.json#L202-L205

This needs to be addressed.

For now, it is possible to set the parameter as an integer, if the `ISearchRequest` is cast to an `IRequest<SearchRequestParameters>`, in order to access the query string set method

```c#
var client = new ElasticClient();

var searchResponse = client.Search<Document>(s =>
{
	IRequest<SearchRequestParameters> request = s;
	request.RequestParameters.SetQueryString("track_total_hits", 1000);
	
	return s;
});
```

which yields

```json
POST default-index/_search?typed_keys=true&track_total_hits=1000 
{}
```

**Comment by marceloodiniz** [comment]
Thanks for the reply. This solutions worked for me while I was requesting a single search. But now I need to use multi search request. How can I do this?

**Comment by russcam** [comment]
@marceloodiniz that's going to be a challenge with the `ISearchRequest` type at present because of how it's generated from the REST API spec. It will need a fix in 7.x to

1. Add `[IgnoreDataMember]` attribute to the `TrackTotalHits` `bool?` property  on the generated `ISearchRequest`
2. Add a new property on the non-generated `ISearchRequest` partial class that can model as both `int` and `bool` i.e. `Nest.Union<int, bool>` and attributed with `[DataMember(Name = "track_total_hits"]`.
3. Implementation for the new property on `SearchRequest` and `SearchDescriptor<T>`

**Comment by russcam** [comment]
I've opened https://github.com/elastic/elasticsearch/pull/51846 to update the REST API spec

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Code-gen work for v8 should resolve this. Please let us know if this issue is still a relevant priority for your usage?
