### ISSUE TITLE
BREAKING CHANGE - Time.ParseUnit doesn't respect casing as well as week, quarter, year + more

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#4251]
We are upgrading to 7.5 and we are calling Time.ParseUnit indirectly (https://github.com/FoundatioFx/Foundatio.Parsers/blob/master/src/Foundatio.Parsers.ElasticQueries/Extensions/DefaultAggregationNodeExtensions.cs#L173-L214) and I noticed that the regex blows up trying to parse valid units. This is a HUGE breaking issue. You can see the in following code that values like `1w`, `1y`, `1M`, `1q` are not supported. Here are the valid time units that mostly worked (looks like quarter wasn't supported at least in nest) in 5.x (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html#calendar_intervalsl)

Here is a link to the expression that doesn't work: https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/CommonOptions/TimeUnit/Time.cs#L25

```
 ---> System.ArgumentException: Expression '1w' is invalid
Parameter name: timeUnit
at Nest.Time.ParseExpression(System.String timeUnit) at offset 89
at Nest.Time..ctor(System.String timeUnit) at offset 81
at Foundatio.Parsers.ElasticQueries.Extensions.DefaultAggregationNodeExtensions.GetInterval(System.String proximity, System.Nullable`1 start, System.Nullable`1 end) at offset 352
```

We have got to flow these through because we need month buckets (and each month/year has a different set of days so we can't just compute it)

**Comment by niemyjski** [comment]
We don't want to have to call two different end points either DateMathTime or Time to figure out what time unit to use. These are all dynamic calls that we want flowed through and not have to parse them. Either way, both don't support all the different time options like quarter... All of the units are valid for aggregations and it's not very easy to use.

**Comment by russcam** [comment]
The `Time` and `DateMathTime` types model `TimeValue` and `DateTimeUnit` types used within Elasticsearch, respectively:

`TimeValue`: https://github.com/elastic/elasticsearch/blob/b7e28a7232616c7a21bc879a535d801b8553ba77/libs/core/src/main/java/org/elasticsearch/common/unit/TimeValue.java#L248-L265

`DateTimeUnit`:
https://github.com/elastic/elasticsearch/blob/b7e28a7232616c7a21bc879a535d801b8553ba77/server/src/main/java/org/elasticsearch/common/Rounding.java#L57-L101

- `Time` supports units `micros`, `nanos`, `ms`, `s`, `m`, `h`, and `d`
- `DateMathTime` supports units `s` `m`, `h`, `d`, `w` `y`

The units `y` and `w` were removed from `Time` in https://github.com/elastic/elasticsearch-net/commit/912170924fcd89d58d0341a67b95d0d618ea73c2#diff-0117475894bff549a74624caf1132c60 and `DateMathTime` introduced, because these units are not valid where a `Time` can be passed. Historically, I believe there were one or two places in Elasticsearch APIs where `w` was accepted for `Time`, but these were removed and units made consistent.

> We don't want to have to call two different end points either DateMathTime or Time to figure out what time unit to use.

If the wrong type is parsed for a particular API, it won't be possible to pass it as a parameter. It could be flowed through as a string, but then there's a possibility that the call will fail because the units supplied are not supported for the API call. Either way, it seems like the correct _time_ type would need to be used to avoid supplying incorrect API inputs.

> Also it's worth nothing that DateHistogramAggregation.FixedInterval only supports Time.

We could introduce another type for `FixedInterval` that supports only `ms`, `s` `m`, `h` and `d` that fixed intervals support i.e. not including `micros` and `nanos` that `Time` supports. @Mpdreamz, @codebrain, thoughts?

For calendar intervals like Month, Quarter and Year, the `CalendarInterval` should be used with the `DateInterval` overload

https://github.com/elastic/elasticsearch-net/blob/36504fa3761af2d273f49f779dbdc7f955c50103/src/Nest/Aggregations/Bucket/DateHistogram/DateHistogramAggregation.cs#L149

That `CalendarInterval` has an overload that supports `Time` looks like a bug.

**Comment by niemyjski** [comment]
Seems like adding a `FixedInterval` time unit might be the best way to do it as it would be tied to a specific agg type? But the docs at least online don't say anything about time units smaller than `1m` but we obviously do small buckets down to a second (normally between `1s` and and `15s`) but I could even see us supporting `1ms`. What do you recommend we use in the mean time (We went through QA and are about to release but are blocked as we have saved agg queries that customers need to run, from seconds to year time buckets).

**Comment by niemyjski** [comment]
I definitely think we need to do some work to our parsers to ensure we specify either a CalenderInterval or a FixedInterval. It would be nice if NEST helped with parsing known formats like a try parse. Regardless there is some work here with time units that it looks like the time unit is parsing that doesn't align with docs like nanos and micro seconds (I think we just need an extra pair of eyes on this. Also I noticed the parser supports `+-` in intervals but I don't see anything like this in the elastic documentation.

**Comment by ejsmith** [comment]
I'm so confused. I am running Elasticsearch 7.5.0 and I doing a `date_histogram` aggregation with `calendar_interval` values of:
-  `1M`
   - Works directly in ES
   - Works if I specify the string `1M` to `DateHistogramAggregationDescriptor<T>.CalendarInterval`
-  `month`
   - Works directly in ES
   - Fails to parse if I specify the string `month` to `DateHistogramAggregationDescriptor<T>.CalendarInterval` with `Expression 'month' is invalid`
-  `M`
   - Fails directly in ES with `The supplied interval [M] could not be parsed as a calendar interval.`, but the [documentation page](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html#calendar_intervals) says that it is a valid value.
   - Fails to parse if I specify the string `M` to `DateHistogramAggregationDescriptor<T>.CalendarInterval` with `Expression 'M' is invalid`

**Comment by russcam** [comment]
>But the docs at least online don't say anything about time units smaller than 1m

The Date Histogram docs have [fixed intervals to milliseconds](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html#fixed_intervals).  The time values docs [have values down to nanos](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/common-options.html#time-units).

> but I could even see us supporting 1ms. What do you recommend we use in the mean time (We went through QA and are about to release but are blocked as we have saved agg queries that customers need to run, from seconds to year time buckets).

I'm not sure what the smallest value supported for buckets is, but looking at `DateHistogramInterval`, it looks like it _may_ be `1s`, which can also be supplied as `1000ms` input: 

https://github.com/elastic/elasticsearch/blob/6ae6f57d39f473e4968700a28a582b93fe3a3bf4/server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramInterval.java#L37-L66

> -  `M`
>    - Fails directly in ES with `The supplied interval [M] could not be parsed as a calendar interval.`, but the [documentation page](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html#calendar_intervals) says that it is a valid value.
>    - Fails to parse if I specify the string `M` to `DateHistogramAggregationDescriptor<T>.CalendarInterval` with `Expression 'M' is invalid`

There's something not right; either the documentation should be clearer, or the implementation should also support the single character time units, which it looks like it doesn't

https://github.com/elastic/elasticsearch/blob/23bf310c849c77e50ab87dbb59ea42d9412fe187/server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java#L79-L98

@ejsmith would you like to open an issue on https://github.com/elastic/elasticsearch/issues ?

**Comment by russcam** [comment]
Thanks for opening a ticket, @niemyjski. I don't think there is any further action to take on the client, so I am going to close this ticket.
