### ISSUE TITLE
NEST internal connections

### ISSUE THREAD

**Issue by RPM1984** [elastic/elasticsearch-net#4279]
I have a NEST client configured like this:

```
var pool = new SingleNodeConnectionPool(uri);
            var settings = new ConnectionSettings(
                                    pool,
                                    sourceSerializer: (builtin, connectionSettings) => new JsonNetSerializer(builtin, connectionSettings)
                               ).DefaultIndex(indexName)
                                .EnableHttpCompression();
var client = new ElasticClient(settings);
```

Which i use throughout the app, ie a singleton.

However i noticed in my app (Azure App Service), many outbound connections are being created:
![image](https://user-images.githubusercontent.com/930343/70978783-813bff00-2104-11ea-98ce-439a64f83234.png)

So my questions are:
- Is it normal for NEST to be opening this many outbound connections?
- Does NEST do HTTP keep alive by default?

**Comment by Mpdreamz** [comment]
By default we cap the maximum number of `80` TCP connections on Windows and we do use HTTP keep alive. So the graph wobbling around 80-180 range falls in the somewhat expected range.

On .NET Full Framework we proactively set `TcpKeepAlive()` on the connections on .NET core we do not do this. Mainly because on `netstandard1.3` this was not available. This might explain the growth if depending on a lower load sockets end up being closed.

If you do the following:

```
var servicePoint = ServicePointManager.FindServicePoint(uri);
servicePoint.SetTcpKeepAlive(true, 2000, 2000);
```

In your app do you find the graph to be more stable? You might also want to limit the number of TCP connections further on `ConnectionSettings().ConnectionLimit()`

**Comment by RPM1984** [comment]
@Mpdreamz thanks for jumping in so quickly.

Yep, we're on .net core, NEST version 7.4.2 (net standard 2.0)

I can definitely try setting tcp keep alive, or setting connection limits, but my other question is: how many connections _should_ we be opening? In other words, is that graph anything to be concerned about? ie should I try and open fewer connections? (context: I'm seeing intermittent slow outbound calls to Elasticsearch, so I'm digging into TCP connections to see if that's the cause)

Thanks in advance for helping me out 🙂

**Comment by Mpdreamz** [comment]
I think the graph is not concerning immediately since it floats arpimd the `~120` mark. 

On linux netcoreapp2.0 `HttpClient` uses the `CurlHttpHandler` which is [known to be bleed connections](https://github.com/dotnet/corefx/issues/21227) which is why we have a much more aggresive `ConnectionLimit` if we see `CurlHttpHandler` used. If you are on `netcoreapp2.1` and over on linux you should be using the new managed socket http handler though.

We limit the connections to `80` and we have integration tests asserting doing thousands of requests only opens [the expected number of connections to Elasticsearch](https://github.com/elastic/elasticsearch-net/blob/master/src/Tests/Tests/ClientConcepts/Connection/ConnectionReuseAndBalancing.cs#L53)

With longer running processes though TCP connection can be killed off for many reasons (ServicePointManager, Os level, Process level) with the main reason any of the layers deeming an opened connection as idle. How does the OS react to `RST` messages (e.g cancelled tasks), what are the `TIME_WAIT` reuse settings? I can imagine these being more aggressive on Azure App Service then the OS defaults.

How frequent are the slow outbound calls? Do they always happen on a particular type of API call?

**Comment by RPM1984** [comment]
We're not on linux. We're on app service for windows, .net core 2.2.

The other stuff you mentioned is a little low-level/over my head unfortunately 😞 

The slow outbound calls aren't 'frequent', but they occur enough for me to have a look.

In the last 24 hours, we had around 500 'slow' calls (> 4 secs). They're on various API calls.. but they always show the slow bit being the network:
![image](https://user-images.githubusercontent.com/930343/71046269-ef77d480-218b-11ea-806e-020790504bb2.png)

However i can't see these slow calls on the Elasticsearch server-side, so it has to be the network (i'd be surprised if this is the case, although it's possible), or it's the way my code is calling out (e.g NEST)

**Comment by Mpdreamz** [comment]
What does the output of the following look like?

`GET /_cat/thread_pool/?v&h=*`

I am looking to see if you have any rejections or whether the search queue at any point was at its maximum and starting queuing search requests. This could also explain the `AWAIT_TIME`.

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Please let us know if this issue is still a relevant priority for your usage?
