### ISSUE TITLE
Field Inference should not take into account DataMember attributes

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#4319]
**NEST/Elasticsearch.Net version**: 7.5.1

**Elasticsearch version**: 7.5.1

**Description of the problem including expected versus actual behavior**:

The current `PropertyMappingProvider` takes into account `DataMember` attributes and it should not. I feel like it should only look at only nest defined attributes and leave the property naming via `DataMember` attributes to my defined serializer. It should only look at the `PropertyName` attributes and fallback to the serializer to handle naming.

We have DTO models that we put `DataContact` and `DataMember` attributes just to control the serialization for only the API surface and configured our own NEST JSON.NET serializer to ignore the attributes (via `strategy.OverrideSpecifiedNames`) and use our naming strategy. It was a big WTF moment when this wasn't working, even though debugging it we saw our own naming strategy being called.

```
         private JsonSerializerSettings JsonSerializerSettingsFactory()
         {
            //.....
         }

         private void ModifyContractResolver(ConnectionSettingsAwareContractResolver resolver)
         {
             var strategy = ((DefaultContractResolver)_serializerSettings.ContractResolver).NamingStrategy;
             resolver.NamingStrategy = new CamelCaseNamingStrategy(strategy.ProcessDictionaryKeys, strategy.OverrideSpecifiedNames, strategy.ProcessExtensionDataNames);
         }
```

The fix we had to do was basically define a new custom `PropertyMappingProvider` and just return null because we don't use any Nest attributes and didn't want DataMembers to be used.

**Comment by russcam** [comment]
Relates: https://github.com/elastic/elasticsearch-net/issues/3107 and https://github.com/elastic/elasticsearch-net/pull/3304

I _think_ this one's a little tricky. Looking at the related issue and PR above, it was introduced because  indexing a document with `DataMemberAttribute` applied to properties, then searching on that document index with `.Field(...)` was incongruent; former indexing call would pick up the `DataMemberAttribute` when serializing the document but the latter search call on the document field using a lambda expression would not.

**Comment by MrKrypto** [comment]
This issue is causing problems for us in version 7.6.1. 
Th client has a Lucene.Net index they want to migrate to Elasticsearch. They index a DataContract that is used to generate published data from index queries. The queries need to filter on non-published fields, i.e. don't have the DataMember attribute. It seems once the you use the DataContract attribute, you have to either:
- use the workaround above and not use NEST attributes 
- create and map a new DTO
Any idea the likely outcome to this issue? Is it just - live with it?

**Comment by russcam** [comment]
Hey @MrKrypto, I'm not sure I completely understand the scenario you describe. Would you be able to put together a succinct but complete example that demonstrates the issue?

**Comment by russcam** [comment]
I'm going to close this issue as I think the current client behaviour of honouring `DataMemberAttribute` in both document serialization and referencing properties of documents in requests like search, is the correct thing to do. The client exposes a way to change behaviour for how properties get mapped with an `IPropertyMappingProvider` that can be provided to `ConnectionSettings`.

**Comment by niemyjski** [comment]
You should only use your own nest attributes. This is causing really hard to debug issues when round trip serialization gets messed up.
