### ISSUE TITLE
Scalar mappings are storing byte as short

### ISSUE THREAD

**Issue by einfoman** [elastic/elasticsearch-net#4377]
**NEST/Elasticsearch.Net version**: 7.5

**Elasticsearch version**: 7

**Description of the problem including expected versus actual behavior**:
When you use `Scalar` for mapping of `byte`-property, field is mapped as `short`. I guess it is a mistake, isn't?

See https://github.com/elastic/elasticsearch-net/blob/8b99472f6a47357c8d2d1164e75f393709641f37/src/Nest/Mapping/Types/Properties-Scalar.cs#L233-L237

**Comment by russcam** [comment]
It's no mistake 😄 

A `System.Byte` is an **unsigned** integer with a range from 0 to 255. Conversely, a `byte` in Java, which Elasticsearch is written in, is a **signed** integer with range -128 to 127. In order to store the full range of `System.Byte` then, a `short` field datatype needs to be used. Take a look at https://github.com/elastic/elasticsearch-net/issues/1643 for more info.

**Comment by einfoman** [comment]
Oops.. Sorry to disturb you

**Comment by russcam** [comment]
No worries @einfoman, good to check!
