### ISSUE TITLE
Elasticsearch.Net.UnexpectedElasticsearchClientException

### ISSUE THREAD

**Issue by nishantj261989** [elastic/elasticsearch-net#4425]
While performing load testing using JMeter with 500 user with the ramp up time of 30 seconds, we are getting below exception after some successful request :

Elasticsearch.Net.UnexpectedElasticsearchClientException: The operation was canceled. ---> System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.IndicesExists[TResponse](String index, IndexExistsRequestParameters requestParameters)
   at Nest.LowLevelDispatch.IndicesExistsDispatch[TResponse](IRequest`1 p)
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch)

We are using Elasticsearch.Net 6.4.0 and NEST 6.4.0 versions.

Could anyone here help us or provide any suggestion to fix the issue?

Thanks in Advance

**Comment by Mpdreamz** [comment]
Hi 

Before we dig in further can you repeat the `JMeter` run with the latest version:

https://www.nuget.org/packages/Elasticsearch.Net/6.8.3

The `6.8.x` version has been tested against all previous Elasticsearch `6.x` versions.

**Comment by Crazy1van** [comment]
We’re experiencing the same exact issue.  Elasticsearch 7.5.1 with a matching driver version running in .NET Core 2.1.  Our test client fine for a while, then starts throwing this exception when we ramp up the traffic.  We have also tried this on our old cluster running 6.4 with a 6.8 driver.  Same behavior (both from .NET Core 2.1 running on Kestrel).  Our clusters are  on-prem behind a firewall but all HTTP ports are open.

**Comment by russcam** [comment]
A small project that reproduces the issue seen would be extremely helpful in identifying if there is an issue, and what it might be

**Comment by Mpdreamz** [comment]
@Crazy1van @nishantj261989 just to cover all the obvious causes: are you reusing `ConnectionSettings` as per: 

https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/lifetimes.html

Also is this on Linux? or Windows? 

@nishantj261989 is this on Asp.NET Core as well?

**Comment by Crazy1van** [comment]
@russcam I'm trying to reproduce this consistently but so far no luck.  This happens sporadically and usually takes a while (1-2 hours) for the errors to start appearing.  Putting the web service under heavy load doesn't seem to trigger this behavior.  

@Mpdreamz 
It's running on Windows Server 2016.  The Elastic client is a static instance in a static class (reused by all threads in our web api).  I tried many options including increasing connection timeout and retry count, and retry timeout.  None of them seem to make a difference.

I am not seeing any corresponding error logs on the cluster so it seems the .NET code is where it's failing.  I will try with another version of .NET Core.

**Comment by nishantj261989** [comment]
@Mpdreamz Yes we are also using ASP.NET Core and its on Windows. This exception is occurring very frequently when we are performing load testing with only 500 users.

**Comment by Mpdreamz** [comment]
Possibly related: https://stackoverflow.com/questions/60284951/net-core-with-elasticsearch-in-docker-blocked-by-connection-limit

Sorry to keep prodding can you share a bit more about the way Kestrel is hosted @nishantj261989 and @Crazy1van ?


Do these timeouts coincide with response times increasing from the server?

**Comment by russcam** [comment]
Do you have any further info, @Crazy1van / @nishantj261989, that might help in being able to narrow down a root cause?

**Comment by Crazy1van** [comment]
Yes, sorry for the late reply.  I ended up narrowing it down to a specific root cause.  The web API code I was using was indeed written in .NET Core 2.1, but it was using a .NET Framework 4.7.2 library for all of the Elastic functionality (I forgot about that).  I did some testing and it appears that .NET Framework (at least 4.7.2) has some sort of a serious bug with their HttpClient implementation.  Once I converted the library to .NET Core 2.1, the problem went away.  Our code has been running rock solid for months with very high TPS. 

I would suggest that anyone else experiencing this issue should try to switch to .NET Core 2.1 or later.  It is worth noting that this issue may never manifest itself for some users.  We only experienced this during bursts of high traffic.  I hope this helps.

**Comment by russcam** [comment]
Thanks for reporting back @Crazy1van. Happy to hear that the issue has been addressed by moving to .NET Core 2.1 🙂 

These kinds of issues can often be tricky to debug and perform a root cause analysis to identify the underlying issue, to determine if it's something in the client that can be addressed.

I'm going to close this issue. @nishantj261989, if there's a repro that can reliably reproduce the issue, please feel free to add additional information and we can look at reopening this.

**Comment by KrzysztofBranicki** [comment]
Is it to be expected that Nest will throw `UnexpectedElasticsearchClientException` (containing `OperationCanceledException` inner exception) if I will cancel the `CancellationToken` passed to the async operation?
