### ISSUE TITLE
Default serializer behavior changed between version 6 and 7 

### ISSUE THREAD

**Issue by tamasvajk** [elastic/elasticsearch-net#4696]
Using _NEST.JsonNetSerializer_ in NEST 7 changes the **default** serialization behavior from NEST 6. _NEST.JsonNetSerializer_ is using the default serialization settings from Json.NET, while NEST 6 was using the settings specified in `InternalSerializer.CreateSettings`. NEST 6 defined `NullValueHandling = NullValueHandling.Ignore` by default, while Json.NET (with NEST 7) uses `Include` by default. This is quite an important change if you were doing partial document updates by specifying null values for properties that should not be modified. (The old behavior was ignoring these fields, the new behavior updates these to `null`.)

One can achieve the same behavior by specifying explicitly the `JsonSerializerSettings`, but the default behavior changed, and I couldn't find any mention of this in the documentation.

**Comment by russcam** [comment]
Hi @tamasvajk 

the 7.x NEST.JsonNetSerializer serialization behaviour is the same as the 6.x NEST.JsonNetSerializer serialization behaviour. The internal serializer in 7.x has different serialization behaviour to the internal serializer in 6.x; [we have documented the changes that we're aware of](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/nest-breaking-changes.html#_utf8json_for_serialization_2). 

The internal serializer in both 7.x and 6.x has different default serialization behaviour to NEST.JsonNetSerializer. The intention with NEST.JsonNetSerializer is that it uses the default Json.NET serializer settings, and can be customized to suit user needs. We had a discussion at the time about whether NEST.JsonNetSerializer should be configured with serializer settings similar to the default serialization behaviour of the internal serializer and decided not to, thinking that a user using NEST.JsonNetSerializer is likely to also configure it to suit their serialization needs that are not met by the internal serializer.

**Comment by tamasvajk** [comment]
Thanks for the clarification. I didn't realize that `InternalSerializer` in 6.x is not the same as 6.x `Newtonsoft.Json`. It probably confused me that the `InternalSerializer` also uses `JsonSerializerSettings`. 
https://github.com/elastic/elasticsearch-net/blob/6.x/src/Nest/CommonAbstractions/SerializationBehavior/InternalSerializer.cs#L130

**Comment by russcam** [comment]
6.x uses an internalized version of Json.NET, which is IL rewritten and merged into NEST 6.x. For all intents and purposes, consider it a serializer that has the _same_ behaviour as Json.NET but is _not_ Json.NET because it exists in a different assembly in a different namespace.

In NEST 6.x+, there are effectively two serializers

- `RequestResponseSerializer`, the serializer to use for requests and responses. This is always the internal serializer and its behaviour cannot be changed
- `SourceSerializer`, the serializer for documents and document related fields. By default, this also uses the internal serializer, but can be changed through [custom serialization](https://www.elastic.co/guide/en/elasticsearch/client/net-api/6.x/custom-serialization.html), For example, using the Nest.JsonNetSerializer changes this serializer.

I think we have the changes between 6.x and 7.x internal serializers covered in the [docs](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/nest-breaking-changes.html#_utf8json_for_serialization_2), but if there are cases that seem missing, please do raise them.

I hope this helps, @tamasvajk. Are you happy for me to close this issue?
