### ISSUE TITLE
NEST API Request exception when format is not JSON

### ISSUE THREAD

**Issue by huey2531** [elastic/elasticsearch-net#4742]
**NEST/Elasticsearch.Net version**:
7.7.1
I think this bug has been around this 7.0 when the JSON parser was switched

**Elasticsearch version**:
7.x

**Description of the problem including expected versus actual behavior**:
when calling this api via NEST
/_cat/allocation?v=true&format=text

Exception
Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'{', actual:'s', at offset:0

**Steps to reproduce**:
            
```
           var request = new CatAllocationRequest();
           request.Verbose = true;
           request.Format = "text";

           client.Cat.Allocation(request); //this will throw an exception
```

**Expected behavior**
don't use JSON parser when format is not JSON
simply return the response as a string / text

**Comment by russcam** [comment]
Relates: https://github.com/elastic/elasticsearch-net/pull/4269

The high level client always expects JSON to be returned, in order to deserialize into `CatResponse<TCatRecord>`. The deserialization implementation cannot deserialize from a `text/plain` response, and it would be tricky to do so, because a user can control which fields are returned, without headers, making it [hard/not possible] to assign values in the response to the correct `TCatRecord` properties.

The low level client can be used to return the response as `text/plain`, which is the default for the low level client Cat APIs. The low level client is exposed on NEST through the `LowLevel` property

```c#
var client = new ElasticClient();
var response = client.LowLevel.Cat.Allocation<StringResponse>();
string text = response.Body;
```
