### ISSUE TITLE
Ids query construct empty request if passed array of ids is empty

### ISSUE THREAD

**Issue by bogdankolomiec706** [elastic/elasticsearch-net#4778]
**NEST version**: 7.6.1

**Elasticsearch version**: 7.6.0

**Description of the problem including expected versus actual behavior**:
```
var docIds = new string[] { };
var response = _elasticClient.Search<object>(s => s
                .Index(myIndexName)
                .Query(q => q.Ids(i => i.Values(docIds))));
```

Expeceted behavior: `response.Documents` contains no elements or exception occurred or unsuccessful response from elasticsearch returned.

Actual behavior: `response.Documents` contains random documents from index.

Reason: NEST lib constructs empty request - `{}` which results in such behaviour.

It seems to be unclear and bug-friendly. Perhaps it makes sense to consider other options.

**Comment by russcam** [comment]
Thanks for opening @bogdankolomiec706.

This is related to conditionless queries, which we are considering removing in the next major version. See https://github.com/elastic/elasticsearch-net/issues/4050 to discuss,

The query can be marked `.Verbatim()` to send exactly as is.

I'm going to close this issue in order to consolidate discussion on conditionless queries on #4050.
