### ISSUE TITLE
NEST generates sorting nested query for null values

### ISSUE THREAD

**Issue by SLavrynenko** [elastic/elasticsearch-net#4788]
**NEST/Elasticsearch.Net version**: 7.6.1

**Elasticsearch version**: 7.7.0

**Description of the problem including expected versus actual behavior**:
I have the following code for generating sorting part of Elastic query:

```
            return sortDescriptor
                .Field(
                    f => f
                        .Field(sortField.FieldName)
                        .Order(sortDirection == ContractContactSortOperator.Descending
                            ? SortOrder.Descending
                            : SortOrder.Ascending)
                        .Nested(n => n
                            .Path(sortField.NestedPath)
                            .Filter(sortField.FilterSelector)))
                .Descending(f => f.ContactId);

```
In the case when sortField.NestedPath = null and sortField.FilterSelector null I see the following query generated:

> {"track_total_hits":true,"query":{"bool":{"must":[{"bool":{"must":[{"term":{"ID":{"value":111}}},{"term":{"IsActive":{"value":1}}},{"term":{"DbId":{"value":14}}}]}}]}},"size":10,"sort":[{**"Field1":{"nested":{},"order":"asc"**}},{"ID":{"order":"desc"}}],"_source":{"includes":["Id"]}}

this query still works fine but not correct as it shouldnt have this nested part.

**Expected behavior**
there should not be any nested part in the sorting for null values

We have just moved from NEST 2.5.8 and this code works there as expected (it doesnt generate nested part in the sorting of Elastic query)

could be related to #4787

**Comment by russcam** [comment]
The implementation of nested sorting is a little different between 2.x and 7.x; 

In 2.x, nested sorting is controlled by `NestedFilter` and `NestedPath`

https://github.com/elastic/elasticsearch-net/blob/68c8b62096ae37f52004b2f5582da42c866451c0/src/Nest/Search/Search/Sort/SortBase.cs#L45-L58

A `null` value for these will not be included in the serialized request.

In 7.x however, nested sorting is controlled by `NestedSort`, with the filter and path as properties on `NestedSort`

https://github.com/elastic/elasticsearch-net/blob/f1ffbf260132eb83ea4e7950c1bcf19ef679ee6f/src/Nest/Search/Search/Sort/NestedSort.cs#L61-L86

What this means in practice is that when

```c#
.Nested(n => ...)
```

is called, if the return value is not null, then the value will be serialized. This is why an empty object is serialized, representing the NestedSort, even though it has no properties, because both path and filter are null.

I think this is correct behaviour in the client, and the difference between 2.x and 7.x is because properties are now nested under another property, `"nested"`, in 7.x.

The code can be changed to

```c#
return sortDescriptor
                .Field(
                    f => f
                        .Field(sortField.FieldName)
                        .Order(sortDirection == ContractContactSortOperator.Descending
                            ? SortOrder.Descending
                            : SortOrder.Ascending)
                        .Nested(n =>
                            sortField.NestedPath is null && sortField.FilterSelector is null 
                            ? null
                            : n.Path(sortField.NestedPath)
                                .Filter(sortField.FilterSelector)))
                .Descending(f => f.ContactId);
```

to achieve similar behaviour as before.
