### ISSUE TITLE
DefaultMappingFor<T> not working for DeleteByQueryAsync<T>

### ISSUE THREAD

**Issue by ttutuncu** [elastic/elasticsearch-net#4958]
**NEST/Elasticsearch.Net version**: 7.8.1

**Elasticsearch version**: 7.5.2

**Description of the problem including expected versus actual behavior**:

I have a .net core consumer application. The DefaultMappingFor setting on the Connection works for Search and Bulk methods but for DeleteByQueryAsync method the field name mapping is not used and it defaults to camel case. In  our elastic index all the field names are lowercase. So when we call DeleteByQueryAsync our property name of **"AccountId"** gets converted to **"accountId"** therefore the field can not be found. It should be converted to **"accountid"** set in the mapping for my class. 

**Steps to reproduce**:

 1. I have a AccountAddressInfo class as below

```
public class AccountAddressInfo
    {
        public AccountAddressInfo();

        public string Phone { get; set; }
        public string CustomerName { get; set; }
        public int TargetUnitId { get; set; }
        public DateTime CreateDate { get; set; }
        public string City { get; set; }
        public int? DoorNumber { get; set; }
        public string TargetUnitName { get; set; }
        public string InvoiceAddress { get; set; }
        public string AddressStatusId { get; set; }
        public string CustomerCode { get; set; }
        public string OutdoorNumber { get; set; }
        public string AcceptCargo { get; set; }
        public string CityId { get; set; }
        public int CustomerTypeId { get; set; }
        public string AddressName { get; set; }
        public string ExceptSelectedUnits { get; set; }
        public string Quater { get; set; }
        public string CountryCode { get; set; }
        public string IntegrationCode { get; set; }
        public int CreateUnitId { get; set; }
        public string ValidAllUnits { get; set; }
        public string AccountAddressId { get; set; }
        public string Town { get; set; }
        public string TownId { get; set; }
        public string Street { get; set; }
        public string ExcludedUnits { get; set; }
        public string Poi { get; set; }
        public DateTime ModifyDate { get; set; }
        public string AccountId { get; set; }
        public string AcceptReceiverPayment { get; set; }
        public string IncludedUnits { get; set; }
        public string Mobile { get; set; }
        public string CustomerType { get; set; }
        public string Avenue { get; set; }
        public string Vtckn { get; set; }
        public int AccountTypeId { get; set; }
        public string AccountAddressVersionId { get; set; }
        public string District { get; set; }
    }
```

 2. I have another class AccountAddressElasticInfo which inherits AccountAddressInfo. I use it this way so I can have a timestamp when I use BulkAsync method.

```
public class AccountAddressElasticInfo : AccountAddressInfo
    {
        
        public DateTime Timestamp => DateTime.Now;
    }
```

3. I have set the `DefaultMappingFor<AccountAddressElasticInfo>` in the connection as below in `ConnectionSettings`

4. I call `DeleteByQueryAsync` method as follows:

```
var resp = await _elasticClient.DeleteByQueryAsync<AccountAddressElasticInfo>(q => q
                            .Query(q => q
                                    .Term(f => f.AccountId, value)).MaximumDocuments(100000));
```

5. The `DebugInformation `in the response is as follows. `AccountId `gets converted to `accountId`. Because my fieldname of AccountId is all lowercase in my elastic index no documents are deleted.

`Valid NEST response built from a successful (200) low level call on POST: /account_address/_delete_by_query?pretty=true&error_trace=true
# Audit trail of this API call:
 - [1] HealthyResponse: Node: https://elastic:redacted@172.31.211.69:9200/ Took: 00:00:00.2202356
# Request:
{"query":{"term":{"**accountId**":{"value":"8D5F2F5162092D4E83C0C0700039D676"}}},"max_docs":1000000}
# Response:
{
  "took" : 2,
  "timed_out" : false,
  "total" : 0,
  "deleted" : 0,
  "batches" : 0,
  "version_conflicts" : 0,
  "noops" : 0,
  "retries" : {
    "bulk" : 0,
    "search" : 0
  },
  "throttled_millis" : 0,
  "requests_per_second" : -1.0,
  "throttled_until_millis" : 0,
  "failures" : [ ]
}`

6. If I add `DefaultFieldNameInferrer` to my Connection settings as follows, I get a successful delete with `DeleteByQueryAsync<T>` call.

`.DefaultFieldNameInferrer(p => p.ToLower(new CultureInfo("en-US")))`

7. I observed that `SearchAsync` and `BulkAsync` methods still work with the mappings by changing with false strings in the mapping and also the `DeleteByQueryAsync` works due to the `DefaultFieldNameInferrer` setting.

**Expected behavior**

Expected behavior should be that `DeleteByQueryAsync` should also take into account my `.DefaultMappingFor<AccountAddressElasticInfo>` setting without the `DefaultFieldNameInferrer` setting.

**Provide `ConnectionSettings` (if relevant)**:

```
connectionSettings = new ConnectionSettings(new Uri(url))
                    .DefaultIndex(defaultIndex)
                    .ServerCertificateValidationCallback((o, certificate, arg3, arg4) => true)
                    .DefaultMappingFor<AccountAddressElasticInfo>(i => i
                    .IndexName(defaultIndex)
                    .PropertyName(p => p.ValidAllUnits, "validallunits")
                    .PropertyName(p => p.AccountAddressId, "accountaddressid")
                    .PropertyName(p => p.Town, "town")
                    .PropertyName(p => p.TownId, "townid")
                    .PropertyName(p => p.Street, "street")
                    .PropertyName(p => p.ExcludedUnits, "excludedunits")
                    .PropertyName(p => p.Poi, "poi")
                    .PropertyName(p => p.AccountId, "accountid")
                    .PropertyName(p => p.AccountAddressVersionId, "accountaddressversionid")
                    .PropertyName(p => p.AcceptReceiverPayment, "acceptreceiverpayment")
                    .PropertyName(p => p.IncludedUnits, "includedunits")
                    .PropertyName(p => p.Mobile, "mobile")
                    .PropertyName(p => p.CustomerType, "customertype")
                    .PropertyName(p => p.Avenue, "avenue")
                    .PropertyName(p => p.Vtckn, "vtckn")
                    .PropertyName(p => p.AccountTypeId, "accounttypeid")
                    .PropertyName(p => p.CreateUnitId, "createunitid")
                    .PropertyName(p => p.ModifyDate, "modifydate")
                    .PropertyName(p => p.IntegrationCode, "integrationcode")
                    .PropertyName(p => p.InvoiceAddress, "invoiceaddress")
                    .PropertyName(p => p.Phone, "phone")
                    .PropertyName(p => p.CustomerName, "customername")
                    .PropertyName(p => p.TargetUnitId, "targetunitid")
                    .PropertyName(p => p.CreateDate, "createdate")
                    .PropertyName(p => p.City, "city")
                    .PropertyName(p => p.DoorNumber, "doornumber")
                    .PropertyName(p => p.TargetUnitName, "targetunitname")
                    .PropertyName(p => p.AddressStatusId, "addressstatusid")
                    .PropertyName(p => p.Quater, "quater")
                    .PropertyName(p => p.CustomerCode, "customercode")
                    .PropertyName(p => p.OutdoorNumber, "outdoornumber")
                    .PropertyName(p => p.AcceptCargo, "acceptcargo")
                    .PropertyName(p => p.CityId, "cityid")
                    .PropertyName(p => p.CustomerTypeId, "customertypeid")
                    .PropertyName(p => p.AddressName, "addressname")
                    .PropertyName(p => p.ExceptSelectedUnits, "exceptselectedunits")
                    .PropertyName(p => p.CountryCode, "countrycode")
                    .PropertyName(p => p.District,  #"district")
                    .PropertyName(p => p.Timestamp, "@timestamp")
                    .IdProperty(p => p.AccountAddressVersionId));
```

**Provide `DebugInformation` (if relevant)**:

```
Valid NEST response built from a successful (200) low level call on POST: /account_address/_delete_by_query?pretty=true&error_trace=true
# Audit trail of this API call:
 - [1] HealthyResponse: Node: https://elastic:redacted@172.31.211.69:9200/ Took: 00:00:00.2202356
# Request:
{"query":{"term":{"accountId":{"value":"8D5F2F5162092D4E83C0C0700039D676"}}},"max_docs":1000000}
# Response:
{
  "took" : 2,
  "timed_out" : false,
  "total" : 0,
  "deleted" : 0,
  "batches" : 0,
  "version_conflicts" : 0,
  "noops" : 0,
  "retries" : {
    "bulk" : 0,
    "search" : 0
  },
  "throttled_millis" : 0,
  "requests_per_second" : -1.0,
  "throttled_until_millis" : 0,
  "failures" : [ ]
}
```

**Comment by russcam** [comment]
@ttutuncu thanks for reporting. This looks to be related to the same issue as #3929.

A workaround for now would be to also map the properties of `AccountAddressInfo` using `.DefaultMappingFor<AccountAddressInfo>`, until this can be addressed.

**Comment by russcam** [comment]
@ttutuncu I've spent some time investigating this issue, and looking at how 7.x behaves compared to 6.x and 5.x.

To demonstrate the behaviour across versions, I have a simplified example

```c#
private static void Main()
{
var defaultIndex = "documents";
var pool = new SingleNodeConnectionPool(new Uri($"https://ipv4.fiddler:9200"));
var settings = new ConnectionSettings(pool, new InMemoryConnection())
    .DefaultIndex(defaultIndex)
    .DisableDirectStreaming()
	.DefaultMappingFor<AccountAddressElasticInfo>(i => i
		.IndexName(defaultIndex)
		.PropertyName(p => p.AccountId, "ACCOUNTID")
		.IdProperty(p => p.AccountAddressVersionId)
	)
	.OnRequestCompleted(callDetails =>
    {
        if (callDetails.RequestBodyInBytes != null)
        {
            var json = JObject.Parse(Encoding.UTF8.GetString(callDetails.RequestBodyInBytes));          
            Console.WriteLine(
                $"{callDetails.HttpMethod} {callDetails.Uri} \n" +
                $"{json.ToString(Newtonsoft.Json.Formatting.Indented)}");
        }
        else
            Console.WriteLine($"{callDetails.HttpMethod} {callDetails.Uri}");
    });
    
	var client = new ElasticClient(settings);

	var response = client.DeleteByQuery<AccountAddressElasticInfo>(d => d
		.Query(q => q
			.Term(f => f.AccountId, "value")
		)
	);
}

public class AccountAddressInfo
{
	public string AccountAddressVersionId { get; set; }
	public string AccountId { get; set; }
}

public class AccountAddressElasticInfo : AccountAddressInfo
{
	public DateTime Timestamp => DateTime.Now;
}
```

_(for 5.x, `DefaultMappingFor<T>` is called `.InferMappingFor<T>` and `PropertyName()` is called `Rename()`)_.

In 5.x and 6.x the JSON produced is as expected

```js
{
  "query": {
    "term": {
      "accountid": {
        "value": "value"
      }
    }
  }
}
```

but for 7.x, the JSON produced replicates the bug that you reported

```js
{
  "query": {
    "term": {
      "accountId": {
        "value": "value"
      }
    }
  }
}
```

This bug can be traced to the introduction of https://github.com/elastic/elasticsearch-net/commit/1bc3e3533affdeedbe74f7414eb6883a5529c273#diff-77d424f3215b6b2a598bdecfe4fbeef7R222-R228, part of the work to move to Utf8Json serializer in https://github.com/elastic/elasticsearch-net/pull/3608, in 7.x.

I'm fairly sure that the reason this was introduced is to fix the problem whereby `DefaultMappingFor<T>`'s `PropertyName` mapping resolves `MemberInfo` through the Expression API, with the `MemberInfo` resolved from the _base_ type i.e. `DefaultMappingFor<AccountAddressElasticInfo>` with property `AccountId` will resolve to `MemberInfo` of `AccountAddressInfo`, with DeclaringType and ReflectedType of `AccountAddressInfo`. This is different to how `MemberInfo` is resolved through Reflection APIs. This is demonstrated with

```c#
void Main()
{

	Field.Infer<Base>(o => o.Property);	
	Field.MemberInfo<Base>();
	
	Field.Infer<Derived>(o => o.Property);
	Field.MemberInfo<Derived>();
}

public static class Field
{
	public static void Infer<T>(Expression<Func<T, object>> expression)
	{
		new FieldVisitor(expression);
	}
	
	public static void MemberInfo<T>() where T : Base, new()
	{
		var memberInfo = typeof(T).GetMember(nameof(Base.Property))[0];
		Console.WriteLine($"member info type: {typeof(T).Name}");
		Console.WriteLine($"member info declaring type: {memberInfo.DeclaringType.Name}");
		Console.WriteLine($"member info reflected type: {memberInfo.ReflectedType.Name}");
		Console.WriteLine();

	}
}

public class FieldVisitor : ExpressionVisitor
{
	public FieldVisitor(Expression expression) => Visit(expression);

	protected override Expression VisitMember(MemberExpression node)
	{
		Console.WriteLine($"node expression type: {node.Expression.Type.Name}");
		Console.WriteLine($"node member declaring type: {node.Member.DeclaringType.Name}");
		Console.WriteLine($"node member reflected type: {node.Member.ReflectedType.Name}");
		Console.WriteLine();	
		return base.VisitMember(node);
	}
}

public class Base 
{
	public string Property {get;set;}
}

public class Derived : Base
{
}
```

which prints

```
node expression type: Base
node member declaring type: Base
node member reflected type: Base

member info type: Base
member info declaring type: Base
member info reflected type: Base

node expression type: Derived
node member declaring type: Base
node member reflected type: Base // <-- Base through Expression API

member info type: Derived
member info declaring type: Base
member info reflected type: Derived // <-- Derived through Reflection
```

The _erroneous fix_ was to align resolution through the expression API with resolution through reflection such that the `DefaultMappingFor<T>` could be specified for both a base and derived type in 7.x

```c#
var settings = new ConnectionSettings(pool, new InMemoryConnection())
    .DefaultIndex(defaultIndex)
    .DisableDirectStreaming()
	.PrettyJson()
	.DefaultMappingFor<AccountAddressInfo>(i => i
		.IndexName(defaultIndex)
		.PropertyName(p => p.AccountId, "accountid")
		.IdProperty(p => p.AccountAddressVersionId)
	)
	.DefaultMappingFor<AccountAddressElasticInfo>(i => i
		.IndexName(defaultIndex)
		.PropertyName(p => p.AccountId, "ACCOUNTID")
		.IdProperty(p => p.AccountAddressVersionId)
	);
```

which the client accepts, but results in the bug reported. In contrast, attempting to do the above in 5.x and 6.x throws an `ArgumentException`

```
Property mapping 'p => p.AccountId' on type AccountAddressElasticInfo can not be mapped to 'ACCOUNTID' already mapped as 'accountid'
```

This is because ultimately, property mappings are held in a dictionary of `MemberInfo` keys and `IPropertyMapping` values

https://github.com/elastic/elasticsearch-net/blob/a355ca307f94e80f680819e11d7fe2d2a1e421ca/src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs#L88

### Fixing

I think it's important to explain that detail and discuss how `DefaultMappingFor<T>` is intended to behave before discussing fixes.

#### Option 1

One way to fix this would be to align 7.x's behaviour with 5.x and 6.x, by removing https://github.com/elastic/elasticsearch-net/commit/1bc3e3533affdeedbe74f7414eb6883a5529c273#diff-77d424f3215b6b2a598bdecfe4fbeef7R222-R228. This would mean that 7.x would now throw an argument exception when attempting to add default mapping for both a base and derived type.

This is the easiest fix to perform, addresses the reported bug and aligns behaviour with 5.x and 6.x. What might be surprising about this behaviour however is that the mapping of any base type property through the base type or any derived type affects the mapping for the whole hierarchy. Consider

```c#
var defaultIndex = "documents";
var pool = new SingleNodeConnectionPool(new Uri($"https://ipv4.fiddler:9200"));

var settings = new ConnectionSettings(pool, new InMemoryConnection())
    .DefaultIndex(defaultIndex)
    .DisableDirectStreaming()
	.DefaultMappingFor<AccountAddressElasticInfo>(i => i
		.IndexName(defaultIndex)
		.PropertyName(p => p.AccountId, "ACCOUNTID")
		.IdProperty(p => p.AccountAddressVersionId)
	);

var client = new ElasticClient(settings);

var response = client.DeleteByQuery<AccountAddressInfo>(d => d
	.Query(q => q
		.Term(f => f.AccountId, "value")
	)
);
```

This will end up serializing `f => f.AccountId` as `"ACCOUNTID"` for `AccountAddressInfo`, even though default mapping is configured for the derived type, `AccountAddressElasticInfo`. This will be the case for any type derived from `AccountAddressInfo` because the `MemberInfo` in property mappings points to the member on `AccountAddressInfo`.

#### Option 2

An alternative option would be to allow properties to be mapped differently for types, irrespective of inheritance. Consider

```c#
var settings = new ConnectionSettings(pool, new InMemoryConnection())
    .DefaultIndex(defaultIndex)
    .DisableDirectStreaming()
	.PrettyJson()
	.DefaultMappingFor<AccountAddressInfo>(i => i
		.PropertyName(p => p.AccountId, "accountid")
		.PropertyName(p => p.AccountAddressVersionId, "accountaddressversionid")
	)
	.DefaultMappingFor<AccountAddressElasticInfo>(i => i
		.PropertyName(p => p.AccountId, "ACCOUNTID")
	);
```

The `AccountId` property can be mapped differently for the base `AccountAddressInfo` and the derived `AccountAddressElasticInfo`. For `AccountAddressVersionId` property on `AccountAddressElasticInfo`, the behaviour could be to 

1. inherit the mapping from `AccountAddressInfo`

   This adds complexity because property mappings would need to be inspected for the base types for all properties of a derived type

or 

2. fallback to the default mapping

   This is simpler to implement, but perhaps more surprising.

This option would likely require keying `MemberInfo` and `IPropertyMapping` against the `T` in `DefaultMappingFor<T>`, which would need to be done in a non-breaking way in 7.x.

----

Irrespective of option, we would need clear documentation that explains the client behaviour.

What are your thoughts, @Mpdreamz?
