### ISSUE TITLE
How to skip more than int-size number of results?

### ISSUE THREAD

**Issue by OndrejPiza** [elastic/elasticsearch-net#4960]
**NEST/Elasticsearch.Net version**: 7.5.*
Hi,

how can I skip more than "int size" number of results? 

On search result, there is property **Total**, which is **long** type. But any methods, which allows me to paginate/skip results accepts only **int**, eg. **From()**, **Skip()**.

Or is it not intended to be able to skip more for performance reasons for example?

Thank you

**Comment by russcam** [comment]
Hi @OndrejPiza, 

`"from"` and `"size"` are both defined as integers in Elasticsearch, so the client exposes them both as such. 

Performing [_deep pagination_](https://www.elastic.co/guide/en/elasticsearch/guide/current/pagination.html) with from and size is not preferable, for performance reasons - each shard in Elasticsearch has to produce _size * from_ number of documents, for the coordinating node to then sort, in order to return _size_ number of documents starting at _from_. This is applicable not just to Elasticsearch, but to a lot of other distributed systems.

For forward only pagination through a large number of records, take a look at [search after](https://www.elastic.co/guide/en/elasticsearch/reference/7.8/paginate-search-results.html#search-after), or [scroll](https://www.elastic.co/guide/en/elasticsearch/reference/7.8/paginate-search-results.html#scroll-search-results). Scrolling keeps a search context alive on the cluster for a configurable amount of time, so having a large amount of scrolls open at any one time will consume cluster resources. Search after on the other hand, does not keep a search context alive, but may return duplicate results during pagination because it is a live view on the documents and so newly indexed documents may have an affect depending on how your paginating. Scroll uses a search context that represents a point in time, so does not exhibit this behaviour. I'd personally steer towards search after, if it's behaviour is amenable to what you're wanting to do.
