### ISSUE TITLE
Deserializing into POCO using dynamic run-time generated object type?

### ISSUE THREAD

**Issue by winzig** [elastic/elasticsearch-net#4982]
**Is your feature request related to a problem? Please describe.**

I have a property on my class being indexed into ES that is flagged as an `object` at compile-time, but at runtime when instantiating the object (prior to indexing), the property gets created as a special class type that gets defined at runtime. (We are using Roslyn features of .NET to compile a C# class at runtime, and generate a new type on the fly.) 

The reason we took this approach is we didn't want to hard-code the layout of this class, as we need it to be able to change in the field. When we tried treating it as a `dynamic` class, we found that ES would only index the top level property names in the object, and the deeper properties, arrays, and dictionaries just turned into empty arrays. 

So our dynamic class solution works **for indexing** into ES. Now the issue is, when we perform a query and get the documents back, that special `object` property is simply rendered as, essentially, a JObject, losing the PascalCase formatting we normally have in that object. 

**Describe the solution you'd like**

Is there a way we can override the property type at runtime, so that instead of Nest deserializing the property as `object` it uses our dynamic class type instead?

**Describe alternatives you've considered**

An alternative that might also work would be if we could specify that all of our documents be indexed using PascalCase instead of camelCase, since at the end of the day, we're really just bringing in the queried documents from ES and spitting them right out to JSON (and our project uses PascalCase for our JSON). 

**Additional context**

If you're having trouble understanding what we're doing:

Our `Message` class defines a `Metadata` property:

```csharp
[Nest.Object]
public object Metadata { get; set; }
```

We store this object as JSON in our database, and then when the `Message` is loaded, we deserialize the `Metadata` property from the JSON into our dynamic type:

```csharp
Metadata = JsonConvert.DeserializeObject("...JSON...", dynamicType);
```

This allows ES to index the entire object properly. But getting it back out from ES as that dynamicType does not work, since ES thinks the property is just an `object`.

**Comment by winzig** [comment]
My current work-around is that I switched ElasticSearch to leave my PascalCase property names alone when indexing:

```csharp
.DefaultFieldNameInferrer
(
    fieldName => fieldName
)
```

**Comment by Mpdreamz** [comment]
Hi @winzig very interesting use case. 

Our `LazyDocument` construct is **nearly** what you need I think, it allows you to read back an arbitrary portion of json and defer the serialization.

```
public LazyDocument Metadata { get; set; }
````

You can then call `instance.Metadata.As(Type t)` to do the deserialization when you have more type information. 

The problem is you can't actually create an instance outside of our assembly. If you could, you potentially just create a `LazyDocument(".....JSON....")` omitting the need for serializing to object. 

@russcam what are your thoughts explicitly supporting this scenario ?

The `DefaultFeldNameInferrer` is definitely needed if your essentially deserializing `object` to `JObject`, `JObject` respects our contract resolver and  `DefaultFeldNameInferrer` sets up our contractresolver.

Since you already rely on `Newtonsoft.Json` I'd be more inclined to ensure `object` is `JObject` so you can call: https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Linq_JToken_ToObject.htm

If you use NEST7.x you will need to wire up https://www.nuget.org/packages/NEST.JsonNetSerializer/ to use JSON.NET for your documents.

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Please let us know if this issue is still a relevant priority for your usage?
