### ISSUE TITLE
Add "Updateable" property to KeywordMarker token filter descriptor in NEST

### ISSUE THREAD

**Issue by trucchuspear-policymogul** [elastic/elasticsearch-net#5110]
We are using a custom analyser setup and want to utilise a file for Keyword Markers to control stemming.

The current KeywordMarker token filter descriptor is missing the Updateable property that enables automatic reindexing should the keyword marker file be updated.

This is related to this feature: https://github.com/elastic/elasticsearch-net/issues/4252 where the Updateable() attribute was added for the Synonym and SynoymGraph Token Filter descriptors.

The end result is that I would like to be able to set up by custom analyser programmatically like this:

```
var createIndexResponse = indexer.ElasticClient.Indices.Create(indexName, c => c
    .Settings(s => s
        .Analysis(a => a
            .Normalizers(n => n
                .Custom("useLowercase", c => c.Filters("lowercase"))
            )
            .TokenFilters(t => t
                .Stop("english_stop", s => s.StopWords("_english_"))
                .KeywordMarker("english_keywords", k => k.KeywordsPath("filelocation.txt").Updateable(true))
...
```

**Comment by stevejgordon** [comment]
Thanks for raising this @trucchuspear-policymogul. I have investigated with the Elasticsearch team and confirmed that the updateable property does not apply to keyword marker token filters currently, only synonym_graph and synonym filters.

An issue has been raised for this to be investigated for inclusion in Elasticsearch https://github.com/elastic/elasticsearch/issues/65355

I'll keep this issue open so that we can implement this for the NEST client after this is available inside ES.

**Comment by stevejgordon** [comment]
I'm going to close this as we'll pick up the work when the ES work is completed.
