### ISSUE TITLE
How to convert kibana query into C# code

### ISSUE THREAD

**Issue by Mahisandy** [elastic/elasticsearch-net#5255]
Hi All,
Can you help me out the how to convert kibana query into C#.If any third party tool we have please mention link.

**Comment by stevejgordon** [comment]
Hi @Mahisandy. 

This is probably best placed as a discussion rather than issue but the transfer functionality is not available the moment. NEST provides two approaches to construct queries, object initialiser and fluent. The fluent approach allows you define the elements of your search through strongly typed representations. Have you checked out the[ documentation on writing queries](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/writing-queries.html)? This provides some worked examples and is the best place to start.

**Comment by stevejgordon** [comment]
Closing due to lack of response.
