### ISSUE TITLE
Utf8JsonSerializer doesn't return arrays to pool on buffer resize

### ISSUE THREAD

**Issue by benaadams** [elastic/elasticsearch-net#5311]
**NEST/Elasticsearch.Net version**: 7.10.1 (all versions)

**Elasticsearch version**:
![image](https://user-images.githubusercontent.com/1142958/107120033-122ee600-6883-11eb-93b7-1576dc6e482b.png)

**Description of the problem including expected versus actual behavior**:

`BinaryUtil.FastResize` replaces the current array with a new array from the ArrayPool however that array will be untracked and discarded to be GC'd. If resizing happens multiple times during serialization then multiple arrays will be discarded this way.

https://github.com/elastic/elasticsearch-net/blob/e7585836f3f002d11706b939d3adb84a9426271d/src/Nest/Utf8Json/Internal/BinaryUtil.cs#L78-L94

**Steps to reproduce**:

Serialize a large object tree to Json that exceeds the initial buffer reservation. 

**Expected behavior**

Arrays rented from the pool are returned to the pool

I did have a look at fixing this https://github.com/elastic/elasticsearch-net/commit/cd2eda5c793fb510d8ceccea24099e27e40d1229, but it is quite pervasive and might be be easier to switch to something like System.Text.Json which should handle this for you; rather than having a custom Json serializer for the project?

**Comment by stevejgordon** [comment]
Thanks @benaadams - As discussed offline, I agree that STJ is likely easier for the next major release and something we're investigating already. Would have been nice if this hadn't cascaded quite so much to get an improvement in 7,x also.

**Comment by stevejgordon** [comment]
For `8.0.0-alpha.1` we have moved to `System.Text.Json`. We rely on their underlying improvements and performance work to hopefully achieve gain and consistency across serialization. We have some manual hooks for complex types with opportunities for further gains in the future, post GA. Given this work, I'm closing off this issue as we are unlikely to make changes in `7.x` due to knock-on effects and test failures we identified during early prototyping.
