### ISSUE TITLE
PostData<object> become only PostData after upgrading to ElasticSearch.Net 7

### ISSUE THREAD

**Issue by argelj289** [elastic/elasticsearch-net#5708]
**ElasticSearch.Net 7**:

Visual studio Intellisense found error when passing a dynamic parameter to Search<T>(PostData)

After upgrading the library from 5 to 7 this error is encountered

Should able to pass dynamic parameter to the method

**Comment by stevejgordon** [comment]
Hi @argelj289. Can you please provide some more information and a small working example of the code you're migrating so that I can provide some guidance? What is the IntelliSense error? There are breaking changes between 5.x and 6.x and again to 7.x which you're running into here. 

The main change between 5.x and 7.x is that the generic argument on the Search method is constrained to implementing `IElasticsearchResponse`. Possibly this is what you're seeing?

Here's a small example of sending a request using the low-level client:
```c#
private static void Main(string[] args)
{
	var client = new ElasticLowLevelClient();

	var a = new
	{
		query = new
		{
			match_all = new { }
		}
	};

	SendSearch(client, a);
}

public static void SendSearch(IElasticLowLevelClient client, dynamic search)
{
	var response = client.Search<BytesResponse>(PostData.Serializable(search));
	
	// TODO - Deserialize bytes from response
}
```

Again, it would be helpful to understand your requirement and existing code to provide a more specific answer.

Have you reviewed the 7.x documentation about [PostData](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/post-data.html) and [searching with the low-level client](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/elasticsearch-net-getting-started.html#_searching)? This may be useful if you haven't seen it already.

**Comment by stevejgordon** [comment]
@argelj289 Is this still an issue for you?

**Comment by stevejgordon** [comment]
Closing this stale issue.
