### ISSUE TITLE
Adding index save method as in the Python ES library

### ISSUE THREAD

**Issue by shravan2x** [elastic/elasticsearch-net#5720]
**Is your feature request related to a problem? Please describe.**
Missing feature parity between libraries for different languages.

**Describe the solution you'd like**
The ElasticSearch library for Python has a `save` method for indices that create if not exists and updates settings and mappings if it does. The logic is at https://github.com/elastic/elasticsearch-dsl-py/blob/58c02732658018333cfd5fa2f7b70d942773b0be/elasticsearch_dsl/index.py#L289. It would be great to have something similar to make porting code easy (and for convenience).

**Comment by stevejgordon** [comment]
Hi @shravan2x. Thanks for raising this feature request. That library is essentially a set of high-level helpers over the base Python client. It's certainly possible to consider adding a similar helper in the .NET client if it provides enough value. I'd like to spend some time in the future to review how this API works and if we can/should replicate it in .NET. 

I'm curious about how often you are porting code. Is that a one-off exercise or something you do more regularly?

I can see some benefit to such a helper but I'd also welcome your opinion and explanation on how you'd like to consume it from your .NET code which could help when designing the API.

To set expectations, the timescale for this will be some way off due to other priorities in the immediate term. I'll leave this issue for discussion and if we agree to add this helper, I will probably break it out into an API design proposal.

**Comment by stevejgordon** [comment]
Having considered this suggestion further, we don't feel this is necessary at this time. While it helps in a direct port scenario, it provides more choices for the consumer which deviate from the actual rest API support. We feel it may add confusion when the other methods which align to the rest API directly are available. Post 8.0.0 we will refocus on additional helpers and I have added a note to return to this at that point.
