### ISSUE TITLE
not map poco Id to es key _id

### ISSUE THREAD

**Issue by wdqzdd** [elastic/elasticsearch-net#5722]
my poco class
![image](https://user-images.githubusercontent.com/27991992/121460533-a51d8f80-c9df-11eb-8875-379fa34d5815.png)

poco Id auto mapping to es key _id， not let it map automatically，What do I do

![image](https://user-images.githubusercontent.com/27991992/121460594-c4b4b800-c9df-11eb-864b-75787a3fa608.png)

**Comment by stevejgordon** [comment]
Hi @wdqzdd. Thanks for the question.

By default, we infer that an `Id` property if present is used as the document ID. You can disable this completely by following [this section of the documentation](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/ids-inference.html#_disabling_id_inference). That documentation page also explains how to configure the use of a different property as the Id if you prefer.

I'm going to convert this issue to a discussion so that other developers with the same question may hopefully find this answer.
