### ISSUE TITLE
Intermittent SSL errors while calling ElasticSearch Cluster

### ISSUE THREAD

**Issue by sandeeppnaik** [elastic/elasticsearch-net#5880]
**NEST/Elasticsearch.Net version**: 7.7.1

**Elasticsearch version**: 7.7 (TLS support 1.0 and above)

**Description of the problem including expected versus actual behaviour**:
I have aspnet core client, that is calling ElasticSearch cluster. What I notice is, every once in a while, some requests return SSL errors.

![image](https://user-images.githubusercontent.com/22852913/125561884-b17a6d9d-f4d4-4e19-8f0f-3c8f1e99ae80.png)
Here we can see 8 of these errors occurred. 

**Expected behaviour**
SSL errors should not happen intermittently.

**Client setup**:
the client is registered as follows:
services.AddSingleton<IEsClient>(sp =>
			{
				var connectionPool = new SingleNodeConnectionPool(new Uri(serviceEndpoints.ESUrl));
				var settings = new ConnectionSettings(connectionPool);
				return new esclient(settings);
			});

**Provide `DebugInformation` (if relevant)**:
Part of the stack trace
``` System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) ```

**Comment by sandeeppnaik** [comment]
I wonder if the TLS used by the client is NONE at times ?
https://docs.microsoft.com/en-us/dotnet/api/system.security.authentication.sslprotocols?view=netcore-3.1#System_Security_Authentication_SslProtocols_None
Thanks in advance !

**Comment by stevejgordon** [comment]
HI @sandeeppnaik. 

The client defers to the underlying `HttpClient` or `HttpWebRequest` defaults for TLS. This will be consistent across all requests. The fact this is occurring intermittently leads me to suspect an issue between the client and server.

A few initial questions:

1. Which version of the .NET Core runtime are you using for the ASP.NET Core app?
2. Where and how is the client app being deployed?
3. Where is the Elasticsearch cluster running (on-prem, cloud) and is it self-managed or hosted?
4. How many nodes are in your cluster?
5. Since you're using the SingleNodeConnectionPool - Is Elasticsearch behind a load balancer/proxy? 
6. Where is TLS terminated in your architecture?

**Comment by sandeeppnaik** [comment]
Thanks @stevejgordon , I believe it would use the OS's TLS version
1. Which version of the .NET Core runtime are you using for the ASP.NET Core app?
a. The run time is aspnet core 3.1 

Where and how is the client app being deployed?
a. The app runs in a kubernetes pod, the container base image is mcr.microsoft.com/dotnet/core/aspnet:3.1
the TLS versions on the container are
command: openssl ciphers -v | awk '{print $2}' | sort | uniq
SSLv3
TLSv1
TLSv1.2
TLSv1.3
  
Where is the Elasticsearch cluster running (on-prem, cloud) and is it self-managed or hosted?
a. The cluster is running on AWS elasticsearch service

How many nodes are in your cluster?
a. 3 master and 8 data Nodes

Since you're using the SingleNodeConnectionPool - Is Elasticsearch behind a load balancer/proxy?
a. I guess it runs behind a load balancer. The load balancer configuration is internal to AWS. The team at AWS has confirmed there are no errors reported on the Load balancer. To back that, when I look at the trace of this request, I don't see it going further beyond this app.  

Where is TLS terminated in your architecture?
a. My guess is TLS might be getting terminated on the Load balancer before  the ES cluster

**Comment by sandeeppnaik** [comment]
OK, my analysis on the trace is incorrect. Please ignore that.

**Comment by stevejgordon** [comment]
@sandeeppnaik - From a quick review of the runtime source code, for .NET Core 3.1+ it seems that the following defaults are applied for `SslProtocols` if not explicitly configured. We don't configure this within the client and rely on the .NET defaults to control this behaviour.

```
Tls | Tls11 | Tls12 | Tls13
```

During the handshake, the client sends a list of SSL versions and the server chooses the best matching version from that list, so this should be correct. 

I can't speak to how the AWS Elasticsearch Service is configured for TLS or networking, but my best guess is that something might be misconfigured or intermittently failing. Is this a new issue or has it always been present? If the client configuration were incorrect then I'd expect this to fail consistently for all requests. I'd recommend raising this with AWS to see if they can identify why the TLS negotiation is sometimes failing.

The Elasticsearch clients go through rigorous testing and validation against the official Elasticsearch distribution coming from Elastic. Since the AWS Elasticsearch Service has incompatible APIs with Elasticsearch itself, either by missing APIs or has an incompatible format, we do not support it. Please consider using [Elastic Cloud](https://cloud.elastic.co/) for an official and formally supported hosted Elasticsearch distribution.

**Comment by sandeeppnaik** [comment]
Thanks Steve, I will post an update here once I solve this mystery !

**Comment by stevejgordon** [comment]
@sandeeppnaik I'll close this issue for now but please do feel free to update with any further details that may assist others if they run into this.
