### ISSUE TITLE
Performance degradation with 7.13 against 7.12

### ISSUE THREAD

**Issue by MartinDemberger** [elastic/elasticsearch-net#5910]
**NEST/Elasticsearch.Net version**:
NEST 7.12.1

**Elasticsearch version**:
7.13.0

**.NET runtime version**:
net5.0

**Operating system version**:
Windows 10

**Description of the problem including expected versus actual behavior**:
When I run a query with an aggregation the execution ist much slower against a elasticsearch server 7.13 than against 7.12.

With 7.13 the query is executed in an average von 4.8 ms
With 7.12 the query is executed in an average von 0.1 ms

I'm not sure if this is a problem of the NEST client or the elastic server. It this is the wrong place can you please move the report to correct repository.

**Steps to reproduce**:
https://gist.github.com/MartinDemberger/a58465ba5ddc2042ae1756040b2318df
 1. Start a local elastic server with version 7.13
 2. Execute the test in the appended project 10x and note the output
 3. Start a local elastic server with version 7.13
 4. Execute the test in the appended project 10x and note the output

**Expected behavior**
The runtime should be almost equal

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by stevejgordon** [comment]
Hi @MartinDemberger. Thanks for raising this and the comprehensive repro code. I made [some modifications](https://gist.github.com/stevejgordon/58ece739c50014e7b0e3f78f12a174fe) to analyse results over multiple searches, and did manage to reproduce this. After speaking to our search engineers they believe this is the result of a known issue which is fixed in [this issue](https://github.com/elastic/elasticsearch/pull/74260) which will be released in 7.14.0. I ran a further test against a pre-release version of 7.14.0 and indeed, the performance regression is removed. In fact, the results are looking faster overall.

```
7.12.0:
Aggs: 35,305.92ns
Collector: 17,084.70ns
Query: 160,051.20ns
Search loop time: 3,087ms

7.12.1:
Aggs: 38,216.61ns
Collector: 19,089.20ns
Query: 168,745.60ns
Search loop time: 3,518ms

7.13.0:
Aggs: 792,880.90ns
Collector: 805,869.18ns
Query: 53,972.00ns
Search loop time: 5,504ms

7.13.3:
Aggs: 765,656.90ns
Collector: 790,476.64ns
Query: 54,005.90ns
Search loop time: 4,773ms

7.14.0:
Aggs: 18,465.88ns
Collector: 17,370.50ns
Query: 96,179.00ns
Search loop time: 2,481ms
```

I don't think it's worth transferring this given that a fix is already merged.
