### ISSUE TITLE
Deserialize post request to NEST SearchData class

### ISSUE THREAD

**Issue by cklogs** [elastic/elasticsearch-net#5923]
**NEST/Elasticsearch.Net version**: 7.13.2

**Elasticsearch version**:  7.x

**.NET runtime version**: 5.0.0

**Operating system version**: Windows 10 Pro: 19042.1110

**Description of the problem including expected versus actual behavior**:

I am trying to use the NEST SearchData class  as the bound body parameter on my controller. This reason for this is that I am wrapping the elastic search queries in my own API. 

My intention is to:

1. Send a pure elastic search body to my wrapped API
2. Deserialize that body to the NEST SearchData object
3. Based on business rules, add some standard queries to the SearchData object
4. Pass the updated SearchData object along to the elastic client.

I have noticed that it sometimes works, but fails for certain queries. I describe one such query below.

In addition to this issue, I am curious if it is even appropriate to try and map the body parameters to the SearchData class. Please advise on best practices here.

**Steps to reproduce**:
 1. Create a basic ASP.NET Core controller with a single POST route. Expose the NEST SearchData as the bound body parameter
```
[HttpPost("elasticSearch")]
[Produces("application/json")]
public async Task<ActionResult<IPagedCollection<MySearchDo>>> SearchAsync([FromBody]SearchRequest searchRequest) {
	var mySearchDos = await elasticSearchService.SearchAsync(searchRequest).ConfigureAwait(false);
	return Ok(mySearchDos);
}
```
 2. Call this API with a simple POST request that has aggregations:
```
{
  "from": 0,
  "size": 10,
  "aggs": {
    "agg_terms_productTypeId": {
      "terms": {
        "field": "productTypeId"
      }
    }
  }
}
```
 3. A NEST action filter is hit before the controller method is ever called. The following response error is returned:
```
{
    "errors": {
        "aggs.agg_terms_assetTypeId.terms.agg_terms_assetTypeId": [
            "Could not create an instance of type Nest.IAggregationContainer. Type is an interface or abstract class and cannot be instantiated. Path 'aggs.agg_terms_assetTypeId.terms', line 6, position 14."
        ]
    },
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-c2cff946c3ac3648a4fc2b877d9d00da-b088817b8f6b3a41-00"
}
```

**Expected behavior**
Query should be serialized correctly to the SearchData model.

Thanks in advance for your consideration.

**Comment by stevejgordon** [comment]
Hi @cklogs,

I'd like to address this question first:

> In addition to this issue, I am curious if it is even appropriate to try and map the body parameters to the SearchData class. Please advise on best practices here.

In most situations, I would say that this is not appropriate for two primary reasons. Firstly, as you've discovered, these types don't (de)serialise in some cases without custom serialisation code. Secondly, unless the consumers of your API are fully trusted, this poses a potential security risk, since anyone with access to your API can run arbitrary searches in your cluster. This could include searching across all indices, perhaps even system indices. In addition, they could run a large, complex query which could impact your cluster performance. For such situations, 

I would recommend that you design your own abstractions over the search options you wish to expose via your API and ensure you validate requests before running them against the cluster. You could design a lighter model for passing the search between your APIs which can be more easily (de)serialised, exposing just the elements you require.

Coming back to the issue you are experiencing, the request and response objects, particularly those around searches are quite complex models to align features of Elasticsearch. We handle serialisation of those internally using custom formatters since default serialiser behaviour doesn't work with them out of the box. In the current version of NEST, we use a specialised version of the `Utf8Json` serialiser, with formatters designed for more complex types. ASP.NET Core will be using its default serialiser during model binding, when attempting to bind complex types from the body of the request. In .NET 5 this defaults to the `System.Text.Json` serialiser.

In order to make this work, you would need to create a custom converter for these types and configure the ASP.NET Core serialiser to use those. This is not something we would provide in this version of NEST since these types are designed to be used to send and receive strongly-typed requests and responses specifically with Elasticsearch and the `Utf8Json` serialiser. As a side note, for the next version of NEST I am planning to use System.Text.Json as the primary serialiser and I am working through the process of customising the default behaviour for custom converters. 

I hope this helped explain the reason for the failure you are experiencing and provides some general guidance on how to proceed. Has this answered your questions?
