### ISSUE TITLE
Index Exists method issue

### ISSUE THREAD

**Issue by shassaan** [elastic/elasticsearch-net#5928]
**NEST/Elasticsearch.Net version**: 7.13.2

**Elasticsearch version**: 7.9.0

**.NET runtime version**: .NET 5.0

**Operating system version**: Ubuntu 20.04

**Description of the problem including expected versus actual behavior**:
The problem is with this `await client.Indices.ExistsAsync(index);` function
When the index does not exist it returns the response with the `IsValid` key false.

**Steps to reproduce**:
 1. Call this `await client.Indices.ExistsAsync(index);` using IElasticClient.
 2. Check the `IsValid` key in response

**Expected behavior**
The expected behavior should be that the `IsValid` key should be `true` because the request was successful but the `Exists` key should be false if the Index is not present in ElasticSearch.

Thanks and Regards.

**Comment by stevejgordon** [comment]
Hi @shassaan! Thanks for your contribution.

I had the same confusion over this myself and agree that it can be argued that this is the wrong behaviour. However, this is currently [by design](https://github.com/elastic/elasticsearch-net/issues/4684#issuecomment-644504297) that a 404 is considered an invalid response, regardless of the endpoint being called. It can be argued both ways which is more suitable for the exists cases. It's not something we will change in 7.x since it would be a breaking change, however, I do intend to review it again for 8.x and already have it on my list.
