### ISSUE TITLE
Please try to avoid using System.* packages of version 5.0 or later when you are not targeting net50

### ISSUE THREAD

**Issue by StingyJack** [elastic/elasticsearch-net#5954]
These packages were really intended for .net5 users, and those of us on .netcoreapp3.1 can get a bunch of dependency  mismatch warnings when a v5 System package is thrown into the mix.  This could be viewed as a breaking change and should have been avoided if at all possible. 

Version 7.11 of the Elasticsearch.net package is the first to use this when targeting netstandard (its actually from the Elastic.Transport package and [this PR](https://github.com/elastic/elastic-transport-net/pull/9)) .  That is all. Thank you for reading.

**Comment by stevejgordon** [comment]
@StingyJack I've not seen any formal guidance which suggests the latest `System.*` are only intended for newer runtimes. Do you have a source for that statement? The packages target various netstandard and .NET runtimes and support OOB installation. I know that OpenTelemetry for example also depends on `System.Diagnostics.DiagnosticSource 5.0.1` since that offers some required features,

I agree there are challenges in taking dependencies which may conflict with other packages that we do try to avoid. Sometimes those newer packages include features of bug fixes we require.

The change you highlight in `Elastic.Transport` is not yet used in a released version of the NEST client. We will switch to that transport layer in `8.0.0`. We took a dependency on `System.Diagnostics.DiagnosticSource 5.0.0` in `Elasticsearch.Net` to resolve some wider compatibility issues some consumers were experiencing.

Are you running into specific package conflicts we can review and test?

**Comment by StingyJack** [comment]
> I've not seen any formal guidance which suggests the latest `System.*` are only intended for newer runtimes.

@stevejgordon  - you probably wont. [This](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/plan#supported-platforms) is about the closest thing to admission I think we are going to get, and I think many other packages got a bump to version 5 that coincided with the net5 release as well. I'm sure that even the v5 packages _look_ like they are OK to use and work in many cases, but they [dont work in all case](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/plan#supported-platforms)s. It could be due to nuget or visual studio and not the packages themselves, but we dont have time to deal with these kind of headaches so we are skipping net5 and going from netcoereapp3.1 to net6 if it looks favorable to do so. 

Just from MSFT changing al of the hosted build agents for Azure Dev Ops to use net5 broke many of our pipelines that were fine with 3.1. We had to add steps to use 3.1 as part of the pipelines.
