### ISSUE TITLE
Add support for index.translog.retention settings

### ISSUE THREAD

**Issue by jcachat** [elastic/elasticsearch-net#6072]
I need to adjust the values of the index.translog.retention settings when creating an index template.  My servers are running out of disk space when I do large data loads because the age defaults to 12h.

But it looks like those settings are not available in TranslogSettingsDescriptor.  Can they be added?

**Comment by stevejgordon** [comment]
Apologies for the delay @jcachat . I'll take a look at this.

**Comment by stevejgordon** [comment]
@jcachat Checking through, I think that these were not added as they are [deprecated and are ignored since 7.4](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-translog.html#index-modules-translog-retention). Which version of Elasticsearch are you using. Per the documentation, perhaps soft deletes retention is the setting you require? That is already included in NEST.

**Comment by jcachat** [comment]
Thanks for looking in to that.  I am currently on 7.3 and had not seen that those settings have been deprecated.

The problem I am having is that I run ES in the cloud where they have limited disk sizes.  When I do initial data loads, the transaction logs are filling up the disk and causing out of disk space errors.  I was specifically looking to change the index.translog.retention.age setting because it defaults to 12h and is the cause of the excessive disk space usage during loads.  

I think you may be right and I need to be looking at index.soft_deletes.retention_lease.period instead.  You can close this issue - I am already behind in upgrading and can manually set index.translog.retention.age if needed in the mean time.

Thanks again!
