### ISSUE TITLE
ConnectionSettings.ServerCertificateValidationCallback does not use System.Net.Security.RemoteCertificateValidationCallback

### ISSUE THREAD

**Issue by Another-Ralf** [elastic/elasticsearch-net#6122]
For stringent certificate handling it would be helpful if ConnectionSettings.ServerCertificateValidationCallback would use the standard RemoteCertificateValidationCallback delegate from the framework. Currently it uses a slightly different func that would need extra lifting in a centralized certificate handling scenario.

Yours
`Func<object, X509Certificate, X509Chain, SslPolicyErrors, bool> callback`
vs
`public delegate bool RemoteCertificateValidationCallback(object sender, X509Certificate? certificate, X509Chain? chain, SslPolicyErrors sslPolicyErrors);`

The only difference seems to be the nullability of the certificate and chain. So i don't see the why it needs to be different from the standard here.

Proposal:
Keep ConnectionSettings.ServerCertificateValidationCallback as it is for backward compatibility and add another RemoteCertificateValidationCallback property to ConnectionSettings conforming to the standard delegate from the framework.

**Comment by stevejgordon** [comment]
Hi, @Another-Ralf. We specifically do not depend on the framework type in order to provide an abstraction that can work across our target frameworks. The library also targets net461, for example, where the signature of the framework types is different. Specifically, in this case, nullable reference types are not available on all targets. Our method needs to be independent of the target framework. While we could technically add framework dependent overloads, it because hard to maintain over time. For the same reason, we provide our own `ITransport` abstractions which decouple the public API of the library from the underlying HTTP implementation.

In your case, could you not provide a function somewhere to convert as necessary. A simple local function like this should be sufficient and doesn't feel like much extra lifting:

```c#
static Func<object, X509Certificate, X509Chain, SslPolicyErrors, bool> Interop(RemoteCertificateValidationCallback callback)
	=> (a, b, c, d) => callback(a, b, c, d);
```

If this is not practical, I'd like to understand your scenario further if you can share more details.

**Comment by Another-Ralf** [comment]
Wasn't aware that the callback signature isn't consistent over all frameworks. Good Argument. 

I was already doing something along the line of your code sample. It is practical but felt unnecessary at first.
