### ISSUE TITLE
Exception thrown when deserializing data with a mixture of string and array values in the same field

### ISSUE THREAD

**Issue by clearscreen** [elastic/elasticsearch-net#6143]
**NEST/Elasticsearch.Net version**:
7.16.0

**Elasticsearch version**:
7.16.2

**.NET runtime version**:
.NET Standard 2.1

**Operating system version**:
Ubuntu 18.04.6 LTS, Windows Server 2019 

**Description of the problem including expected versus actual behavior**:
NEST throws an exception when deserializing query results with fields that have a mixture of string and array values
`expected:'String Begin Token', actual:'[', at offset:990764`

**Steps to reproduce**:
 1. Have documents in an Elasticsearch index that have either a single string value or an array of strings in the same field
 2. Try to deserialize documents into POCOs using NEST

**Expected behavior**:
No exception thrown. Is there a more graceful way to handle the fact that Elasticsearch does not have a dedicated array data type and allows strings or arrays of strings to be indexed into the same field?

**Example JSON from Elasticsearch**:
The exception `expected:'String Begin Token', actual:'[', at offset:990764` is thrown when trying to deserialize event.category in this example
```
{
  "took" : 790,
  "timed_out" : false,
  "_shards" : {
    ...
  },
  "hits" : {
    "total" : {
      ...
    },
    "max_score" : 0.0,
    "hits" : [
      {
        ...
        "_source" : {
          "event" : {
            "provider" : "Microsoft-Windows-Security-Auditing",
            "module" : "security",
            "action" : "logon-failed",
            "type" : "windows",
            "category" : "authentication",
            "outcome" : "failure",
            "id" : "4625",
            ...
          }
        }
      },
      {
        ...
        "_source" : {
          "event" : {
            "provider" : "Microsoft-Windows-Security-Auditing",
            "module" : "security",
            "action" : "logon-failed",
            "type" : "windows",
            "category" : [
              "authentication"
            ],
            "outcome" : "failure",
            "id" : "4625",
            ...
          }
        }
      }
    ]
  }
}
```

**Example POCO**:
```
using Nest;
public class Event
{
    [Keyword(Name = "action")]
    public string Action { get; set; } = string.Empty;

    [Keyword(Name = "category")]
    public string Category { get; set; } = string.Empty;

    [Keyword(Name = "id")]
    public string Id { get; set; } = string.Empty;

    [Keyword(Name = "severity")]
    public string Severity { get; set; } = string.Empty;

    [Keyword(Name = "type")]
    public string Type { get; set; } = string.Empty;
}
```

**Comment by stevejgordon** [comment]
Hi, @clearscreen.

It's difficult for the client to resolve this automatically as it has to use the POCO model you provide as the source of truth for the source data it should expect in a search response hit. Because the category property is typed as a string, that's what the deserializer attempts to read and the exception is valid when an unexpected array token is included. The default serializer (and most serializers) are strict here because they can't know how you want to handle an array of values when the property can store only one.

A solution would be to handle this at ingest time and force a consistent format for the source document, so your POCO model can match the data being returned. If the category is ever more than one item, forcing the source to always contain an array would help as your C# model can then be typed as `string[]`.

From a consuming application perspective, I think you have two options when using the v7 client. You can provide your [own source serializer](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html) for the client to use, in which case you can fully control serialization and deserialization. If you register the Json.NET serializer, for example, you can include a custom converter to support both strings and arrays in the source.

An alternative workaround (although not ideal) is to consider using our `Union<T1, T2>` type for your `Category` property. Our built-in default serializer knows how to handle the `Union` type. For example:

```c#
var eventSearch = await client.SearchAsync<Events>(s => s.Index("events-test").MatchAll());

foreach (var hit in eventSearch.Hits)
{   
    foreach (var hit in eventSearch.Hits)
	{   
		var categories = hit.Source.Event.Category.Match(s => new [] { s }, a => a);

		foreach (var category in categories)
		{
			Console.WriteLine(category);
		}
	}
}

public class Events
{
    public Event Event { get; set; }
}

public class Event
{ 
    [Keyword(Name = "category")]
    public Union<string, string[]> Category { get; set; } = string.Empty;
}
```

As a side note, in v8, we are moving to depend on System.Text.Json for serialization and this will make it easier to plug in custom converter behaviour to individual properties without having to swap out the entire source serializer.

**Comment by stevejgordon** [comment]
@clearscreen I'm checking in to see if you were able to progress based on the suggestion above?

**Comment by stevejgordon** [comment]
Closing as stale.
