### ISSUE TITLE
Bool-Query with many must-Clauses needed

### ISSUE THREAD

**Issue by FrankAppGenerics** [elastic/elasticsearch-net#6426]
**Is your feature request related to a problem? Please describe.**
I need a solution to write a nest query which should have the following result:
```
"bool": {
	"must": [
		{
			"term": {
				"documentTags.value": {
					"value": "searchvalue1",
					"case_insensitive": true
				}
			}
		}
	],
	"must": [
		{
			"term": {
				"documentTags.value": {
					"value": "searchvalue2",
					"case_insensitive": true
				}
			}
		}
	]
}
```

I've tried many different ways, but NEST seems to optimize this always to:
```
"bool": {
	"must": [
		{
			"term": {
				"documentTags.value": {
					"value": "searchvalue1",
					"case_insensitive": true
				}
			}
		},
		{
			"term": {
				"documentTags.value": {
					"value": "searchvalue2",
					"case_insensitive": true
				}
			}
		}
	]
}
```

The query does not deliver the same result used in a nested query.

**Describe the solution you'd like**
A way to construct the above mentioned query.

**Comment by aakashranaa** [comment]
Hi, I hope it's not too late to reply. Since this is an open issue, here are my 2 cents -
Both of these queries are logically different and that's why they are producing different results. The query that you have written have two separate 'must' clauses, which will be combined with a logical OR. This means that the resulting documents will match either the first must clause or the second must clause (or both).

The second query, generated by NEST, has a single must clause that contains two nested term clauses. These clauses will be combined with a logical AND, so the resulting documents will match both clauses. 

The solution that you are looking is to write the first query in the correct way. You can use the 'Should' method instead of 'Must'. The 'Should' method works similarly to 'Must', but it combines clauses with a logical OR instead of a logical AND.
The resulting query would look like this - 
{
  "query": {
    "bool": {
      "should": [
        {
          "term": {
            "documentTags.value": {
              "value": "searchvalue1",
              "case_insensitive": true
            }
          }
        },
        {
          "term": {
            "documentTags.value": {
              "value": "searchvalue2",
              "case_insensitive": true
            }
          }
        }
      ]
    }
  }
}
You can further use 'minimumShouldMatch' according to your requirements. To conclude, IMHO, I don't think this is an issue as you can get the required result by using the correct clauses. I hope this helps.

**Comment by FrankAppGenerics** [comment]
Thanks for your answer, I've fixed this some weeks ago.

To do this I've analyzed the generated query, corrected the query and tried to find the necessary NEST Linq expression to generate the same query.

Sometimes I assume writing direct queries is easier than using NEST.
