### ISSUE TITLE
Using both nested and Match in one query with logical OR

### ISSUE THREAD

**Issue by AdiIndoSwiss** [elastic/elasticsearch-net#6654]
My query is like this 

            var response = elasticClient.Search<T>(s => s           
            .From(0)
            .Size(searchPluginSettings.NumberOfItems)
            .Index(searchPluginSettings.Index)
            .Query(q =>
                 q.Match(m => m
                     .Field("ean")
                     .Query(where).Boost(searchPluginSettings.WeightEan))
                 ||
                  q.Nested(m => m.Path("authors").Query(qn => qn.Match(n => n.Field("authors.name.keyword:" + @"""+where+@""").Boost(searchPluginSettings.WeightSpecificAttribute))
                )) );
               

new ConnectionSettings(pool).DisableDirectStreaming(pluginSettings.DisableDirectStreaming).EnableDebugMode();
I always get the results for ean = somevalue but not for nested ...

If i use seperately nested it works but if i use logical Or and combine both then it doesn't work..

Aditya

**Comment by stevejgordon** [comment]
Hi, @AdiIndoSwiss,

This appears to be a question rather than a bug report or feature request. We recommend questions are asked over on the community [discuss forum](https://discuss.elastic.co/) rather than as issues on this repo.

In your example the nested query appears to be used incorrectly as you are trying to manually format in the field name and query clause for the short request format. As there is no query defined, it's not being added to the request. Instead, try something like this:

```c#
var response = elasticClient.Search<T>(s => s
.From(0)
.Size(searchPluginSettings.NumberOfItems)
.Index(searchPluginSettings.Index)
.Query(q =>
     q.Match(m => m
         .Field("ean")
         .Query(where).Boost(searchPluginSettings.WeightEan))
     ||
      q.Nested(m => m.Path("authors").Query(qn => qn.Match(n => n.Field("authors.name.keyword").Query(where).Boost(searchPluginSettings.WeightSpecificAttribute))
    ))));
```

**Comment by stevejgordon** [comment]
Closing as answered.
