### ISSUE TITLE
GetIndexRequest fails on dynamic_templates serialization 

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#7221]
```
The converter 'Elastic.Clients.Elasticsearch.Serialization.UnionConverter+UnionConverterInner`2[System.Collections.Generic.IDictionary`2[System.String,Elastic.Clients.Elasticsearch.Mapping.DynamicTemplate],System.Collections.Generic.ICollection`1[System.Collections.Generic.IDictionary`2[System.String,Elastic.Clients.Elasticsearch.Mapping.DynamicTemplate]]]' read too much or not enough. Path: $['catalog-data-2023.01.31'].mappings.dynamic_templates | LineNumber: 4 | BytePositionInLine: 29.
```

This happens when I do a `GetIndexRequest` that returns the following json:

https://gist.github.com/Mpdreamz/ab38378c8be875b1821ee227febe72f1

**Comment by stevejgordon** [comment]
Thanks for raising this @Mpdreamz. I see the cause, which is missing implementation in the union converter. After fixing that, I've noticed some other issues deserializing this example response, which I will take care of.

- The `DynamicTemplates` property on the `TypeMapping` should ideally be typed as an `ICollection<IDictionary<string, Elastic.Clients.Elasticsearch.Mapping.DynamicTemplate>` rather than a union here. The code generator logic to simplify such properties seems to miss this one. For usability, it's worth considering the breaking change to improve this. If implemented, the property will need to be marked to use the `ICollectionSingleOrManyConverter`.
- The`DynamicTemplate.Mapping` property is generated as `Elastic.Clients.Elasticsearch.Mapping.Properties?` but should be `IProperty?`
