### ISSUE TITLE
Add feature to allow setting refresh=wait_for in DeleteByQuery

### ISSUE THREAD

**Issue by h-h-** [elastic/elasticsearch-net#7606]
**Is your feature request related to a problem? Please describe.**
I want to set `refresh` to `wait_for`. But I can only set it to `true` or `false`.
Currently using NEST 7.17.5

**Describe the solution you'd like**
Since the property `Refresh` of the `DeleteByQueryRequest` is a `bool?` there is no possibility to set it at `wait_for`.

This is possible:
```
var request = new DeleteByQueryRequest(_indicesNameForSearch)
{
	Refresh = true
};
```

I suggest adding an additional property which in turn sets `refresh=wait_for` when setting to true.
```
var request = new DeleteByQueryRequest(_indicesNameForSearch)
{
	WaitForRefresh = true
};
```

**Comment by stevejgordon** [comment]
Thanks for raising this, @h-h-. This would technically be a breaking change, so we need to consider this carefully for 7.x since it has the potential to impact more consumers. We should fix it in the [specication](https://github.com/elastic/elasticsearch-specification/tree/main/specification) so that generated v8 clients support `wait_for`.
