### ISSUE TITLE
FilterAggregation is missing in the 8.x library

### ISSUE THREAD

**Issue by rustunooldu** [elastic/elasticsearch-net#7877]
**Is your feature request related to a problem? Please describe.**
```FilterAggregation``` was supported in NEST, but isn't generated for the 8.x version of the client.
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-filter-aggregation.html

**Describe the solution you'd like**
The multi-bucket version of this aggregation (```FiltersAggregation```) is already implemented and can be used to achieve the same result, however it would be nice to re-introduce the ```FilterAggregation``` functionality to avoid the extra steps and potential performance impact as well.

**Comment by flobernd** [comment]
Thanks for reporting! This will be back as soon as I finish my work on the code generator. I'm closing this issue for now.

**Comment by KPGDL** [comment]
Bump

**Comment by flobernd** [comment]
@KPGDL There is no point in bumping this. As explained, it will be available after I finish the related work on the code generator. To be honest, this issue has rather low priority as there is a perfectly valid workaround that does not require a lot of extra effort to use (`FiltersAggregation`).

**Comment by flobernd** [comment]
Hi @gpetrou,

the `Filter` aggregation is fully supported in 8.13.*. You probably missed it, because of the way it's modelled in the [specification](https://github.com/elastic/elasticsearch-specification/blob/bda8a6d16e9b4b83fa44cf6f4d98af059b7ce0dc/specification/_types/aggregations/AggregationContainer.ts#L249-L258). Unless most of the other aggregations, it's not wrapped in a separate class, but uses the `Query` instead:

https://github.com/elastic/elasticsearch-net/blob/8db7bd4402db1a5e8e06354a94f4458b846ea5a6/src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/Aggregation.g.cs#L71-L72

**Comment by gpetrou** [comment]
Oh, I see. OK thanks.
