### ISSUE TITLE
NonStringIndexOption should have only 'no' value

### ISSUE THREAD

**Issue by maximpashuk** [elastic/elasticsearch-net#808]
Refer to documentation

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-core-types.html

For non-string core types 'index' property may have only 'no' value, 'not_analyzed' and 'analyzed' values are not applicable for non-string core types.

Hovewer in NEST 1.0 RC1 I can map non-string field as 'analyzed'.
Please remove Analyzed and NotAnalyzed values from this enum

**Comment by RobinRieger** [comment]
@gmarz / @Mpdreamz 

Is this correct that non string core types can only have the value of 'no'???

Quote from ES site:
"The other simple types (such as long, double, date etc) also accept the index parameter, but the only relevant values are no and **not_analyzed**, as their values are never analyzed." [here](https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping-intro.html)

How can you search on e.g. a number field, if it is set to 'No'?

**Comment by gmarz** [comment]
> Is this correct that non string core types can only have the value of 'no'???

They can also be`not_analyzed`, but that is the default value so it doesn't really need to be specified explicitly.  This is why we only map the value `No`.

> How can you search on e.g. a number field, if it is set to 'No'?

You wouldn't.  The field would have to be `not_analyzed` in order to be searchable.

**Comment by RobinRieger** [comment]
Thanks for the reply. 

Yeah kind of makes sense if that is the default value. I guess it just threw me because for a string you would also have a default value (have not checked the code what you use), I presume `not_analyzed` as well, but for that enum you kept the `not_analyzed`... Just a consistency thing I guess :confused: 

> How can you search on e.g. a number field, if it is set to 'No'?

Yeah, I figured you can't just didn't realise the default was `not_analyzed` hence kind of a  silly question given that I know that now :smile:

**Comment by gmarz** [comment]
Yea, that's a fair point- I can definitely see how it may be confusing.

For the sake of consistency, I wouldn't be opposed to either (1) removing `Analyzed` from `FieldIndexOption` which is the default for string fields, or (2) adding all valid options to both `NonStringIndexOption` and `FieldIndexOption` including defaults.

I prefer option 2.

Also, while on the topic- it would be nice to come up with better names for `FieldIndexOption` and `NonStringIndexOption`.

cc @Mpdreamz @russcam

**Comment by nerdomancer** [comment]
I want to ask this for clarification.

I had a mapping as follows in NEST v1.7:
```.Number (n => n.Name(p => p.Status).Store(true).Index(NonStringIndexOption.NotAnalyzed))```

After migrating to NEST v2.0.2, I should change it as follows to make this number searchable?
```.Number (n => n.Name(p => p.basvuruzarfistatu).Store(true))```

Because default value to Index() method in elasticsearch side will be mapped as ```not_analyzed```

Then if I mark the same code as follows it will not be searchable:
```.Number (n => n.Name(p => p.basvuruzarfistatu).Store(true).Index(NonStringIndexOption.No))```

This change had an impact of unexpected size to my code so I wanted to be sure.
Thanks.

**Comment by gmarz** [comment]
@nerdomancer yes, that's correct!
