### ISSUE TITLE
What is missing from full feature parity with NEST?

### ISSUE THREAD

**Issue by landlord-matt** [elastic/elasticsearch-net#8101]
**Is your feature request related to a problem? Please describe.**
We been using the new Elasticsearch client library Elastic.Clients.Elasticsearch for a while now and everything seems to be working as intended. However, the README of repository here as well as the official Elasticsearch documentation seems to suggest we should still use this with caution. (or at least 8.0.x).

> The 8.0.x versions do not offer complete feature parity with the existing NEST client. We therefore recommend you thoroughly review our [release notes and migration guidance](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/release-notes-8.0.0.html) before attempting to migrate existing applications to the Elastic.Clients.Elasticsearch library.

**Describe the solution you'd like**
The read me should clarify if this is still accurate and if this is the case, link to some sort of list of missing features. 

Perhaps [this was](https://github.com/elastic/elasticsearch-net/issues/7890) an attempt of this (says TBD). If nobody can think of anything, perhaps we should remove the warning against using it?

**Describe alternatives you've considered**
Simply writing that this is resolved since the added support for completion fields.

**Additional context**
That's pretty much it

**Comment by flobernd** [comment]
Hi @landlord-matt,

With the recent `8.13.*` releases, the `8.*` client does now support about 95% of the native Elasticsearch features.

If you never used NEST, you probably won't miss anything.

If you have used NEST before, you might notice that some of the helper functions / convenience features are missing. These are built on top of the native functionality and not ported over to the new client (yet). I will bring back some of the functionality over time, but definitely not anything 🙂 An example would be the auto-mapping feature that allowed you to automatically infer Elasticsearch types from CLR types for index creation etc.

Does that answer your question?

Pointing to the migration guide is still valid, because of the missing convenience features and the fundamentally changed architecture. However, this is only a concern if you migrate from `NEST` to `Elastic.Clients.Elasticsearch`.

**Comment by flobernd** [comment]
Hi @RomBrz

> could you tell me where i could look to know if this 95% at april/24 is improved?

I will release a reference documentation (xmldoc rendered by DocFx) shortly. You could use that to compare the API surface of the latest version with the API surface of a pre 8.13 one. This should give you an idea of what has been added in the 8.13.x release.

> If the feature parity with NEST now is 100%,

This is not the case and won't ever be the case. The reasons for this are explained in e.g. the migration guide or the [8.0 release notes](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/release-notes-8.0.0.html).

The 95% coverage is about the REST API surface of Elasticsearch. E.g. in the 8.12 client many aggregations were missing which are now supported in 8.13+. Most NEST high level helper functions are not available in the v8 client and some of them will never get re-implemented by design.

My above comment is still valid:

> If you have used NEST before, you might notice that some of the helper functions / convenience features are missing. These are built on top of the native functionality and not ported over to the new client (yet). I will bring back some of the functionality over time, but definitely not anything 🙂 An example would be the auto-mapping feature that allowed you to automatically infer Elasticsearch types from CLR types for index creation etc.

> the best approach would be update the Client from 7 to 8 while using the 7 Server. When the code is migrated, than migrate the server from 7 to 8 and just point the code to the 8 Server

This is definitely recommended as NEST (v7) will be end-of-life at the end of this year.

> The "compatibility mode" on Elastic Server 8 is still working OK with the latest Elastic.Net 7 Client?

Yes.

> another approach would be to migrate the server first and put it on compatibility mode ON, than the systems that use Elastic Server could start to migrate the Client from 7 to 8 to use in native mode instead of compatibility mode.

This is possible as well, but the client-first approach is probably easier.
