### ISSUE TITLE
Being more careful with releases

### ISSUE THREAD

**Issue by imperugo** [elastic/elasticsearch-net#8252]
Frequently updating a library is always a good thing, new features, more security, but also just the pleasure of seeing that you are using a project that is alive.
When this happens on such large and important projects like ElasticSearch it is really nice and I **thank you for the continuous work you are doing**.

Precisely for this reason, I would like to use a quote 'With great power comes great responsibility'.

Every time I update the SDK I get breaking changes out of the blue without having had any signals beforehand especially if I am updating a minor version which should never introduce breaking changes (see [SEMVER](https://semver.org/)) but this unfortunately does not happen.

I go to the site and look at the release hoping to find documentation explaining that now API "A" no longer exists and API "B" must be used, but this document is not there.

It would be nice to have it and, more importantly, before sawing off a method it should be marked as deprecated in some previous version.

This is not meant to be a criticism, let alone a complaint, but an insight into the experience of someone who uses your SDK on a daily basis.

Thank you again and keep up the good work

**Comment by flobernd** [comment]
Hi @imperugo, thanks for your kind feedback!

I understand that breaking changes are always painful, but sadly they are not avoidable a lot of times in the context of the Elasticsearch client. Let me give you some insights 🙂 

> Every time I update the SDK I get breaking changes out of the blue without having had any signals beforehand especially if I am updating a minor version which should never introduce breaking changes

The version numbers of the client are aligned with the ones from the server (at least for the `major.minor` part). This often leads to the assumption that the client is using semantic versioning - which is not the case. The `patch` version is indepentant and increased everytime the client releases an update. This allows us to do frequent updates (new server versions are released less than once per month) while still indicating server <-> client version compatibility.

Usually I try to limit breaking changes to cases where the code was broken before. Recently, I had to do more breaking changes due to switching to a completely new code generator and to be able to implement some previously completely unsupported functionality. The new client is finally getting close to a state of supporting every server endpoint, which means that the number of breaking changes will hopefully decrease in the near future.

> before sawing off a method it should be marked as deprecated in some previous version.

For cases where it's possible, I definitely try to deprecate old functionality first, before I remove it (e.g. the recent deprecation of the synchronous request methods). Most of the cases, however, are driven by changes to our specification. The specification is a formal definition of the API surface which is used to generate large part of the client (not only for .NET, but as well for other languages).

> I go to the site and look at the release hoping to find documentation explaining that now API "A" no longer exists and API "B" must be used, but this document is not there.

This changelog can be found in the [release notes](https://github.com/elastic/elasticsearch-net/releases) here on GitHub. I try to document all major breaking changes here and to provide some examples of how to migrate (I will add a section to the latest release as well as I'm currently missing this part). There is some CI work on my todo list to push the release notes to the official website again (this functionality is broken for a while..).

Thanks again for this valuable feedback!
