### ISSUE TITLE
Rename SearchDescriptor.Filter method to PostFilter

### ISSUE THREAD

**Issue by maximpashuk** [elastic/elasticsearch-net#997]
https://github.com/elasticsearch/elasticsearch-net/blob/c454cf6b58901d475f2dde505d8ab89bbc571166/src/Nest/DSL/SearchDescriptor.cs#L1064

You can see Filter method,
'filter' word was renamed to 'post_filter', indicating it applies after aggeregations.

See the documentation
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-post-filter.html

Old word 'filter' is deprecated. See
https://github.com/elasticsearch/elasticsearch/issues/7971#issuecomment-59227974

Can you rename method to "PostFilter"?
Or, for better compatibility, just add method PostFilter and mark Filter method as deprecated?

**Comment by ThomasSkyldahl** [comment]
How far does the backwards compatibility go back in NEST? 

http://www.elasticsearch.org/guide/en/elasticsearch/reference/0.90/search-request-post-filter.html

**filter** was deprecated in 0.90.8
and the new **post_filter** was introduced,

You could add the **PostFilter** and leave the **Filter** in the code and add a method comment in the documentation that *Filter* is deprecated in versions after 0.90.8 and if people are using later versions of elasticsearch they should use **PostFilter** instead.

You don't need to mark **Filter** as deprecated with an attribute if you still want to support older versions than 0.90.8

Send both of to Elasticsearch in the request and let Elasticsearch choose the way to handle the issue where both parameters are send in the request.

**Comment by Mpdreamz** [comment]
Elasticsearch still supports `filter` and `post_filter` as synonyms in 1.0 and sending both seems wasteful :) and we in fact still send `Filter()` as `filter` to Elasticsearch.

`Nest 1.x` supports `Elasticsearch 1.x` there are more breaking changes then just this one in order to claim `0.90.8` support see here: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/breaking-changes.html

For `NEST 2.0` we will rename `Filter` to `PostFilter` since the chances are high that `filter` support from the parser on elasticsearch's side will be removed in `Elasticsearch 2.0` as well.

**Comment by ThomasSkyldahl** [comment]
That wasn't exactly what I meant, if you added PostFilter and left Filter
untouched then People that know of the breaking change can use the correct
PostFilter and others that dont care can keep using Filter.

and it would only serialize filter or post_filter if they are set to
something, so if somebody where foolish enough to use both by mistake, I
would just leave it up to the elasticsearch server to choose what to do.

For myself it just seems strange that we can't follow the latest docs from
Elasticsearch with NEST as some options are named differently than the
official docs.

And adding PostFilter wouldn't break any compatibility.
